/**
 * Automation Pro copy (V3.4). Courier, store and channel names (Steadfast,
 * Shopify, WhatsApp, COD, SKU) stay English in Bangla, the way sellers say them.
 */
export const automationEn = {
  'auto.title': 'Automation',
  'auto.subtitle': 'When something happens, check it, then act, wait or branch. Safe steps only.',
  'auto.tab.workflows': 'Workflows',
  'auto.tab.recipes': 'Ready recipes',
  'auto.tab.runs': 'Run history',
  'auto.tab.failures': 'Failures',
  'auto.tab.tasks': 'Tasks',
  'auto.new': 'New workflow',
  'auto.back': 'All workflows',
  'auto.readOnly': 'You can watch workflows. The owner or a manager builds and switches them on.',
  'auto.empty': 'No workflows yet',
  'auto.emptyHint': 'Start from a ready recipe, or build your own.',
  'auto.enabled': 'On',
  'auto.disabled': 'Off',
  'auto.enable': 'Switch on',
  'auto.disable': 'Switch off',
  'auto.edit': 'Edit',
  'auto.version': 'Version {n}',
  'auto.unpublished': 'Unpublished changes',
  'auto.notPublished': 'Not published yet',
  'auto.runs7d': 'Last 7 days: {ok} completed, {failed} failed, {waiting} waiting',
  'auto.col.workflow': 'Workflow',
  'auto.col.trigger': 'Trigger',
  'auto.col.status': 'Status',
  'auto.col.step': 'Step',
  'auto.col.when': 'When',
  'auto.col.reason': 'Reason',

  'auto.metrics.runs': 'Runs',
  'auto.metrics.succeeded': 'Completed',
  'auto.metrics.failed': 'Failed',
  'auto.metrics.waiting': 'Waiting now',
  'auto.metrics.duration': 'Average duration',
  'auto.metrics.topFailure': 'Top failure reason',
  'auto.metrics.period': 'Last {days} days',
  'auto.seconds': '{n} s',
  'auto.minutes': '{n} min',

  'auto.builder.name': 'Workflow name',
  'auto.builder.when': 'WHEN',
  'auto.builder.if': 'IF',
  'auto.builder.then': 'THEN',
  'auto.builder.else': 'ELSE',
  'auto.builder.ifHint': 'Leave empty to run for every event.',
  'auto.builder.addStep': 'Add action',
  'auto.builder.addDelay': 'Add wait',
  'auto.builder.addWait': 'Wait for an event',
  'auto.builder.addBranch': 'Add branch',
  'auto.builder.addCondition': 'Add condition',
  'auto.builder.addGroup': 'Add group',
  'auto.builder.remove': 'Remove',
  'auto.builder.up': 'Move up',
  'auto.builder.down': 'Move down',
  'auto.builder.match.all': 'All of these',
  'auto.builder.match.any': 'Any of these',
  'auto.builder.group': 'Group',
  'auto.builder.save': 'Save draft',
  'auto.builder.saved': 'Draft saved. Publish to use it for new events.',
  'auto.builder.publish': 'Publish and switch on',
  'auto.builder.publishOff': 'Publish, keep off',
  'auto.builder.published': 'Published. New events use version {n}; runs already started finish on their own version.',
  'auto.builder.preview': 'Test without doing anything',
  'auto.builder.previewHint': 'Uses the latest order or customer (or the one you enter). Nothing is sent, booked or changed.',
  'auto.builder.sampleOrder': 'Order ID (optional)',
  'auto.builder.sampleCustomer': 'Customer ID (optional)',
  'auto.builder.testRun': 'Run for real on this order',
  'auto.builder.testConfirm': 'This really sends messages, books couriers and changes tags for this order. Continue?',
  'auto.builder.testStarted': 'Test run queued. Watch it in Run history.',
  'auto.builder.versions': 'Published versions',
  'auto.builder.minutes': 'Minutes',
  'auto.builder.hours': 'Hours',
  'auto.builder.days': 'Days',
  'auto.builder.at': 'At (shop time)',
  'auto.builder.dayOffset': 'Not before tomorrow',
  'auto.builder.timeout': 'Give up after (minutes)',
  'auto.builder.onTimeout': 'If it does not happen',
  'auto.builder.onTimeout.continue': 'Carry on with the next step',
  'auto.builder.onTimeout.stop': 'Stop the workflow',
  'auto.builder.value': 'Value',
  'auto.builder.select': 'Select',
  'auto.builder.followupStep': 'Follow-up step',

  'auto.delay.duration': 'Wait for a while',
  'auto.delay.until_time': 'Wait until a time of day',
  'auto.delay.followup_due': 'Wait until the follow-up is due',

  'auto.preview.title': 'What would happen',
  'auto.preview.entryMatched': 'Conditions match: the workflow would start.',
  'auto.preview.entryMissed': 'Conditions do not match: the workflow would not start.',
  'auto.preview.RUN': 'Would run',
  'auto.preview.SKIP': 'Would be skipped',
  'auto.preview.WAIT': 'Would wait',
  'auto.preview.WAIT_FOR': 'Would wait for the event',
  'auto.preview.THEN': 'Would take THEN',
  'auto.preview.ELSE': 'Would take ELSE',

  'auto.step.action': 'Action',
  'auto.step.delay': 'Wait',
  'auto.step.wait_event': 'Wait for event',
  'auto.step.branch': 'Branch',

  'auto.trigger.order.created': 'Order created',
  'auto.trigger.order.external_received': 'Website / store order received',
  'auto.trigger.order.confirmed': 'Order confirmed',
  'auto.trigger.order.cancelled': 'Order cancelled',
  'auto.trigger.order.status_changed': 'Order status changed',
  'auto.trigger.courier.booked': 'Courier booked',
  'auto.trigger.courier.status_changed': 'Courier status changed',
  'auto.trigger.order.delivered': 'Delivered',
  'auto.trigger.order.returned': 'Returned (RTO)',
  'auto.trigger.cod.settled': 'COD received',
  'auto.trigger.payout.overdue': 'COD payout overdue',
  'auto.trigger.reconciliation.issue': 'Reconciliation issue found',
  'auto.trigger.followup.due': 'Follow-ups due',
  'auto.trigger.inventory.low': 'Stock reached its low level',
  'auto.trigger.inventory.stockout_predicted': 'Item forecast to run out',
  'auto.cfg.useSuggested': 'Use the forecast’s suggested quantity when there is one',
  'auto.trigger.purchase_order.ordered': 'A purchase order was placed',
  'auto.trigger.purchase_order.partially_received': 'Part of a purchase order arrived',
  'auto.trigger.purchase_order.received': 'A purchase order fully arrived',
  'auto.trigger.purchase_order.overdue': 'A purchase order is late',
  'auto.trigger.supplier_payment.due': 'A supplier payment is overdue',
  'auto.trigger.transfer.completed': 'Stock moved between locations',
  'auto.trigger.integration.sync_failed': 'Store sync failed',
  'auto.trigger.customer.segment_entered': 'Customer entered a segment',
  'auto.trigger.customer.replied': 'Customer replied on WhatsApp',
  'auto.trigger.followup.completed': 'Follow-up completed',

  'auto.event.order.confirmed': 'Order confirmed',
  'auto.event.courier.booked': 'Courier booked',
  'auto.event.order.delivered': 'Delivered',
  'auto.event.customer.replied': 'Customer replied',
  'auto.event.followup.completed': 'Follow-up completed',

  'auto.action.SEND_TEMPLATE': 'Send order-update message',
  'auto.action.CREATE_FOLLOWUP': 'Create follow-up',
  'auto.action.ADD_TAG': 'Add CRM tag',
  'auto.action.REMOVE_TAG': 'Remove CRM tag',
  'auto.action.SELLER_NOTIFICATION': 'Notify my team',
  'auto.action.CREATE_TASK': 'Create task',
  'auto.action.BOOK_COURIER': 'Book courier',
  'auto.action.PUSH_STORE_STATUS': 'Update my website / store',
  'auto.action.RETRY_INTEGRATION_SYNC': 'Retry the failed sync once',
  'auto.action.SET_ORDER_LABEL': 'Label the order',
  'auto.action.TRIGGER_WEBHOOK': 'Send a webhook',
  'auto.action.CREATE_TEAM_TASK': 'Create a team task',
  'auto.action.CREATE_DRAFT_PO': 'Prepare a draft purchase order',
  'auto.cfg.quantity': 'Quantity to order',
  'auto.cfg.draftPoNote': 'Goes to the item’s preferred supplier as a DRAFT. Nothing is sent to the supplier; a person reviews and orders it.',
  'auto.cfg.assigneeOptional': 'Assign to (member id, optional)',
  'auto.action.WORKFLOW': 'Workflow',

  'auto.field.status': 'Order status',
  'auto.field.channel': 'Order source',
  'auto.field.cod_amount_paisa': 'COD amount (paisa)',
  'auto.field.payment_method': 'Payment method',
  'auto.field.courier': 'Courier',
  'auto.field.consignment_status': 'Parcel status',
  'auto.field.sku': 'Order has SKU',
  'auto.field.items_in_stock': 'All items in stock',
  'auto.field.external_source': 'Store the order came from',
  'auto.field.customer_tag': 'Customer tag',
  'auto.field.customer_segment': 'Customer segment',
  'auto.field.customer_flag': 'Customer mark',
  'auto.field.returned_parcels': 'Returned parcels (count)',
  'auto.field.transactional_consent': 'Agreed to order updates',
  'auto.field.marketing_consent': 'Agreed to offers',
  'auto.field.stock_on_hand': 'Stock on hand',
  'auto.field.integration_provider': 'Store platform',
  'auto.field.sync_error_code': 'Sync problem code',
  'auto.field.entered_segment': 'Segment entered',
  'auto.field.alert_kind': 'Alert',

  'auto.op.eq': 'is',
  'auto.op.ne': 'is not',
  'auto.op.in': 'is one of',
  'auto.op.not_in': 'is none of',
  'auto.op.gte': 'at least',
  'auto.op.lte': 'at most',
  'auto.op.has': 'has',
  'auto.op.not_has': 'does not have',
  'auto.op.is_true': 'yes',
  'auto.op.is_false': 'no',

  'auto.cfg.template': 'Order-update template',
  'auto.cfg.language': 'Message language',
  'auto.cfg.channel': 'Channel',
  'auto.cfg.text': 'Note',
  'auto.cfg.dueHours': 'Due after (hours)',
  'auto.cfg.assignee': 'Assign to (user ID, optional)',
  'auto.cfg.tag': 'CRM tag',
  'auto.cfg.titleEn': 'Title (English)',
  'auto.cfg.titleBn': 'Title (Bangla)',
  'auto.cfg.textEn': 'Text (English)',
  'auto.cfg.textBn': 'Text (Bangla)',
  'auto.cfg.audience': 'Who sees it',
  'auto.cfg.audience.OPERATIONS': 'Operations',
  'auto.cfg.audience.FINANCE': 'Finance',
  'auto.cfg.audience.INVENTORY': 'Inventory',
  'auto.cfg.provider': 'Courier',
  'auto.cfg.label': 'Label',
  'auto.cfg.bookingNote': 'Books only when the order has no parcel. If the courier does not answer, the run stops and booking recovery checks it; it is never booked twice.',
  'auto.cfg.messageNote': 'Order updates only. Consent, opt-out and channel are checked before every send; offers go through Campaigns.',
  'auto.cfg.storeNote': 'Uses the same store sync as Integrations; a push already queued is not repeated.',

  'auto.status.QUEUED': 'Queued',
  'auto.status.RUNNING': 'Running',
  'auto.status.WAITING': 'Waiting',
  'auto.status.SUCCEEDED': 'Completed',
  'auto.status.FAILED': 'Failed',
  'auto.status.CANCELLED': 'Cancelled',
  'auto.status.SKIPPED': 'Not started',
  'auto.status.TIMED_OUT': 'Timed out',
  'auto.status.IN_FLIGHT': 'Sent to courier',

  'auto.run.detail': 'Run details',
  'auto.run.retry': 'Retry from the failed step',
  'auto.run.cancel': 'Cancel run',
  'auto.run.retryable': 'Can be retried',
  'auto.run.notRetryable': 'Needs a fix first',
  'auto.run.steps': 'Steps',
  'auto.run.history': 'History',
  'auto.run.order': 'Order',
  'auto.run.version': 'Version',
  'auto.run.depth': 'Chain depth',
  'auto.run.test': 'Test run',
  'auto.run.waitingFor': 'Waiting for: {event}',
  'auto.run.nextAt': 'Next: {when}',
  'auto.run.more': 'Load more',
  'auto.run.noFailures': 'No failed runs. Nice.',
  'auto.run.none': 'No runs yet',

  'auto.recipe.install': 'Use this recipe',
  'auto.recipe.installed': 'In use',
  'auto.recipe.provider': 'Courier to book with',
  'auto.recipe.channel': 'Message channel',
  'auto.recipe.done': 'Added and switched on. You can edit it any time.',
  'auto.recipe.draft': 'Added as a draft: {reason}',

  'auto.reason.CONDITIONS_NOT_MET': 'Conditions did not match',
  'auto.reason.WORKFLOW_DISABLED': 'Workflow was switched off',
  'auto.reason.RULE_OWNER_PERMISSION_REVOKED': 'The person who published it can no longer manage automation',
  'auto.reason.LOOP_DETECTED': 'Stopped: this would start the same workflow again (a loop)',
  'auto.reason.DEPTH_LIMIT': 'Stopped: too many workflows triggering each other',
  'auto.reason.REPEAT_LIMIT': 'Stopped: ran too often for the same item today',
  'auto.reason.CONSENT_REQUIRED': 'Customer has not agreed to messages',
  'auto.reason.UNDELIVERABLE': 'Customer address cannot receive messages',
  'auto.reason.CHANNEL_DISABLED': 'Messaging channel is not set up',
  'auto.reason.FREQUENCY_LIMIT': 'Daily message limit for this customer reached',
  'auto.reason.BOOKING_UNKNOWN': 'Courier did not confirm; booking recovery is checking. Never re-booked automatically.',
  'auto.reason.BOOKING_FAILED': 'The courier refused the booking',
  'auto.reason.BOOKING_PERMISSION_REQUIRED': 'The publisher cannot book couriers',
  'auto.reason.ALREADY_BOOKED': 'Already booked; not booked again',
  'auto.reason.COURIER_NOT_CONNECTED': 'Connect this courier first',
  'auto.reason.NO_CONNECTED_STORE': 'Order is not from a connected store',
  'auto.reason.NOTHING_TO_PUSH': 'Nothing to update on the store yet',
  'auto.reason.RETRY_LIMIT_REACHED': 'Already retried enough times',
  'auto.reason.CANCELLED_BY_SELLER': 'Cancelled by a team member',
  'auto.reason.NO_CUSTOMER': 'Order has no customer',
  'auto.reason.TAG_NOT_FOUND': 'Tag no longer exists',
  'auto.reason.TEMPLATE_NOT_TRANSACTIONAL': 'Choose an order-update template for this channel',
  'auto.reason.PROVIDER_REQUIRED': 'Choose a courier',
  'auto.reason.NOT_RETRYABLE': 'This failure cannot be retried',
  'auto.reason.CONFIRMATION_REQUIRED': 'Confirm the real test run first',
  'auto.reason.NO_SAMPLE': 'No order or customer to test with',
  'auto.reason.TRANSIENT': 'Temporary problem; retried automatically',
  'auto.reason.INVALID_CONFIG': 'A step is not filled in correctly',
  'auto.reason.DUPLICATE_STEP_ID': 'Two steps have the same ID',
  'auto.reason.NO_ACTION': 'Add at least one action',
  'auto.reason.ACTION_NOT_AVAILABLE': 'This action does not fit this trigger',
  'auto.reason.CONDITION_NOT_AVAILABLE': 'This condition does not fit this trigger',
  'auto.reason.WAIT_NOT_AVAILABLE': 'This wait does not fit this trigger',
  'auto.reason.INVALID_VALUE': 'A condition has an invalid value',
  'auto.reason.FOLLOWUP_STEP_NOT_BEFORE_DELAY': 'The follow-up must be created before this wait',
  'auto.reason.ONE_TASK_PER_WORKFLOW': 'Only one task step per workflow',
  'auto.reason.ONE_BOOKING_PER_WORKFLOW': 'Only one courier booking per workflow',
  'auto.reason.TOO_MANY_STEPS': 'Too many steps (30 at most)',
  'auto.reason.TOO_DEEPLY_NESTED': 'Branches are nested too deeply',
  'auto.reason.NOT_PUBLISHED': 'Publish the workflow first',
} as const;

export const automationBn: Record<keyof typeof automationEn, string> = {
  'auto.title': 'অটোমেশন',
  'auto.subtitle': 'কিছু ঘটলে যাচাই করুন, তারপর কাজ, অপেক্ষা বা শাখা। শুধু নিরাপদ ধাপ।',
  'auto.tab.workflows': 'ওয়ার্কফ্লো',
  'auto.tab.recipes': 'তৈরি রেসিপি',
  'auto.tab.runs': 'চালানোর ইতিহাস',
  'auto.tab.failures': 'ব্যর্থ',
  'auto.tab.tasks': 'কাজ',
  'auto.new': 'নতুন ওয়ার্কফ্লো',
  'auto.back': 'সব ওয়ার্কফ্লো',
  'auto.readOnly': 'আপনি ওয়ার্কফ্লো দেখতে পারবেন। মালিক বা ম্যানেজার তৈরি ও চালু করেন।',
  'auto.empty': 'এখনো কোনো ওয়ার্কফ্লো নেই',
  'auto.emptyHint': 'তৈরি রেসিপি দিয়ে শুরু করুন, অথবা নিজে বানান।',
  'auto.enabled': 'চালু',
  'auto.disabled': 'বন্ধ',
  'auto.enable': 'চালু করুন',
  'auto.disable': 'বন্ধ করুন',
  'auto.edit': 'সম্পাদনা',
  'auto.version': 'সংস্করণ {n}',
  'auto.unpublished': 'প্রকাশ না করা পরিবর্তন আছে',
  'auto.notPublished': 'এখনো প্রকাশ হয়নি',
  'auto.runs7d': 'গত ৭ দিন: {ok}টি সম্পন্ন, {failed}টি ব্যর্থ, {waiting}টি অপেক্ষায়',
  'auto.col.workflow': 'ওয়ার্কফ্লো',
  'auto.col.trigger': 'কখন',
  'auto.col.status': 'অবস্থা',
  'auto.col.step': 'ধাপ',
  'auto.col.when': 'সময়',
  'auto.col.reason': 'কারণ',

  'auto.metrics.runs': 'মোট চালানো',
  'auto.metrics.succeeded': 'সম্পন্ন',
  'auto.metrics.failed': 'ব্যর্থ',
  'auto.metrics.waiting': 'এখন অপেক্ষায়',
  'auto.metrics.duration': 'গড় সময়',
  'auto.metrics.topFailure': 'সবচেয়ে বেশি ব্যর্থতার কারণ',
  'auto.metrics.period': 'গত {days} দিন',
  'auto.seconds': '{n} সেকেন্ড',
  'auto.minutes': '{n} মিনিট',

  'auto.builder.name': 'ওয়ার্কফ্লোর নাম',
  'auto.builder.when': 'যখন',
  'auto.builder.if': 'যদি',
  'auto.builder.then': 'তাহলে',
  'auto.builder.else': 'নাহলে',
  'auto.builder.ifHint': 'খালি রাখলে প্রতিটি ঘটনায় চলবে।',
  'auto.builder.addStep': 'কাজ যোগ করুন',
  'auto.builder.addDelay': 'অপেক্ষা যোগ করুন',
  'auto.builder.addWait': 'ঘটনার জন্য অপেক্ষা',
  'auto.builder.addBranch': 'শাখা যোগ করুন',
  'auto.builder.addCondition': 'শর্ত যোগ করুন',
  'auto.builder.addGroup': 'গ্রুপ যোগ করুন',
  'auto.builder.remove': 'সরান',
  'auto.builder.up': 'উপরে নিন',
  'auto.builder.down': 'নিচে নিন',
  'auto.builder.match.all': 'সবগুলো মিলতে হবে',
  'auto.builder.match.any': 'যেকোনো একটি মিললেই',
  'auto.builder.group': 'গ্রুপ',
  'auto.builder.save': 'খসড়া সংরক্ষণ',
  'auto.builder.saved': 'খসড়া সংরক্ষিত। নতুন ঘটনায় ব্যবহার করতে প্রকাশ করুন।',
  'auto.builder.publish': 'প্রকাশ করে চালু করুন',
  'auto.builder.publishOff': 'প্রকাশ করুন, বন্ধ রাখুন',
  'auto.builder.published': 'প্রকাশিত। নতুন ঘটনায় সংস্করণ {n} চলবে; আগে শুরু হওয়াগুলো নিজের সংস্করণেই শেষ হবে।',
  'auto.builder.preview': 'কিছু না করে পরীক্ষা করুন',
  'auto.builder.previewHint': 'সর্বশেষ অর্ডার বা গ্রাহক (বা আপনার দেওয়া আইডি) দিয়ে। কিছু পাঠানো, বুক বা পরিবর্তন হবে না।',
  'auto.builder.sampleOrder': 'অর্ডার আইডি (ঐচ্ছিক)',
  'auto.builder.sampleCustomer': 'গ্রাহক আইডি (ঐচ্ছিক)',
  'auto.builder.testRun': 'এই অর্ডারে সত্যি চালান',
  'auto.builder.testConfirm': 'এতে সত্যিই এই অর্ডারের জন্য মেসেজ যাবে, কুরিয়ার বুক হবে ও ট্যাগ বদলাবে। চালিয়ে যাবেন?',
  'auto.builder.testStarted': 'পরীক্ষামূলক চালানো সারিতে আছে। চালানোর ইতিহাসে দেখুন।',
  'auto.builder.versions': 'প্রকাশিত সংস্করণ',
  'auto.builder.minutes': 'মিনিট',
  'auto.builder.hours': 'ঘণ্টা',
  'auto.builder.days': 'দিন',
  'auto.builder.at': 'সময় (দোকানের সময়)',
  'auto.builder.dayOffset': 'আগামীকালের আগে নয়',
  'auto.builder.timeout': 'কত মিনিট পর হাল ছাড়বে',
  'auto.builder.onTimeout': 'না ঘটলে',
  'auto.builder.onTimeout.continue': 'পরের ধাপে যান',
  'auto.builder.onTimeout.stop': 'ওয়ার্কফ্লো থামান',
  'auto.builder.value': 'মান',
  'auto.builder.select': 'বাছুন',
  'auto.builder.followupStep': 'ফলো-আপ ধাপ',

  'auto.delay.duration': 'কিছুক্ষণ অপেক্ষা',
  'auto.delay.until_time': 'নির্দিষ্ট সময় পর্যন্ত অপেক্ষা',
  'auto.delay.followup_due': 'ফলো-আপের সময় পর্যন্ত অপেক্ষা',

  'auto.preview.title': 'কী ঘটবে',
  'auto.preview.entryMatched': 'শর্ত মিলেছে: ওয়ার্কফ্লো শুরু হবে।',
  'auto.preview.entryMissed': 'শর্ত মেলেনি: ওয়ার্কফ্লো শুরু হবে না।',
  'auto.preview.RUN': 'চলবে',
  'auto.preview.SKIP': 'বাদ যাবে',
  'auto.preview.WAIT': 'অপেক্ষা করবে',
  'auto.preview.WAIT_FOR': 'ঘটনার অপেক্ষা করবে',
  'auto.preview.THEN': '"তাহলে" পথে যাবে',
  'auto.preview.ELSE': '"নাহলে" পথে যাবে',

  'auto.step.action': 'কাজ',
  'auto.step.delay': 'অপেক্ষা',
  'auto.step.wait_event': 'ঘটনার অপেক্ষা',
  'auto.step.branch': 'শাখা',

  'auto.trigger.order.created': 'অর্ডার তৈরি হলে',
  'auto.trigger.order.external_received': 'ওয়েবসাইট / স্টোরের অর্ডার এলে',
  'auto.trigger.order.confirmed': 'অর্ডার নিশ্চিত হলে',
  'auto.trigger.order.cancelled': 'অর্ডার বাতিল হলে',
  'auto.trigger.order.status_changed': 'অর্ডারের অবস্থা বদলালে',
  'auto.trigger.courier.booked': 'কুরিয়ার বুক হলে',
  'auto.trigger.courier.status_changed': 'কুরিয়ারের অবস্থা বদলালে',
  'auto.trigger.order.delivered': 'ডেলিভারি হলে',
  'auto.trigger.order.returned': 'ফেরত এলে (RTO)',
  'auto.trigger.cod.settled': 'COD টাকা পেলে',
  'auto.trigger.payout.overdue': 'COD পেমেন্ট দেরি হলে',
  'auto.trigger.reconciliation.issue': 'হিসাব মেলানোয় সমস্যা পেলে',
  'auto.trigger.followup.due': 'ফলো-আপের সময় হলে',
  'auto.trigger.inventory.low': 'স্টক কম সীমায় পৌঁছালে',
  'auto.trigger.inventory.stockout_predicted': 'পণ্য ফুরিয়ে যাওয়ার পূর্বাভাস হলে',
  'auto.cfg.useSuggested': 'পূর্বাভাসে পরামর্শ দেওয়া সংখ্যা থাকলে সেটাই নিন',
  'auto.trigger.purchase_order.ordered': 'ক্রয় আদেশ দেওয়া হলে',
  'auto.trigger.purchase_order.partially_received': 'ক্রয় আদেশের কিছু মাল এলে',
  'auto.trigger.purchase_order.received': 'ক্রয় আদেশের সব মাল এলে',
  'auto.trigger.purchase_order.overdue': 'ক্রয় আদেশের মাল দেরি হলে',
  'auto.trigger.supplier_payment.due': 'সরবরাহকারীর পরিশোধ বকেয়া হলে',
  'auto.trigger.transfer.completed': 'এক জায়গা থেকে অন্য জায়গায় স্টক সরালে',
  'auto.trigger.integration.sync_failed': 'স্টোর সিঙ্ক ব্যর্থ হলে',
  'auto.trigger.customer.segment_entered': 'গ্রাহক কোনো সেগমেন্টে ঢুকলে',
  'auto.trigger.customer.replied': 'গ্রাহক WhatsApp-এ উত্তর দিলে',
  'auto.trigger.followup.completed': 'ফলো-আপ সম্পন্ন হলে',

  'auto.event.order.confirmed': 'অর্ডার নিশ্চিত',
  'auto.event.courier.booked': 'কুরিয়ার বুক',
  'auto.event.order.delivered': 'ডেলিভারি',
  'auto.event.customer.replied': 'গ্রাহকের উত্তর',
  'auto.event.followup.completed': 'ফলো-আপ সম্পন্ন',

  'auto.action.SEND_TEMPLATE': 'অর্ডার আপডেট মেসেজ পাঠান',
  'auto.action.CREATE_FOLLOWUP': 'ফলো-আপ তৈরি',
  'auto.action.ADD_TAG': 'CRM ট্যাগ যোগ',
  'auto.action.REMOVE_TAG': 'CRM ট্যাগ সরান',
  'auto.action.SELLER_NOTIFICATION': 'টিমকে জানান',
  'auto.action.CREATE_TASK': 'কাজ তৈরি',
  'auto.action.BOOK_COURIER': 'কুরিয়ার বুক করুন',
  'auto.action.PUSH_STORE_STATUS': 'ওয়েবসাইট / স্টোর আপডেট',
  'auto.action.RETRY_INTEGRATION_SYNC': 'ব্যর্থ সিঙ্ক একবার আবার চেষ্টা',
  'auto.action.SET_ORDER_LABEL': 'অর্ডারে লেবেল দিন',
  'auto.action.TRIGGER_WEBHOOK': 'ওয়েবহুক পাঠান',
  'auto.action.CREATE_TEAM_TASK': 'টিমের জন্য কাজ তৈরি',
  'auto.action.CREATE_DRAFT_PO': 'খসড়া ক্রয় আদেশ তৈরি',
  'auto.cfg.quantity': 'কত পিস অর্ডার করবেন',
  'auto.cfg.draftPoNote': 'পছন্দের সরবরাহকারীর নামে খসড়া হিসেবে তৈরি হবে। সরবরাহকারীকে কিছু পাঠানো হয় না; একজন দেখে তারপর অর্ডার দেবেন।',
  'auto.cfg.assigneeOptional': 'কাকে দেবেন (সদস্যের আইডি, ঐচ্ছিক)',
  'auto.action.WORKFLOW': 'ওয়ার্কফ্লো',

  'auto.field.status': 'অর্ডারের অবস্থা',
  'auto.field.channel': 'অর্ডারের উৎস',
  'auto.field.cod_amount_paisa': 'COD পরিমাণ (পয়সা)',
  'auto.field.payment_method': 'পেমেন্টের ধরন',
  'auto.field.courier': 'কুরিয়ার',
  'auto.field.consignment_status': 'পার্সেলের অবস্থা',
  'auto.field.sku': 'অর্ডারে SKU আছে',
  'auto.field.items_in_stock': 'সব পণ্য স্টকে আছে',
  'auto.field.external_source': 'কোন স্টোর থেকে অর্ডার',
  'auto.field.customer_tag': 'গ্রাহকের ট্যাগ',
  'auto.field.customer_segment': 'গ্রাহকের সেগমেন্ট',
  'auto.field.customer_flag': 'গ্রাহকের চিহ্ন',
  'auto.field.returned_parcels': 'ফেরত পার্সেল (সংখ্যা)',
  'auto.field.transactional_consent': 'অর্ডার আপডেটে সম্মতি',
  'auto.field.marketing_consent': 'অফারে সম্মতি',
  'auto.field.stock_on_hand': 'হাতে স্টক',
  'auto.field.integration_provider': 'স্টোর প্ল্যাটফর্ম',
  'auto.field.sync_error_code': 'সিঙ্ক সমস্যার কোড',
  'auto.field.entered_segment': 'যে সেগমেন্টে ঢুকেছে',
  'auto.field.alert_kind': 'সতর্কবার্তা',

  'auto.op.eq': 'হলো',
  'auto.op.ne': 'নয়',
  'auto.op.in': 'এগুলোর একটি',
  'auto.op.not_in': 'এগুলোর কোনোটি নয়',
  'auto.op.gte': 'কমপক্ষে',
  'auto.op.lte': 'সর্বোচ্চ',
  'auto.op.has': 'আছে',
  'auto.op.not_has': 'নেই',
  'auto.op.is_true': 'হ্যাঁ',
  'auto.op.is_false': 'না',

  'auto.cfg.template': 'অর্ডার আপডেট টেমপ্লেট',
  'auto.cfg.language': 'মেসেজের ভাষা',
  'auto.cfg.channel': 'মাধ্যম',
  'auto.cfg.text': 'নোট',
  'auto.cfg.dueHours': 'কত ঘণ্টা পরে (সময়সীমা)',
  'auto.cfg.assignee': 'কাকে দেবেন (ইউজার আইডি, ঐচ্ছিক)',
  'auto.cfg.tag': 'CRM ট্যাগ',
  'auto.cfg.titleEn': 'শিরোনাম (ইংরেজি)',
  'auto.cfg.titleBn': 'শিরোনাম (বাংলা)',
  'auto.cfg.textEn': 'লেখা (ইংরেজি)',
  'auto.cfg.textBn': 'লেখা (বাংলা)',
  'auto.cfg.audience': 'কে দেখবে',
  'auto.cfg.audience.OPERATIONS': 'অপারেশন',
  'auto.cfg.audience.FINANCE': 'হিসাব',
  'auto.cfg.audience.INVENTORY': 'স্টক',
  'auto.cfg.provider': 'কুরিয়ার',
  'auto.cfg.label': 'লেবেল',
  'auto.cfg.bookingNote': 'অর্ডারে কোনো পার্সেল না থাকলেই বুক করবে। কুরিয়ার উত্তর না দিলে থেমে যাবে এবং বুকিং রিকভারি যাচাই করবে; কখনো দুবার বুক হবে না।',
  'auto.cfg.messageNote': 'শুধু অর্ডার আপডেট। প্রতিবার পাঠানোর আগে সম্মতি, অপ্ট-আউট ও মাধ্যম যাচাই হয়; অফার পাঠান ক্যাম্পেইন থেকে।',
  'auto.cfg.storeNote': 'ইন্টিগ্রেশনের একই স্টোর সিঙ্ক ব্যবহার করে; আগে থেকে সারিতে থাকা আপডেট আবার যায় না।',

  'auto.status.QUEUED': 'সারিতে',
  'auto.status.RUNNING': 'চলছে',
  'auto.status.WAITING': 'অপেক্ষায়',
  'auto.status.SUCCEEDED': 'সম্পন্ন',
  'auto.status.FAILED': 'ব্যর্থ',
  'auto.status.CANCELLED': 'বাতিল',
  'auto.status.SKIPPED': 'শুরু হয়নি',
  'auto.status.TIMED_OUT': 'সময় শেষ',
  'auto.status.IN_FLIGHT': 'কুরিয়ারে পাঠানো',

  'auto.run.detail': 'চালানোর বিস্তারিত',
  'auto.run.retry': 'ব্যর্থ ধাপ থেকে আবার চেষ্টা',
  'auto.run.cancel': 'চালানো বাতিল',
  'auto.run.retryable': 'আবার চেষ্টা করা যাবে',
  'auto.run.notRetryable': 'আগে ঠিক করতে হবে',
  'auto.run.steps': 'ধাপগুলো',
  'auto.run.history': 'ইতিহাস',
  'auto.run.order': 'অর্ডার',
  'auto.run.version': 'সংস্করণ',
  'auto.run.depth': 'চেইনের গভীরতা',
  'auto.run.test': 'পরীক্ষামূলক',
  'auto.run.waitingFor': 'অপেক্ষা: {event}',
  'auto.run.nextAt': 'পরবর্তী: {when}',
  'auto.run.more': 'আরও দেখুন',
  'auto.run.noFailures': 'কোনো ব্যর্থ চালানো নেই।',
  'auto.run.none': 'এখনো কোনো চালানো নেই',

  'auto.recipe.install': 'এই রেসিপি ব্যবহার করুন',
  'auto.recipe.installed': 'ব্যবহার হচ্ছে',
  'auto.recipe.provider': 'কোন কুরিয়ারে বুক হবে',
  'auto.recipe.channel': 'মেসেজের মাধ্যম',
  'auto.recipe.done': 'যোগ হয়েছে ও চালু। যেকোনো সময় সম্পাদনা করতে পারবেন।',
  'auto.recipe.draft': 'খসড়া হিসেবে যোগ হয়েছে: {reason}',

  'auto.reason.CONDITIONS_NOT_MET': 'শর্ত মেলেনি',
  'auto.reason.WORKFLOW_DISABLED': 'ওয়ার্কফ্লো বন্ধ করা হয়েছে',
  'auto.reason.RULE_OWNER_PERMISSION_REVOKED': 'যিনি প্রকাশ করেছেন তিনি আর অটোমেশন পরিচালনা করতে পারেন না',
  'auto.reason.LOOP_DETECTED': 'থামানো হয়েছে: একই ওয়ার্কফ্লো আবার শুরু হতো (লুপ)',
  'auto.reason.DEPTH_LIMIT': 'থামানো হয়েছে: অনেক ওয়ার্কফ্লো একে অপরকে চালাচ্ছিল',
  'auto.reason.REPEAT_LIMIT': 'থামানো হয়েছে: আজ একই জিনিসের জন্য অনেকবার চলেছে',
  'auto.reason.CONSENT_REQUIRED': 'গ্রাহক মেসেজে সম্মতি দেননি',
  'auto.reason.UNDELIVERABLE': 'গ্রাহকের ঠিকানায় মেসেজ যায় না',
  'auto.reason.CHANNEL_DISABLED': 'মেসেজিং মাধ্যম সেট করা নেই',
  'auto.reason.FREQUENCY_LIMIT': 'এই গ্রাহকের দৈনিক মেসেজ সীমা পূর্ণ',
  'auto.reason.BOOKING_UNKNOWN': 'কুরিয়ার নিশ্চিত করেনি; বুকিং রিকভারি যাচাই করছে। নিজে থেকে আবার বুক হবে না।',
  'auto.reason.BOOKING_FAILED': 'কুরিয়ার বুকিং গ্রহণ করেনি',
  'auto.reason.BOOKING_PERMISSION_REQUIRED': 'প্রকাশকারী কুরিয়ার বুক করতে পারেন না',
  'auto.reason.ALREADY_BOOKED': 'আগেই বুক করা; আবার বুক হয়নি',
  'auto.reason.COURIER_NOT_CONNECTED': 'আগে এই কুরিয়ার যুক্ত করুন',
  'auto.reason.NO_CONNECTED_STORE': 'অর্ডারটি যুক্ত স্টোর থেকে আসেনি',
  'auto.reason.NOTHING_TO_PUSH': 'স্টোরে এখনো আপডেট করার কিছু নেই',
  'auto.reason.RETRY_LIMIT_REACHED': 'যথেষ্টবার আবার চেষ্টা করা হয়েছে',
  'auto.reason.CANCELLED_BY_SELLER': 'টিমের একজন বাতিল করেছেন',
  'auto.reason.NO_CUSTOMER': 'অর্ডারে গ্রাহক নেই',
  'auto.reason.TAG_NOT_FOUND': 'ট্যাগটি আর নেই',
  'auto.reason.TEMPLATE_NOT_TRANSACTIONAL': 'এই মাধ্যমের জন্য অর্ডার আপডেট টেমপ্লেট বাছুন',
  'auto.reason.PROVIDER_REQUIRED': 'কুরিয়ার বাছুন',
  'auto.reason.NOT_RETRYABLE': 'এই ব্যর্থতা আবার চেষ্টা করা যাবে না',
  'auto.reason.CONFIRMATION_REQUIRED': 'আগে সত্যি চালানো নিশ্চিত করুন',
  'auto.reason.NO_SAMPLE': 'পরীক্ষার জন্য কোনো অর্ডার বা গ্রাহক নেই',
  'auto.reason.TRANSIENT': 'সাময়িক সমস্যা; নিজে থেকে আবার চেষ্টা হচ্ছে',
  'auto.reason.INVALID_CONFIG': 'একটি ধাপ ঠিকভাবে পূরণ হয়নি',
  'auto.reason.DUPLICATE_STEP_ID': 'দুটি ধাপের আইডি একই',
  'auto.reason.NO_ACTION': 'অন্তত একটি কাজ যোগ করুন',
  'auto.reason.ACTION_NOT_AVAILABLE': 'এই কাজ এই ট্রিগারের সাথে মেলে না',
  'auto.reason.CONDITION_NOT_AVAILABLE': 'এই শর্ত এই ট্রিগারের সাথে মেলে না',
  'auto.reason.WAIT_NOT_AVAILABLE': 'এই অপেক্ষা এই ট্রিগারের সাথে মেলে না',
  'auto.reason.INVALID_VALUE': 'একটি শর্তের মান ঠিক নয়',
  'auto.reason.FOLLOWUP_STEP_NOT_BEFORE_DELAY': 'এই অপেক্ষার আগে ফলো-আপ তৈরি হতে হবে',
  'auto.reason.ONE_TASK_PER_WORKFLOW': 'এক ওয়ার্কফ্লোতে একটিই কাজ-ধাপ',
  'auto.reason.ONE_BOOKING_PER_WORKFLOW': 'এক ওয়ার্কফ্লোতে একটিই কুরিয়ার বুকিং',
  'auto.reason.TOO_MANY_STEPS': 'অনেক বেশি ধাপ (সর্বোচ্চ ৩০)',
  'auto.reason.TOO_DEEPLY_NESTED': 'শাখার ভেতরে শাখা খুব বেশি',
  'auto.reason.NOT_PUBLISHED': 'আগে ওয়ার্কফ্লো প্রকাশ করুন',
};
