/**
 * Messaging & campaigns copy (V3.3). Channel and provider names (WhatsApp,
 * Email, Meta) stay English in Bangla, the way sellers say them.
 */
export const campaignsEn = {
  'nav.campaigns': 'Campaigns',
  'cmp.title': 'Campaigns',
  'cmp.subtitle': 'Offers to customers who agreed to receive them. Order updates stay in Messaging.',
  'cmp.new': 'New campaign',
  'cmp.newFlow': 'New flow',
  'cmp.edit': 'Edit',
  'cmp.back': 'All campaigns',
  'cmp.oneOffs': 'Campaigns',
  'cmp.flows': 'Automatic flows',
  'cmp.flowsHint': 'Run every day and message each customer once per lapse.',
  'cmp.empty': 'No campaigns yet',
  'cmp.emptyHint': 'Record marketing consent on customers first, then build a campaign.',
  'cmp.readOnly': 'You can watch campaigns. The shop owner builds and launches them.',
  'cmp.col.name': 'Name',
  'cmp.col.channel': 'Channel',
  'cmp.col.status': 'Status',
  'cmp.col.recipients': 'Recipients',
  'cmp.col.sent': 'Sent',
  'cmp.col.when': 'When',
  'cmp.kind.ONE_OFF': 'One-off',
  'cmp.kind.FLOW': 'Flow',
  'cmp.status.DRAFT': 'Draft',
  'cmp.status.SCHEDULED': 'Scheduled',
  'cmp.status.SENDING': 'Sending',
  'cmp.status.PAUSED': 'Paused',
  'cmp.status.COMPLETED': 'Completed',
  'cmp.status.CANCELLED': 'Cancelled',
  'cmp.status.ACTIVE': 'Active',
  'cmp.flow.WIN_BACK': 'Win back past buyers',
  'cmp.flow.REPEAT_NUDGE': 'Repeat purchase reminder',
  'cmp.flow.INACTIVE': 'Inactive customers',
  'cmp.flowAbout.WIN_BACK': 'Customers who once received a parcel and have not ordered for {days} days.',
  'cmp.flowAbout.REPEAT_NUDGE': 'Customers whose last order was delivered about {days} days ago.',
  'cmp.flowAbout.INACTIVE': 'Customers with no order in {days} days (the CRM "Inactive" definition).',
  'cmp.channel.EMAIL': 'Email',
  'cmp.channel.WHATSAPP': 'WhatsApp',
  'cmp.b.name': 'Campaign name',
  'cmp.b.kind': 'Type',
  'cmp.b.flow': 'Flow',
  'cmp.b.flowDays': 'After how many days',
  'cmp.b.channel': 'Channel',
  'cmp.b.template': 'Marketing template',
  'cmp.b.noTemplates': 'No marketing template for this channel yet. Create one in Messaging.',
  'cmp.b.language': 'Message language',
  'cmp.b.audience': 'Who receives it',
  'cmp.b.segment': 'CRM segment',
  'cmp.b.anySegment': 'All customers',
  'cmp.b.tag': 'CRM tag',
  'cmp.b.anyTag': 'Any tag',
  'cmp.b.minOrders': 'At least orders',
  'cmp.b.maxOrders': 'At most orders',
  'cmp.b.lastBefore': 'Last order more than … days ago',
  'cmp.b.lastWithin': 'Last order within … days',
  'cmp.b.pace': 'Sending pace',
  'cmp.b.rate': 'Messages per minute',
  'cmp.b.cap': 'At most one offer per customer every … hours',
  'cmp.b.attribution': 'Count orders placed within … days',
  'cmp.b.estimate': 'Check audience',
  'cmp.b.save': 'Save draft',
  'cmp.b.saved': 'Draft saved',
  'cmp.b.preview': 'Preview',
  'cmp.b.tagHint': 'Automation rules can add or remove CRM tags on order events. Target a tag to reach those customers.',
  'cmp.est.matched': 'Match the audience',
  'cmp.est.reachable': 'Can receive this campaign',
  'cmp.est.overLimit': 'Only the first {limit} customers are included.',
  'cmp.skip.NO_CONTACT': 'No address on this channel',
  'cmp.skip.NO_MARKETING_CONSENT': 'No marketing consent',
  'cmp.skip.OPTED_OUT': 'Opted out',
  'cmp.skip.UNDELIVERABLE': 'Address cannot receive',
  'cmp.skip.FREQUENCY_CAP': 'Received an offer recently',
  'cmp.skip.CUSTOMER_BLOCKED': 'Customer blocked or deleted',
  'cmp.skip.CANCELLED': 'Campaign cancelled',
  'cmp.rules':
    'Always on: marketing is never sent between {start}:00 and {end}:00, consent is checked again at the moment of sending, and every email carries a one-click unsubscribe.',
  'cmp.launch': 'Send now',
  'cmp.schedule': 'Schedule',
  'cmp.scheduleAt': 'Send at',
  'cmp.activate': 'Turn flow on',
  'cmp.pause': 'Pause',
  'cmp.resume': 'Resume',
  'cmp.cancel': 'Cancel campaign',
  'cmp.cancelConfirm': 'Cancel this campaign? Messages not yet sent will not be sent.',
  'cmp.launchConfirm': 'Send this campaign to {count} customers now?',
  'cmp.blocked': 'Cannot send yet',
  'cmp.a.title': 'Results',
  'cmp.a.recipients': 'Recipients',
  'cmp.a.sent': 'Sent',
  'cmp.a.delivered': 'Delivered',
  'cmp.a.read': 'Read / opened',
  'cmp.a.failed': 'Failed',
  'cmp.a.optOuts': 'Unsubscribed',
  'cmp.a.notReported': 'Not reported by this provider',
  'cmp.a.skipped': 'Not sent to',
  'cmp.a.errors': 'Failure reasons',
  'cmp.a.ordersAfter': 'Orders within {days} days after the message',
  'cmp.a.ordersAfterHint': 'Counted, not claimed: these customers ordered after receiving it; the message may not be why.',
  'cmp.a.buyers': 'Customers who ordered',
  'cmp.a.orders': 'Orders',
  'cmp.a.value': 'Order value',
  'cmp.a.pending': 'Waiting to send',
  'cmp.r.title': 'Recipients',
  'cmp.r.status.PENDING': 'Waiting',
  'cmp.r.status.QUEUED': 'Queued',
  'cmp.r.status.SKIPPED': 'Skipped',
  'cmp.m.QUEUED': 'Queued',
  'cmp.m.SENDING': 'Sending',
  'cmp.m.RETRY': 'Retrying',
  'cmp.m.SENT': 'Sent',
  'cmp.m.DELIVERED': 'Delivered',
  'cmp.m.READ': 'Read',
  'cmp.m.FAILED': 'Failed',
  'cmp.m.SUPPRESSED': 'Stopped (consent)',
  'cmp.m.UNKNOWN': 'Unknown — check before resending',
  'cmp.m.CANCELLED': 'Cancelled',
  'cmp.blocker.CHANNEL_DISABLED': 'Turn this channel on in Messaging.',
  'cmp.blocker.WHATSAPP_CONNECTION_REQUIRED': 'Link your WhatsApp Business number in Integrations.',
  'cmp.blocker.META_APP_SETUP_REQUIRED': 'WhatsApp is not set up on this ecomsbd deployment yet.',
  'cmp.blocker.EMAIL_OFFICIAL_PROVIDER_REQUIRED': 'Email sending is not set up on this deployment yet.',
  'cmp.blocker.WHATSAPP_TEMPLATE_NOT_APPROVED': 'Meta has not approved this template yet. Check approvals in Integrations.',
  'cmp.blocker.WHATSAPP_TEMPLATE_LANGUAGE': 'This template has no approved language for the chosen one.',
  'cmp.blocker.TEMPLATE_ARCHIVED': 'The template was archived.',
  'cmp.blocker.TEMPLATE_NOT_FOUND': 'The template no longer exists.',
  'cmp.blocker.TEMPLATE_PURPOSE_MISMATCH': 'Choose a marketing template.',
  'cmp.blocker.TEMPLATE_CHANNEL_MISMATCH': 'The template is for a different channel.',
  'cmp.monitor.title': 'Last 30 days',
  'cmp.monitor.contacts': 'Customers who accept offers',
  'cmp.monitor.optOuts': 'Opt-outs',
  'cmp.monitor.marketing': 'Offers sent',
  'cmp.monitor.transactional': 'Order updates sent',
} as const;

export const campaignsBn: Record<keyof typeof campaignsEn, string> = {
  'nav.campaigns': 'ক্যাম্পেইন',
  'cmp.title': 'ক্যাম্পেইন',
  'cmp.subtitle': 'যে গ্রাহকেরা অফার পেতে রাজি, শুধু তাঁদের জন্য। অর্ডারের আপডেট মেসেজিং-এ থাকে।',
  'cmp.new': 'নতুন ক্যাম্পেইন',
  'cmp.newFlow': 'নতুন ফ্লো',
  'cmp.edit': 'সম্পাদনা',
  'cmp.back': 'সব ক্যাম্পেইন',
  'cmp.oneOffs': 'ক্যাম্পেইন',
  'cmp.flows': 'স্বয়ংক্রিয় ফ্লো',
  'cmp.flowsHint': 'প্রতিদিন চলে; প্রতিবার অর্ডার বন্ধ হলে একজন গ্রাহক একবারই মেসেজ পান।',
  'cmp.empty': 'এখনো কোনো ক্যাম্পেইন নেই',
  'cmp.emptyHint': 'আগে গ্রাহকের মার্কেটিং সম্মতি সংরক্ষণ করুন, তারপর ক্যাম্পেইন বানান।',
  'cmp.readOnly': 'আপনি ক্যাম্পেইন দেখতে পারবেন। শপের মালিক তৈরি ও চালু করেন।',
  'cmp.col.name': 'নাম',
  'cmp.col.channel': 'মাধ্যম',
  'cmp.col.status': 'অবস্থা',
  'cmp.col.recipients': 'প্রাপক',
  'cmp.col.sent': 'পাঠানো',
  'cmp.col.when': 'কখন',
  'cmp.kind.ONE_OFF': 'একবার',
  'cmp.kind.FLOW': 'ফ্লো',
  'cmp.status.DRAFT': 'খসড়া',
  'cmp.status.SCHEDULED': 'নির্ধারিত',
  'cmp.status.SENDING': 'পাঠানো চলছে',
  'cmp.status.PAUSED': 'থামানো',
  'cmp.status.COMPLETED': 'সম্পন্ন',
  'cmp.status.CANCELLED': 'বাতিল',
  'cmp.status.ACTIVE': 'চালু',
  'cmp.flow.WIN_BACK': 'পুরনো ক্রেতাদের ফেরানো',
  'cmp.flow.REPEAT_NUDGE': 'আবার কেনার রিমাইন্ডার',
  'cmp.flow.INACTIVE': 'নিষ্ক্রিয় গ্রাহক',
  'cmp.flowAbout.WIN_BACK': 'যাঁরা আগে পার্সেল পেয়েছেন কিন্তু {days} দিন অর্ডার করেননি।',
  'cmp.flowAbout.REPEAT_NUDGE': 'যাঁদের শেষ অর্ডার প্রায় {days} দিন আগে ডেলিভারি হয়েছে।',
  'cmp.flowAbout.INACTIVE': '{days} দিন কোনো অর্ডার নেই (CRM-এর "নিষ্ক্রিয়" সংজ্ঞা)।',
  'cmp.channel.EMAIL': 'ইমেইল',
  'cmp.channel.WHATSAPP': 'WhatsApp',
  'cmp.b.name': 'ক্যাম্পেইনের নাম',
  'cmp.b.kind': 'ধরন',
  'cmp.b.flow': 'ফ্লো',
  'cmp.b.flowDays': 'কত দিন পর',
  'cmp.b.channel': 'মাধ্যম',
  'cmp.b.template': 'মার্কেটিং টেমপ্লেট',
  'cmp.b.noTemplates': 'এই মাধ্যমের কোনো মার্কেটিং টেমপ্লেট নেই। মেসেজিং থেকে তৈরি করুন।',
  'cmp.b.language': 'মেসেজের ভাষা',
  'cmp.b.audience': 'কারা পাবেন',
  'cmp.b.segment': 'CRM সেগমেন্ট',
  'cmp.b.anySegment': 'সব গ্রাহক',
  'cmp.b.tag': 'CRM ট্যাগ',
  'cmp.b.anyTag': 'যেকোনো ট্যাগ',
  'cmp.b.minOrders': 'কমপক্ষে অর্ডার',
  'cmp.b.maxOrders': 'সর্বোচ্চ অর্ডার',
  'cmp.b.lastBefore': 'শেষ অর্ডার … দিনের বেশি আগে',
  'cmp.b.lastWithin': 'শেষ অর্ডার … দিনের মধ্যে',
  'cmp.b.pace': 'পাঠানোর গতি',
  'cmp.b.rate': 'প্রতি মিনিটে মেসেজ',
  'cmp.b.cap': 'একজন গ্রাহক প্রতি … ঘণ্টায় সর্বোচ্চ একটি অফার',
  'cmp.b.attribution': '… দিনের মধ্যে দেওয়া অর্ডার গুনুন',
  'cmp.b.estimate': 'প্রাপক যাচাই',
  'cmp.b.save': 'খসড়া সংরক্ষণ',
  'cmp.b.saved': 'খসড়া সংরক্ষিত',
  'cmp.b.preview': 'প্রিভিউ',
  'cmp.b.tagHint': 'অটোমেশন নিয়ম অর্ডারের ঘটনায় CRM ট্যাগ যোগ বা বাদ দিতে পারে। সেই গ্রাহকদের কাছে পৌঁছাতে ট্যাগ বেছে নিন।',
  'cmp.est.matched': 'শর্তে মেলে',
  'cmp.est.reachable': 'এই ক্যাম্পেইন পেতে পারবেন',
  'cmp.est.overLimit': 'শুধু প্রথম {limit} জন গ্রাহক যুক্ত হবেন।',
  'cmp.skip.NO_CONTACT': 'এই মাধ্যমে ঠিকানা নেই',
  'cmp.skip.NO_MARKETING_CONSENT': 'মার্কেটিং সম্মতি নেই',
  'cmp.skip.OPTED_OUT': 'অফার বন্ধ করেছেন',
  'cmp.skip.UNDELIVERABLE': 'ঠিকানায় মেসেজ যায় না',
  'cmp.skip.FREQUENCY_CAP': 'সম্প্রতি অফার পেয়েছেন',
  'cmp.skip.CUSTOMER_BLOCKED': 'গ্রাহক ব্লক বা মুছে ফেলা',
  'cmp.skip.CANCELLED': 'ক্যাম্পেইন বাতিল',
  'cmp.rules':
    'সবসময় চালু: রাত {start}টা থেকে সকাল {end}টা পর্যন্ত মার্কেটিং পাঠানো হয় না, পাঠানোর মুহূর্তে আবার সম্মতি যাচাই হয়, আর প্রতিটি ইমেইলে এক ক্লিকে আনসাবস্ক্রাইব থাকে।',
  'cmp.launch': 'এখনই পাঠান',
  'cmp.schedule': 'সময় নির্ধারণ',
  'cmp.scheduleAt': 'পাঠানোর সময়',
  'cmp.activate': 'ফ্লো চালু করুন',
  'cmp.pause': 'থামান',
  'cmp.resume': 'আবার চালু',
  'cmp.cancel': 'ক্যাম্পেইন বাতিল',
  'cmp.cancelConfirm': 'ক্যাম্পেইন বাতিল করবেন? যেগুলো এখনো যায়নি সেগুলো আর যাবে না।',
  'cmp.launchConfirm': 'এখনই {count} জন গ্রাহককে পাঠাবেন?',
  'cmp.blocked': 'এখনো পাঠানো যাবে না',
  'cmp.a.title': 'ফলাফল',
  'cmp.a.recipients': 'প্রাপক',
  'cmp.a.sent': 'পাঠানো',
  'cmp.a.delivered': 'পৌঁছেছে',
  'cmp.a.read': 'পড়া / খোলা',
  'cmp.a.failed': 'ব্যর্থ',
  'cmp.a.optOuts': 'আনসাবস্ক্রাইব',
  'cmp.a.notReported': 'এই প্রোভাইডার জানায় না',
  'cmp.a.skipped': 'যাঁদের পাঠানো হয়নি',
  'cmp.a.errors': 'ব্যর্থতার কারণ',
  'cmp.a.ordersAfter': 'মেসেজের পর {days} দিনের মধ্যে অর্ডার',
  'cmp.a.ordersAfterHint': 'শুধু গণনা, দাবি নয়: মেসেজ পাওয়ার পর এঁরা অর্ডার দিয়েছেন; কারণ মেসেজ না-ও হতে পারে।',
  'cmp.a.buyers': 'অর্ডার দেওয়া গ্রাহক',
  'cmp.a.orders': 'অর্ডার',
  'cmp.a.value': 'অর্ডারের মূল্য',
  'cmp.a.pending': 'পাঠানোর অপেক্ষায়',
  'cmp.r.title': 'প্রাপক',
  'cmp.r.status.PENDING': 'অপেক্ষায়',
  'cmp.r.status.QUEUED': 'সারিতে',
  'cmp.r.status.SKIPPED': 'বাদ',
  'cmp.m.QUEUED': 'সারিতে',
  'cmp.m.SENDING': 'পাঠানো হচ্ছে',
  'cmp.m.RETRY': 'আবার চেষ্টা',
  'cmp.m.SENT': 'পাঠানো',
  'cmp.m.DELIVERED': 'পৌঁছেছে',
  'cmp.m.READ': 'পড়েছেন',
  'cmp.m.FAILED': 'ব্যর্থ',
  'cmp.m.SUPPRESSED': 'থামানো (সম্মতি)',
  'cmp.m.UNKNOWN': 'অজানা — আবার পাঠানোর আগে যাচাই করুন',
  'cmp.m.CANCELLED': 'বাতিল',
  'cmp.blocker.CHANNEL_DISABLED': 'মেসেজিং থেকে এই মাধ্যম চালু করুন।',
  'cmp.blocker.WHATSAPP_CONNECTION_REQUIRED': 'ইন্টিগ্রেশন থেকে আপনার WhatsApp Business নম্বর যুক্ত করুন।',
  'cmp.blocker.META_APP_SETUP_REQUIRED': 'এই ecomsbd-এ WhatsApp এখনো সেটআপ হয়নি।',
  'cmp.blocker.EMAIL_OFFICIAL_PROVIDER_REQUIRED': 'এই ecomsbd-এ ইমেইল পাঠানো এখনো সেটআপ হয়নি।',
  'cmp.blocker.WHATSAPP_TEMPLATE_NOT_APPROVED': 'Meta এখনো টেমপ্লেটটি অনুমোদন করেনি। ইন্টিগ্রেশন থেকে যাচাই করুন।',
  'cmp.blocker.WHATSAPP_TEMPLATE_LANGUAGE': 'বেছে নেওয়া ভাষায় টেমপ্লেটটির অনুমোদন নেই।',
  'cmp.blocker.TEMPLATE_ARCHIVED': 'টেমপ্লেটটি আর্কাইভ করা হয়েছে।',
  'cmp.blocker.TEMPLATE_NOT_FOUND': 'টেমপ্লেটটি আর নেই।',
  'cmp.blocker.TEMPLATE_PURPOSE_MISMATCH': 'একটি মার্কেটিং টেমপ্লেট বেছে নিন।',
  'cmp.blocker.TEMPLATE_CHANNEL_MISMATCH': 'টেমপ্লেটটি অন্য মাধ্যমের।',
  'cmp.monitor.title': 'গত ৩০ দিন',
  'cmp.monitor.contacts': 'অফার পেতে রাজি গ্রাহক',
  'cmp.monitor.optOuts': 'অফার বন্ধ করেছেন',
  'cmp.monitor.marketing': 'পাঠানো অফার',
  'cmp.monitor.transactional': 'পাঠানো অর্ডার আপডেট',
};
