export const crmEn = {
  "crm.ORDER_PARTIAL_DELIVERED": "Parcel partly delivered",
  "crm.unstar": "Remove star",
  "crm.unblock": "Unblock",
  "crm.reveal": "Reveal phone",
  "crm.revealReason": "Why do you need the phone number?",
  "crm.blockReason": "Reason for blocking",
  "notif.cat.CRM": "Customer follow-ups",
  "crm.NO_ORDERS": "No orders yet",
  "crm.SMALL_SAMPLE": "Too few completed orders for a reliable risk result",
  "crm.STRONG_DELIVERY_RATE": "Most completed orders were delivered",
  "crm.MIXED_DELIVERY_RATE": "Completed orders have mixed delivery outcomes",
  "crm.WEAK_DELIVERY_RATE": "Many completed orders were not delivered",
  "crm.HAS_RETURNS": "This shop has recorded returns",
  "crm.HAS_CANCELLATIONS": "This shop has recorded cancellations",
  "crm.OWN_SHOP_HISTORY_ONLY": "Based only on this shop's history",
  "crm.title": "Customer CRM",
  "crm.overview": "Overview",
  "crm.segment": "Segment",
  "crm.tags": "Tags",
  "crm.notes": "Notes",
  "crm.followups": "Follow-ups",
  "crm.timeline": "Activity timeline",
  "crm.orders": "Recent orders",
  "crm.all": "All customers",
  "crm.NEW": "New customers",
  "crm.REPEAT": "Repeat buyers",
  "crm.HIGH_VALUE": "High value",
  "crm.INACTIVE": "Inactive customers",
  "crm.SUCCESSFUL_REPEAT": "Successful repeat buyers",
  "crm.REPEATED_RTO": "Repeated RTO history",
  "crm.FOLLOW_UP_DUE": "Follow-up due",
  "crm.ACTIVE_ORDERS": "Active orders",
  "crm.definitions": "How segments work",
  "crm.rules": "New: first order in {new_days} days. Repeat: at least {repeat_min_orders} recorded orders (including drafts and cancellations). Inactive: no order for {inactive_days} days. Successful repeat: at least {repeat_min_outcomes} delivered parcels. Repeated RTO: at least {repeat_min_outcomes} RTOs among {rto_min_completed} completed parcels. Due: an unfinished follow-up is due. Active: an order is not completed or cancelled and has no parcel yet or an unresolved parcel.",
  "crm.highRule": "High value: measured delivered revenue at or above this shop's average among customers with positive measured revenue. Requires at least {high_value_min_customers} such customers.",
  "crm.threshold": "Shop threshold",
  "crm.minOrders": "Minimum orders",
  "crm.maxOrders": "Maximum orders",
  "crm.lastFrom": "Last order from",
  "crm.lastUntil": "Last order through",
  "crm.firstOrder": "First order",
  "crm.lastOrder": "Latest order",
  "crm.cancelled": "Cancelled",
  "crm.active": "Active orders",
  "crm.value": "Historical value",
  "crm.totalValue": "Total ordered value",
  "crm.revenue": "Measured delivered revenue",
  "crm.profit": "Measured profit contribution",
  "crm.average": "Average measured delivered order",
  "crm.coverage": "{measured} of {completed} completed parcels have fully measured values. Totals cover those parcels only.",
  "crm.noValue": "Not measured yet",
  "crm.locked": "Historical money figures are unavailable for your role or plan.",
  "crm.noteHint": "Seller notes are personal observations, not verified facts. Notes cannot be edited or deleted.",
  "crm.addNote": "Add note",
  "crm.addTag": "Add tag",
  "crm.removeTag": "Remove tag",
  "crm.createTag": "Create tag",
  "crm.archiveTag": "Archive tag",
  "crm.tagName": "Tag name",
  "crm.bulk": "Apply to {count} selected customers",
  "crm.addFollowup": "Add follow-up",
  "crm.task": "Follow-up task",
  "crm.due": "Due",
  "crm.assignee": "Assigned to",
  "crm.unassigned": "Unassigned",
  "crm.complete": "Complete",
  "crm.reopen": "Reopen",
  "crm.COMPLETED": "Completed",
  "crm.OVERDUE": "Overdue",
  "crm.UPCOMING": "Upcoming",
  "crm.openTasks": "Open tasks",
  "crm.allTasks": "All tasks",
  "crm.member": "Team member",
  "crm.save": "Save",
  "crm.close": "Close",
  "crm.previous": "Previous",
  "crm.next": "Next",
  "crm.moreTags": "Next tags",
  "crm.moreMembers": "Next members",
  "crm.empty": "Nothing here yet",
  "crm.loading": "Loading…",
  "crm.error": "Could not save. Please try again.",
  "crm.saved": "Saved",
  "crm.risk": "Risk Check · this shop only",
  "crm.INSUFFICIENT_DATA": "Not enough history",
  "crm.LOW_RISK": "Lower delivery risk",
  "crm.MEDIUM_RISK": "Mixed delivery history",
  "crm.HIGH_RISK": "Review delivery history",
  "crm.UNKNOWN": "Not enough history",
  "crm.NOTE": "Seller note",
  "crm.NOTE_LEGACY": "Earlier seller note",
  "crm.TAG_ADDED": "Tag added",
  "crm.TAG_REMOVED": "Tag removed",
  "crm.FOLLOW_UP_CREATED": "Follow-up created",
  "crm.FOLLOW_UP_COMPLETED": "Follow-up completed",
  "crm.FOLLOW_UP_REOPENED": "Follow-up reopened",
  "crm.ORDER_CREATED": "Order created",
  "crm.ORDER_CANCELLED": "Order cancelled",
  "crm.ORDER_DELIVERED": "Parcel delivered",
  "crm.ORDER_RTO": "Parcel returned / RTO",
  "crm.legacy": "Earlier note",
  "crm.address": "Address",
  "crm.customer": "Customer",
  "crm.orderCount": "Orders",
  "crm.delivered": "Delivered parcels",
  "crm.returned": "Returned / RTO parcels",
  "crm.success": "Delivery success",
  "crm.search": "Name, phone or last four digits",
  "crm.reset": "Clear filters"
} as const;
export const crmBn: Record<keyof typeof crmEn, string> = {
  "crm.ORDER_PARTIAL_DELIVERED": "পার্সেল আংশিক ডেলিভারি হয়েছে",
  "crm.unstar": "তারকা সরান",
  "crm.unblock": "ব্লক সরান",
  "crm.reveal": "ফোন নম্বর দেখুন",
  "crm.revealReason": "ফোন নম্বর কেন দরকার?",
  "crm.blockReason": "ব্লক করার কারণ",
  "notif.cat.CRM": "কাস্টমারের ফলো-আপ",
  "crm.NO_ORDERS": "এখনো অর্ডার নেই",
  "crm.SMALL_SAMPLE": "নির্ভরযোগ্য ফলের জন্য সম্পন্ন অর্ডার কম",
  "crm.STRONG_DELIVERY_RATE": "বেশির ভাগ সম্পন্ন অর্ডার ডেলিভারি হয়েছে",
  "crm.MIXED_DELIVERY_RATE": "সম্পন্ন অর্ডারের ডেলিভারির ফল মিশ্র",
  "crm.WEAK_DELIVERY_RATE": "অনেক সম্পন্ন অর্ডার ডেলিভারি হয়নি",
  "crm.HAS_RETURNS": "এই দোকানে ফেরতের ইতিহাস আছে",
  "crm.HAS_CANCELLATIONS": "এই দোকানে বাতিলের ইতিহাস আছে",
  "crm.OWN_SHOP_HISTORY_ONLY": "শুধু এই দোকানের ইতিহাসের ভিত্তিতে",
  "crm.title": "কাস্টমার CRM",
  "crm.overview": "সারসংক্ষেপ",
  "crm.segment": "কাস্টমারের ধরন",
  "crm.tags": "ট্যাগ",
  "crm.notes": "নোট",
  "crm.followups": "ফলো-আপ",
  "crm.timeline": "কাজের ইতিহাস",
  "crm.orders": "সাম্প্রতিক অর্ডার",
  "crm.all": "সব কাস্টমার",
  "crm.NEW": "নতুন কাস্টমার",
  "crm.REPEAT": "আবার কিনেছেন",
  "crm.HIGH_VALUE": "বেশি মূল্যের ক্রেতা",
  "crm.INACTIVE": "অনেক দিন অর্ডার নেই",
  "crm.SUCCESSFUL_REPEAT": "একাধিকবার ডেলিভারি পেয়েছেন",
  "crm.REPEATED_RTO": "একাধিক অর্ডার ফেরত এসেছে",
  "crm.FOLLOW_UP_DUE": "ফলো-আপের সময় হয়েছে",
  "crm.ACTIVE_ORDERS": "চলমান অর্ডার",
  "crm.definitions": "কাস্টমারের ধরন কীভাবে নির্ধারিত হয়",
  "crm.rules": "নতুন: গত {new_days} দিনে প্রথম অর্ডার। পুনরায় ক্রেতা: অন্তত {repeat_min_orders}টি নথিভুক্ত অর্ডার (খসড়া ও বাতিলসহ)। নিষ্ক্রিয়: {inactive_days} দিন অর্ডার নেই। সফল পুনরায় ক্রেতা: অন্তত {repeat_min_outcomes}টি পার্সেল ডেলিভারি হয়েছে। একাধিক ফেরত: অন্তত {rto_min_completed}টি সম্পন্ন পার্সেলের মধ্যে {repeat_min_outcomes}টি ফেরত। ফলো-আপ বাকি: অসম্পন্ন কাজের সময় হয়েছে। চলমান: অর্ডার সম্পন্ন বা বাতিল হয়নি এবং পার্সেল এখনো পাঠানো হয়নি বা চূড়ান্ত ফল আসেনি।",
  "crm.highRule": "বেশি মূল্যের ক্রেতা: মাপা ডেলিভারি আয় আছে এমন কাস্টমারদের মধ্যে দোকানের গড়ের সমান বা বেশি আয়। এমন অন্তত {high_value_min_customers} জন কাস্টমার থাকতে হবে।",
  "crm.threshold": "এই দোকানের সীমা",
  "crm.minOrders": "ন্যূনতম অর্ডার",
  "crm.maxOrders": "সর্বোচ্চ অর্ডার",
  "crm.lastFrom": "শেষ অর্ডারের শুরুর তারিখ",
  "crm.lastUntil": "শেষ অর্ডারের শেষ তারিখ",
  "crm.firstOrder": "প্রথম অর্ডার",
  "crm.lastOrder": "শেষ অর্ডার",
  "crm.cancelled": "বাতিল",
  "crm.active": "চলমান অর্ডার",
  "crm.value": "আগের অর্ডারের মূল্য",
  "crm.totalValue": "মোট অর্ডারের মূল্য",
  "crm.revenue": "মাপা ডেলিভারি আয়",
  "crm.profit": "মাপা লাভের অবদান",
  "crm.average": "মাপা ডেলিভারি অর্ডারের গড় মূল্য",
  "crm.coverage": "সম্পন্ন {completed}টি পার্সেলের মধ্যে {measured}টির সব হিসাব মাপা আছে। মোট হিসাবে শুধু সেগুলো আছে।",
  "crm.noValue": "এখনো মাপা হয়নি",
  "crm.locked": "আপনার ভূমিকা বা প্ল্যানে আগের টাকার হিসাব দেখা যায় না।",
  "crm.noteHint": "বিক্রেতার নোট ব্যক্তিগত মন্তব্য, যাচাই করা তথ্য নয়। নোট বদলানো বা মুছে ফেলা যায় না।",
  "crm.addNote": "নোট যোগ করুন",
  "crm.addTag": "ট্যাগ যোগ করুন",
  "crm.removeTag": "ট্যাগ সরান",
  "crm.createTag": "নতুন ট্যাগ",
  "crm.archiveTag": "ট্যাগ বন্ধ করুন",
  "crm.tagName": "ট্যাগের নাম",
  "crm.bulk": "বেছে নেওয়া {count} জন কাস্টমারে প্রয়োগ করুন",
  "crm.addFollowup": "ফলো-আপ যোগ করুন",
  "crm.task": "ফলো-আপের কাজ",
  "crm.due": "সময়",
  "crm.assignee": "দায়িত্বে",
  "crm.unassigned": "কাউকে দেওয়া হয়নি",
  "crm.complete": "সম্পন্ন করুন",
  "crm.reopen": "আবার চালু করুন",
  "crm.COMPLETED": "সম্পন্ন",
  "crm.OVERDUE": "সময় পেরিয়েছে",
  "crm.UPCOMING": "সামনে আছে",
  "crm.openTasks": "বাকি কাজ",
  "crm.allTasks": "সব কাজ",
  "crm.member": "টিমের সদস্য",
  "crm.save": "সংরক্ষণ করুন",
  "crm.close": "বন্ধ করুন",
  "crm.previous": "আগের",
  "crm.next": "পরের",
  "crm.moreTags": "পরের ট্যাগ",
  "crm.moreMembers": "পরের সদস্য",
  "crm.empty": "এখনো কিছু নেই",
  "crm.loading": "লোড হচ্ছে…",
  "crm.error": "সংরক্ষণ হয়নি। আবার চেষ্টা করুন।",
  "crm.saved": "সংরক্ষিত হয়েছে",
  "crm.risk": "রিস্ক চেক · শুধু এই দোকানের তথ্য",
  "crm.INSUFFICIENT_DATA": "যথেষ্ট ইতিহাস নেই",
  "crm.LOW_RISK": "ডেলিভারির ঝুঁকি কম",
  "crm.MEDIUM_RISK": "ডেলিভারির ফল মিশ্র",
  "crm.HIGH_RISK": "ডেলিভারির ইতিহাস দেখুন",
  "crm.UNKNOWN": "যথেষ্ট ইতিহাস নেই",
  "crm.NOTE": "বিক্রেতার নোট",
  "crm.NOTE_LEGACY": "আগের বিক্রেতার নোট",
  "crm.TAG_ADDED": "ট্যাগ যোগ হয়েছে",
  "crm.TAG_REMOVED": "ট্যাগ সরানো হয়েছে",
  "crm.FOLLOW_UP_CREATED": "ফলো-আপ তৈরি হয়েছে",
  "crm.FOLLOW_UP_COMPLETED": "ফলো-আপ সম্পন্ন হয়েছে",
  "crm.FOLLOW_UP_REOPENED": "ফলো-আপ আবার চালু হয়েছে",
  "crm.ORDER_CREATED": "অর্ডার তৈরি হয়েছে",
  "crm.ORDER_CANCELLED": "অর্ডার বাতিল হয়েছে",
  "crm.ORDER_DELIVERED": "পার্সেল ডেলিভারি হয়েছে",
  "crm.ORDER_RTO": "পার্সেল ফেরত এসেছে",
  "crm.legacy": "আগের নোট",
  "crm.address": "ঠিকানা",
  "crm.customer": "কাস্টমার",
  "crm.orderCount": "অর্ডার",
  "crm.delivered": "ডেলিভারি হওয়া পার্সেল",
  "crm.returned": "ফেরত / RTO পার্সেল",
  "crm.success": "সফল ডেলিভারি",
  "crm.search": "নাম, ফোন বা শেষ চার সংখ্যা",
  "crm.reset": "ফিল্টার মুছুন"
};
