/**
 * Developer portal copy (V3.8). Code, headers and API paths stay in English
 * in both languages because they are typed exactly as shown.
 */
export const developerEn = {
  'dev.title': 'Developer',
  'dev.subtitle': 'API keys, signed webhooks, delivery history and test tools for your website or app.',
  'dev.tab.keys': 'API keys',
  'dev.tab.webhooks': 'Webhooks',
  'dev.tab.deliveries': 'Deliveries',
  'dev.tab.requests': 'Requests',
  'dev.tab.health': 'Health',
  'dev.tab.tools': 'Test tools',
  'dev.once': 'Copy now — shown only once',
  'dev.onceHint': 'It is stored only as a one-way hash (keys) or encrypted (secrets). Nobody can show it again.',
  'dev.saved': 'I have saved it',
  'dev.key.create': 'Create key',
  'dev.key.name': 'Name',
  'dev.key.rate': 'Requests per minute',
  'dev.key.expiry': 'Expires after (days, optional)',
  'dev.key.scopes': 'Scopes',
  'dev.key.scopesHint': 'Give each key only what it needs. The API refuses anything else.',
  'dev.key.state.ACTIVE': 'Active',
  'dev.key.state.REVOKED': 'Revoked',
  'dev.key.state.EXPIRED': 'Expired',
  'dev.key.lastUsed': 'Last used',
  'dev.key.never': 'Never',
  'dev.key.expires': 'Expires',
  'dev.key.noExpiry': 'No expiry',
  'dev.key.website': 'Used by a Custom Website connection',
  'dev.key.rotate': 'Rotate',
  'dev.key.rotateConfirm': 'Issue a new secret now? The current key stops working immediately; update your website with the new one.',
  'dev.key.revoke': 'Revoke',
  'dev.key.revokeConfirm': 'Revoke this key? Anything using it stops working immediately.',
  'dev.key.empty': 'No API keys yet.',
  'dev.hook.create': 'Add webhook',
  'dev.hook.url': 'Public HTTPS endpoint',
  'dev.hook.events': 'Events',
  'dev.hook.saveEvents': 'Save events',
  'dev.hook.enable': 'Turn on',
  'dev.hook.disable': 'Turn off',
  'dev.hook.rotate': 'Rotate secret',
  'dev.hook.rotateConfirm': 'Issue a new signing secret now? Deliveries from now on are signed only with the new one.',
  'dev.hook.test': 'Send test webhook',
  'dev.hook.testDone': 'Test event queued. It is a webhook.test event and creates no business data.',
  'dev.hook.empty': 'No webhooks yet.',
  'dev.del.filter': 'Show',
  'dev.del.all': 'All',
  'dev.del.attempts': 'Attempts',
  'dev.del.retry': 'Retry',
  'dev.del.empty': 'No deliveries.',
  'dev.del.status.PENDING': 'Waiting',
  'dev.del.status.RETRY': 'Retrying',
  'dev.del.status.DELIVERED': 'Delivered',
  'dev.del.status.FAILED': 'Failed',
  'dev.del.status.DISABLED': 'Webhook off',
  'dev.req.hint': 'Recent write requests, from their idempotency receipts. Request bodies are not kept here.',
  'dev.req.empty': 'No write requests yet.',
  'dev.req.endpoint': 'Endpoint',
  'dev.req.key': 'Idempotency-Key',
  'dev.req.when': 'When',
  'dev.health.api': 'API',
  'dev.health.api.ACTIVE': 'Ready — {n} active key(s)',
  'dev.health.api.NO_ACTIVE_KEY': 'No active key',
  'dev.health.lastRequest': 'Last request',
  'dev.health.expiring': '{n} key(s) expire within 7 days',
  'dev.health.webhooks': 'Webhooks',
  'dev.health.state.ACTIVE': 'Healthy',
  'dev.health.state.FAILING': 'Failing',
  'dev.health.state.DISABLED': 'Off',
  'dev.health.failed24h': '{n} failed or retrying in 24 h',
  'dev.health.latest': 'Latest delivery',
  'dev.health.latestError': 'Latest error',
  'dev.health.connections': 'Custom Website connections',
  'dev.health.connectionsHint': 'The same health the Integrations Hub shows.',
  'dev.health.none': 'None',
  'dev.tools.check': 'Test API key',
  'dev.tools.checkHint': 'Paste a key to see whether it belongs to this shop and works. It is compared by hash and never stored.',
  'dev.tools.checkRun': 'Check key',
  'dev.tools.valid': 'Valid — {name} · {scopes}',
  'dev.tools.invalid': 'Not a working key for this shop ({state}).',
  'dev.tools.samples': 'Sample payloads',
  'dev.tools.samplesHint': 'Placeholders only. Nothing here is sent or created.',
  'dev.tools.sampleOrder': 'Order your website sends',
  'dev.tools.sampleEvent': 'Event ecomsbd sends',
  'dev.tools.verify': 'Signature check',
  'dev.tools.verifyHint': 'Runs in your browser: the secret you type never leaves this page.',
  'dev.tools.secret': 'Signing secret',
  'dev.tools.body': 'Raw body',
  'dev.tools.header': 'X-Ecomsbd-Signature header',
  'dev.tools.now': 'Check the 5-minute window against my clock',
  'dev.tools.verifyRun': 'Verify',
  'dev.tools.verifyOk': 'Signature is valid.',
  'dev.tools.verifyBad': 'Signature does not match this body and secret.',
  'dev.tools.verifyOld': 'Signature matches, but the timestamp is outside 5 minutes: treat it as a replay.',
  'dev.tools.useExample': 'Fill with the example',
  'dev.tools.docs': 'The full API reference is docs/PUBLIC_API.md; the SDKs are in sdk/.',
  'int.dev.testOrder': 'Send test order',
  'int.dev.testOrderHint': 'Checked exactly like a real order. Nothing is created.',
  'int.dev.testOrderOk': 'Test order is valid: {items} item(s), COD {cod}. Nothing was created.',
  'int.dev.testOrderBad': 'Test order has problems: {problems}. Nothing was created.',
} as const;

export const developerBn: Record<keyof typeof developerEn, string> = {
  'dev.title': 'ডেভেলপার',
  'dev.subtitle': 'আপনার ওয়েবসাইট বা অ্যাপের জন্য API কী, স্বাক্ষরযুক্ত ওয়েবহুক, পাঠানোর ইতিহাস ও টেস্ট টুল।',
  'dev.tab.keys': 'API কী',
  'dev.tab.webhooks': 'ওয়েবহুক',
  'dev.tab.deliveries': 'পাঠানো',
  'dev.tab.requests': 'অনুরোধ',
  'dev.tab.health': 'অবস্থা',
  'dev.tab.tools': 'টেস্ট টুল',
  'dev.once': 'এখনই কপি করুন — একবারই দেখানো হবে',
  'dev.onceHint': 'কী শুধু একমুখী হ্যাশ হিসেবে আর সিক্রেট এনক্রিপ্ট করে রাখা হয়। কেউ আবার দেখাতে পারবে না।',
  'dev.saved': 'সংরক্ষণ করেছি',
  'dev.key.create': 'কী তৈরি',
  'dev.key.name': 'নাম',
  'dev.key.rate': 'প্রতি মিনিটে অনুরোধ',
  'dev.key.expiry': 'মেয়াদ (দিন, ঐচ্ছিক)',
  'dev.key.scopes': 'অনুমতি',
  'dev.key.scopesHint': 'প্রতিটি কী-কে শুধু প্রয়োজনীয় অনুমতি দিন। বাকি সব API ফিরিয়ে দেয়।',
  'dev.key.state.ACTIVE': 'চালু',
  'dev.key.state.REVOKED': 'বাতিল',
  'dev.key.state.EXPIRED': 'মেয়াদ শেষ',
  'dev.key.lastUsed': 'শেষ ব্যবহার',
  'dev.key.never': 'কখনো নয়',
  'dev.key.expires': 'মেয়াদ',
  'dev.key.noExpiry': 'মেয়াদ নেই',
  'dev.key.website': 'একটি কাস্টম ওয়েবসাইট সংযোগ ব্যবহার করছে',
  'dev.key.rotate': 'নতুন কী',
  'dev.key.rotateConfirm': 'এখনই নতুন সিক্রেট দেবেন? বর্তমান কী সঙ্গে সঙ্গে বন্ধ হবে; ওয়েবসাইটে নতুনটি বসান।',
  'dev.key.revoke': 'বাতিল',
  'dev.key.revokeConfirm': 'এই কী বাতিল করবেন? যা এটি ব্যবহার করছে তা সঙ্গে সঙ্গে বন্ধ হবে।',
  'dev.key.empty': 'এখনো কোনো API কী নেই।',
  'dev.hook.create': 'ওয়েবহুক যোগ করুন',
  'dev.hook.url': 'পাবলিক HTTPS ঠিকানা',
  'dev.hook.events': 'ইভেন্ট',
  'dev.hook.saveEvents': 'ইভেন্ট সংরক্ষণ',
  'dev.hook.enable': 'চালু করুন',
  'dev.hook.disable': 'বন্ধ করুন',
  'dev.hook.rotate': 'নতুন সিক্রেট',
  'dev.hook.rotateConfirm': 'এখনই নতুন সাইনিং সিক্রেট দেবেন? এখন থেকে পাঠানো সব শুধু নতুনটি দিয়ে স্বাক্ষরিত হবে।',
  'dev.hook.test': 'টেস্ট ওয়েবহুক পাঠান',
  'dev.hook.testDone': 'টেস্ট ইভেন্ট সারিতে আছে। এটি webhook.test ইভেন্ট, কোনো ব্যবসায়িক তথ্য তৈরি করে না।',
  'dev.hook.empty': 'এখনো কোনো ওয়েবহুক নেই।',
  'dev.del.filter': 'দেখান',
  'dev.del.all': 'সব',
  'dev.del.attempts': 'চেষ্টাগুলো',
  'dev.del.retry': 'আবার চেষ্টা',
  'dev.del.empty': 'কিছু পাঠানো হয়নি।',
  'dev.del.status.PENDING': 'অপেক্ষায়',
  'dev.del.status.RETRY': 'আবার চেষ্টা হচ্ছে',
  'dev.del.status.DELIVERED': 'পৌঁছেছে',
  'dev.del.status.FAILED': 'ব্যর্থ',
  'dev.del.status.DISABLED': 'ওয়েবহুক বন্ধ',
  'dev.req.hint': 'সাম্প্রতিক লেখার অনুরোধ, তাদের idempotency রসিদ থেকে। অনুরোধের তথ্য এখানে রাখা হয় না।',
  'dev.req.empty': 'এখনো কোনো লেখার অনুরোধ নেই।',
  'dev.req.endpoint': 'এন্ডপয়েন্ট',
  'dev.req.key': 'Idempotency-Key',
  'dev.req.when': 'কখন',
  'dev.health.api': 'API',
  'dev.health.api.ACTIVE': 'প্রস্তুত — {n}টি চালু কী',
  'dev.health.api.NO_ACTIVE_KEY': 'কোনো চালু কী নেই',
  'dev.health.lastRequest': 'শেষ অনুরোধ',
  'dev.health.expiring': '{n}টি কী-এর মেয়াদ ৭ দিনের মধ্যে শেষ',
  'dev.health.webhooks': 'ওয়েবহুক',
  'dev.health.state.ACTIVE': 'ঠিক আছে',
  'dev.health.state.FAILING': 'ব্যর্থ হচ্ছে',
  'dev.health.state.DISABLED': 'বন্ধ',
  'dev.health.failed24h': '২৪ ঘণ্টায় {n}টি ব্যর্থ বা আবার চেষ্টায়',
  'dev.health.latest': 'শেষ পাঠানো',
  'dev.health.latestError': 'শেষ ত্রুটি',
  'dev.health.connections': 'কাস্টম ওয়েবসাইট সংযোগ',
  'dev.health.connectionsHint': 'ইন্টিগ্রেশন হাব যে অবস্থা দেখায়, সেটাই।',
  'dev.health.none': 'নেই',
  'dev.tools.check': 'API কী পরীক্ষা',
  'dev.tools.checkHint': 'কী পেস্ট করুন: এটি এই শপের কি না ও কাজ করে কি না দেখুন। হ্যাশ দিয়ে মেলানো হয়, কোথাও রাখা হয় না।',
  'dev.tools.checkRun': 'কী পরীক্ষা করুন',
  'dev.tools.valid': 'বৈধ — {name} · {scopes}',
  'dev.tools.invalid': 'এই শপের জন্য কাজ করা কী নয় ({state})।',
  'dev.tools.samples': 'নমুনা তথ্য',
  'dev.tools.samplesHint': 'শুধু নমুনা। এখান থেকে কিছু পাঠানো বা তৈরি হয় না।',
  'dev.tools.sampleOrder': 'আপনার ওয়েবসাইট যে অর্ডার পাঠায়',
  'dev.tools.sampleEvent': 'ecomsbd যে ইভেন্ট পাঠায়',
  'dev.tools.verify': 'স্বাক্ষর যাচাই',
  'dev.tools.verifyHint': 'আপনার ব্রাউজারেই চলে: যে সিক্রেট লিখবেন তা এই পাতার বাইরে যায় না।',
  'dev.tools.secret': 'সাইনিং সিক্রেট',
  'dev.tools.body': 'মূল বডি',
  'dev.tools.header': 'X-Ecomsbd-Signature হেডার',
  'dev.tools.now': 'আমার ঘড়ি অনুযায়ী ৫ মিনিটের সীমা মিলিয়ে দেখুন',
  'dev.tools.verifyRun': 'যাচাই',
  'dev.tools.verifyOk': 'স্বাক্ষর বৈধ।',
  'dev.tools.verifyBad': 'এই বডি ও সিক্রেটের সঙ্গে স্বাক্ষর মেলে না।',
  'dev.tools.verifyOld': 'স্বাক্ষর মেলে, কিন্তু সময় ৫ মিনিটের বাইরে: এটিকে রিপ্লে ধরুন।',
  'dev.tools.useExample': 'নমুনা দিয়ে পূরণ করুন',
  'dev.tools.docs': 'পুরো API বিবরণ docs/PUBLIC_API.md-এ; SDK আছে sdk/-এ।',
  'int.dev.testOrder': 'টেস্ট অর্ডার পাঠান',
  'int.dev.testOrderHint': 'আসল অর্ডারের মতোই যাচাই হয়। কিছুই তৈরি হয় না।',
  'int.dev.testOrderOk': 'টেস্ট অর্ডার ঠিক আছে: {items}টি পণ্য, COD {cod}। কিছুই তৈরি হয়নি।',
  'int.dev.testOrderBad': 'টেস্ট অর্ডারে সমস্যা: {problems}। কিছুই তৈরি হয়নি।',
};
