/**
 * Forecasting copy (V3.6). Plain words over jargon: "likely to run out",
 * "reorder", "estimate" — every screen says it is a forecast, not a promise.
 */
export const forecastingEn = {
  'nav.forecasting': 'Forecasts',
  'fc.title': 'Forecasts',
  'fc.subtitle': 'What is likely to run out, what to reorder and the cash you can expect. Estimates from your own sales, never a guarantee.',
  'fc.tab.reorder': 'Reorder',
  'fc.tab.accuracy': 'Accuracy',
  'fc.tab.cash': 'Cash outlook',
  'fc.filter.all': 'All items',
  'fc.filter.at_risk': 'Likely to run out',
  'fc.filter.insufficient': 'Not enough history',
  'fc.coverDays': 'Stock to cover (days)',
  'fc.tile.atRisk': 'Likely to run out',
  'fc.tile.atRiskHint': 'Before a new order could arrive',
  'fc.tile.insufficient': 'Not enough history',
  'fc.tile.insufficientHint': 'No forecast until an item has sold on 14 days',
  'fc.tile.accuracy': 'Forecast error',
  'fc.tile.accuracyNone': 'Not measured yet',
  'fc.col.item': 'Item',
  'fc.col.confidence': 'Confidence',
  'fc.col.rate': 'Sells per day',
  'fc.col.onHand': 'On hand',
  'fc.col.incoming': 'On order',
  'fc.col.lead': 'Lead time',
  'fc.col.runsOut': 'Runs out',
  'fc.col.suggested': 'Suggested reorder',
  'fc.conf.HIGH': 'High',
  'fc.conf.MEDIUM': 'Medium',
  'fc.conf.INSUFFICIENT': 'Not enough history',
  'fc.lead.OBSERVED': 'from {n} received orders',
  'fc.lead.SUPPLIER': 'supplier’s estimate',
  'fc.lead.DEFAULT': 'assumed',
  'fc.days': '{n} days',
  'fc.today': 'Now',
  'fc.draft': 'Draft PO',
  'fc.drafted': 'Draft {number} created for {quantity}. Review it before ordering.',
  'fc.openDraft': 'Open draft',
  'fc.empty': 'Nothing to show here.',
  'fc.readOnly': 'You can see forecasts. Drafting purchase orders needs purchasing access.',
  'fc.err.NO_PREFERRED_SUPPLIER': 'Set a preferred supplier for this item first (Purchasing → Suppliers).',
  'fc.err.ALREADY_ON_ORDER': 'This item is already on a draft or open purchase order.',
  'fc.err.NO_SUGGESTION': 'Nothing to reorder for this item right now.',
  'fc.item.back': '← Forecasts',
  'fc.item.chart': 'Units sold per day, last 56 completed days',
  'fc.item.legendSold': 'Units sold',
  'fc.item.legendOut': 'Out of stock or not yet listed — not counted',
  'fc.item.table': 'Show as table',
  'fc.item.date': 'Date',
  'fc.item.units': 'Units',
  'fc.item.inStock': 'Counted',
  'fc.item.yes': 'Yes',
  'fc.item.no': 'No',
  'fc.how.title': 'How this was worked out',
  'fc.how.days': 'Days it could be sold: {n} (of the last {total})',
  'fc.how.units': 'Units sold on those days: {n}',
  'fc.how.recent': 'Recent average (last 14 days): {rate}/day',
  'fc.how.long': 'Longer average: {rate}/day',
  'fc.how.rate': 'Forecast: half of each = {rate}/day',
  'fc.how.safety': 'Safety stock for uneven sales: {n}',
  'fc.how.reorderPoint': 'Reorder point (lead time × daily sales + safety): {n}',
  'fc.how.suggested': 'Suggested reorder (enough for lead time + {cover} days, less on hand and on order): {n}',
  'fc.how.insufficient': 'A forecast needs sales on at least {days} days and {units} units in total. Until then no numbers are shown.',
  'fc.acc.title': 'How good the forecasts have been',
  'fc.acc.hint': 'Each morning’s forecast is stored. Four weeks later it is compared with what actually sold.',
  'fc.acc.notEnough': 'Not measured yet. Forecasts stored on at least 10 items need four weeks to be scored.',
  'fc.acc.noSales': 'Nothing sold in the scored period, so there is no error to measure.',
  'fc.acc.asOf': 'Forecast stored on',
  'fc.acc.items': 'Items scored',
  'fc.acc.skipped': 'Items without a forecast',
  'fc.acc.predicted': 'Units forecast',
  'fc.acc.actual': 'Units actually sold',
  'fc.acc.error': 'Error (weighted by volume)',
  'fc.acc.over': 'Forecasts ran high by {n} units.',
  'fc.acc.under': 'Forecasts ran low by {n} units.',
  'fc.cash.title': 'Cash outlook',
  'fc.cash.hint': 'Expected COD in against supplier money due out. An estimate from courier payout history and purchase orders, not a bank balance.',
  'fc.cash.window': 'When',
  'fc.cash.in': 'COD expected in',
  'fc.cash.out': 'Supplier payments due',
  'fc.cash.overdue': 'Already overdue',
  'fc.cash.next7': 'Next 7 days',
  'fc.cash.next14': 'Days 8–14',
  'fc.cash.later': 'Later',
  'fc.cash.noDate': 'No date known',
  'fc.cash.net7': 'Net, next 7 days',
  'fc.cash.net14': 'Net, next 14 days',
  'fc.cash.committed': 'Spoken for on open orders (not owed until received)',
  'fc.cash.unplaced': 'COD with no expected date yet',
  'fc.cash.noAccess': 'The cash outlook needs money access.',
  'pr.f.leadTime': 'Lead time (days from order to arrival)',
} as const;

export const forecastingBn: Record<keyof typeof forecastingEn, string> = {
  'nav.forecasting': 'পূর্বাভাস',
  'fc.title': 'পূর্বাভাস',
  'fc.subtitle': 'কোন মাল ফুরিয়ে যেতে পারে, কী আবার আনতে হবে আর কত টাকা আসতে পারে। আপনার নিজের বিক্রি থেকে অনুমান, নিশ্চয়তা নয়।',
  'fc.tab.reorder': 'আবার অর্ডার',
  'fc.tab.accuracy': 'নির্ভুলতা',
  'fc.tab.cash': 'টাকার হিসাবের অনুমান',
  'fc.filter.all': 'সব পণ্য',
  'fc.filter.at_risk': 'ফুরিয়ে যেতে পারে',
  'fc.filter.insufficient': 'যথেষ্ট বিক্রির ইতিহাস নেই',
  'fc.coverDays': 'কত দিনের মাল রাখবেন',
  'fc.tile.atRisk': 'ফুরিয়ে যেতে পারে',
  'fc.tile.atRiskHint': 'নতুন মাল আসার আগেই',
  'fc.tile.insufficient': 'যথেষ্ট ইতিহাস নেই',
  'fc.tile.insufficientHint': '১৪ দিন বিক্রি না হওয়া পর্যন্ত পূর্বাভাস নেই',
  'fc.tile.accuracy': 'পূর্বাভাসের ভুল',
  'fc.tile.accuracyNone': 'এখনো মাপা হয়নি',
  'fc.col.item': 'পণ্য',
  'fc.col.confidence': 'নির্ভরযোগ্যতা',
  'fc.col.rate': 'দিনে বিক্রি',
  'fc.col.onHand': 'হাতে আছে',
  'fc.col.incoming': 'অর্ডারে আছে',
  'fc.col.lead': 'আসতে সময়',
  'fc.col.runsOut': 'ফুরাবে',
  'fc.col.suggested': 'যত আনার পরামর্শ',
  'fc.conf.HIGH': 'বেশি',
  'fc.conf.MEDIUM': 'মাঝারি',
  'fc.conf.INSUFFICIENT': 'যথেষ্ট ইতিহাস নেই',
  'fc.lead.OBSERVED': '{n}টি আসা অর্ডার থেকে',
  'fc.lead.SUPPLIER': 'সরবরাহকারীর অনুমান',
  'fc.lead.DEFAULT': 'ধরে নেওয়া',
  'fc.days': '{n} দিন',
  'fc.today': 'এখনই',
  'fc.draft': 'খসড়া অর্ডার',
  'fc.drafted': 'খসড়া {number} তৈরি হয়েছে, {quantity}টি। অর্ডার দেওয়ার আগে দেখে নিন।',
  'fc.openDraft': 'খসড়া খুলুন',
  'fc.empty': 'দেখানোর মতো কিছু নেই।',
  'fc.readOnly': 'আপনি পূর্বাভাস দেখতে পারেন। খসড়া ক্রয় আদেশ করতে কেনাকাটার অনুমতি লাগবে।',
  'fc.err.NO_PREFERRED_SUPPLIER': 'আগে এই পণ্যের পছন্দের সরবরাহকারী ঠিক করুন (কেনাকাটা → সরবরাহকারী)।',
  'fc.err.ALREADY_ON_ORDER': 'এই পণ্য আগে থেকেই খসড়া বা চলমান ক্রয় আদেশে আছে।',
  'fc.err.NO_SUGGESTION': 'এই পণ্য এখন আবার আনার দরকার নেই।',
  'fc.item.back': '← পূর্বাভাস',
  'fc.item.chart': 'দিনে কতটি বিক্রি, গত ৫৬টি পুরো দিন',
  'fc.item.legendSold': 'বিক্রি',
  'fc.item.legendOut': 'স্টক ছিল না বা তখনো তালিকায় ছিল না — গোনা হয়নি',
  'fc.item.table': 'টেবিল হিসেবে দেখুন',
  'fc.item.date': 'তারিখ',
  'fc.item.units': 'সংখ্যা',
  'fc.item.inStock': 'গোনা হয়েছে',
  'fc.item.yes': 'হ্যাঁ',
  'fc.item.no': 'না',
  'fc.how.title': 'কীভাবে হিসাব হলো',
  'fc.how.days': 'যত দিন বিক্রি করা যেত: {n} (গত {total} দিনের মধ্যে)',
  'fc.how.units': 'সেই দিনগুলোতে বিক্রি: {n}টি',
  'fc.how.recent': 'সাম্প্রতিক গড় (গত ১৪ দিন): দিনে {rate}',
  'fc.how.long': 'দীর্ঘ গড়: দিনে {rate}',
  'fc.how.rate': 'পূর্বাভাস: দুটোর অর্ধেক করে = দিনে {rate}',
  'fc.how.safety': 'অসমান বিক্রির জন্য বাড়তি মাল: {n}',
  'fc.how.reorderPoint': 'আবার অর্ডারের সীমা (আসতে সময় × দিনে বিক্রি + বাড়তি): {n}',
  'fc.how.suggested': 'যত আনার পরামর্শ (আসার সময় + {cover} দিনের জন্য, হাতে ও অর্ডারে থাকা বাদে): {n}',
  'fc.how.insufficient': 'পূর্বাভাসের জন্য অন্তত {days} দিন বিক্রি আর মোট {units}টি লাগে। তার আগে কোনো সংখ্যা দেখানো হয় না।',
  'fc.acc.title': 'পূর্বাভাস কতটা মিলেছে',
  'fc.acc.hint': 'প্রতিদিন সকালের পূর্বাভাস জমা থাকে। চার সপ্তাহ পরে আসল বিক্রির সঙ্গে মেলানো হয়।',
  'fc.acc.notEnough': 'এখনো মাপা হয়নি। অন্তত ১০টি পণ্যের জমা পূর্বাভাস মাপতে চার সপ্তাহ লাগে।',
  'fc.acc.noSales': 'মাপার সময়ে কিছু বিক্রি হয়নি, তাই ভুল মাপার কিছু নেই।',
  'fc.acc.asOf': 'পূর্বাভাস জমার তারিখ',
  'fc.acc.items': 'যত পণ্য মাপা হলো',
  'fc.acc.skipped': 'পূর্বাভাস ছাড়া পণ্য',
  'fc.acc.predicted': 'পূর্বাভাসে বিক্রি',
  'fc.acc.actual': 'আসল বিক্রি',
  'fc.acc.error': 'ভুল (বিক্রির পরিমাণ অনুযায়ী)',
  'fc.acc.over': 'পূর্বাভাস {n}টি বেশি ছিল।',
  'fc.acc.under': 'পূর্বাভাস {n}টি কম ছিল।',
  'fc.cash.title': 'টাকার হিসাবের অনুমান',
  'fc.cash.hint': 'যত COD আসার কথা আর সরবরাহকারীকে যত দিতে হবে। কুরিয়ারের পেমেন্টের ইতিহাস আর ক্রয় আদেশ থেকে অনুমান, ব্যাংকের হিসাব নয়।',
  'fc.cash.window': 'কখন',
  'fc.cash.in': 'COD আসার কথা',
  'fc.cash.out': 'সরবরাহকারীকে দিতে হবে',
  'fc.cash.overdue': 'সময় পেরিয়ে গেছে',
  'fc.cash.next7': 'আগামী ৭ দিন',
  'fc.cash.next14': '৮–১৪ দিন',
  'fc.cash.later': 'পরে',
  'fc.cash.noDate': 'তারিখ জানা নেই',
  'fc.cash.net7': 'নিট, আগামী ৭ দিন',
  'fc.cash.net14': 'নিট, আগামী ১৪ দিন',
  'fc.cash.committed': 'চলমান অর্ডারে ধরা আছে (মাল এলে দিতে হবে)',
  'fc.cash.unplaced': 'যে COD-এর আসার তারিখ এখনো জানা নেই',
  'fc.cash.noAccess': 'টাকার হিসাবের অনুমান দেখতে টাকার হিসাবের অনুমতি লাগবে।',
  'pr.f.leadTime': 'আসতে সময় (অর্ডার থেকে হাতে পাওয়া, দিন)',
};
