export const insightsEn = {
  "ins.range": "{days} days",
  "ins.vsPrev": "{change} vs previous",
  "ins.noCompare": "No earlier base to compare",
  "ins.revenue": "Delivered sales",
  "ins.profit": "Profit",
  "ins.orders": "Orders",
  "ins.delivered": "Delivered",
  "ins.rtoRate": "RTO rate",
  "ins.rtoOf": "{rto} of {completed} came back",
  "ins.received": "COD received",
  "ins.receivable": "Outstanding COD",
  "ins.overdue": "Overdue COD",
  "ins.onRoad": "COD on the road",
  "ins.overdueCaption": "{amount} overdue",
  "ins.discrepancies": "Mismatches",
  "ins.discrepancyCaption": "{amount} disagreement",
  "ins.stock": "Stock alerts",
  "ins.stockValue": "{low} low · {out} out",
  "ins.slowCaption": "{count} with no sale in {days} days",
  "ins.limited": "Limited data",
  "ins.notEnough": "Not enough data",
  "ins.missingCost": "{count} parcels without cost",
  "ins.estimated": "Includes estimates",
  "ins.moneyLockedRole": "Your role does not include money figures.",
  "ins.whatChanged": "What changed",
  "ins.whatChangedSub": "Facts from your own figures — no guesses",
  "ins.nothingChanged": "Nothing notable changed in this period.",
  "ins.trendProfit": "Profit over time",
  "ins.trendOrders": "Orders over time",
  "ins.trendSubDay": "Per day",
  "ins.trendSubWeek": "Per week",
  "ins.trendEmpty": "Nothing happened in this period yet.",
  "ins.chartLabel": "{title}: {count} periods",
  "ins.explore": "Explore",
  "ins.exploreSub": "One area at a time",
  "ins.couldNotLoad": "Could not load insights",
  "ins.profitTile": "Profit & costs",
  "ins.profitTileSub": "Revenue → profit bridge, product profit, return loss",
  "ins.profitEyebrow": "Insights",
  "ins.profitTitle": "Profit & costs",
  "ins.profitDescription": "Contribution profit over the last 30 days, and where the money goes.",
  "ins.cashTile": "Cash & COD",
  "ins.cashTileSub": "Received, outstanding, overdue, on the road",
  "ins.cashDescription": "What arrived, what couriers still hold, and what is late.",
  "ins.productsTile": "Products",
  "ins.productsTileSub": "Sales, profit, RTO and stock per product",
  "ins.productsDescription": "Per product: what sold, what it earned, what came back and what is on the shelf.",
  "ins.couriersTile": "Couriers",
  "ins.couriersTileSub": "Facts side by side — you decide",
  "ins.couriersTitle": "Courier scorecards",
  "ins.couriersDescription": "Your own parcels, courier by courier. Facts side by side — no ranking.",
  "ins.inventoryTile": "Inventory",
  "ins.inventoryTileSub": "Stock health and slow-moving items",
  "ins.inventoryDescription": "Stock health from the stock ledger. Slow-moving means stock on the shelf and no sale in {days} days.",
  "ins.customersTile": "Customers",
  "ins.customersTileSub": "New, returning and repeat customers",
  "ins.customersDescription": "Your own customers, as counts. No names, no scores.",
  "ins.parcelCount.one": "{count} parcel",
  "ins.parcelCount.other": "{count} parcels",
  "ins.aging": "How long it has waited",
  "ins.byCourier": "By courier",
  "ins.nothingOwed": "Couriers hold no COD for you right now.",
  "ins.forecast": "Expected arrival",
  "ins.forecastSub": "From each courier's own payment history — not a promise",
  "ins.estimate": "Estimate",
  "ins.fc.next_7_days": "Next 7 days",
  "ins.fc.days_8_to_14": "8–14 days",
  "ins.fc.later": "Later",
  "ins.fc.past_expected": "Past its usual date",
  "ins.fc.no_history": "No payment history yet",
  "ins.daysRange": "{min}–{max} days",
  "ins.daysOpen": "{min}+ days",
  "ins.cat.all": "All",
  "ins.cat.top_revenue": "Top sales",
  "ins.cat.top_profit": "Top profit",
  "ins.cat.high_rto": "High RTO",
  "ins.cat.low_stock": "Low stock",
  "ins.cat.out_of_stock": "Out of stock",
  "ins.cat.slow_moving": "Slow-moving",
  "ins.cat.fast_moving": "Fast-moving",
  "ins.highRtoNote": "Only products with at least {min} finished parcels are compared.",
  "ins.productRow": "{parcels} parcels · RTO {rto}",
  "ins.stockLeft": "{count} in stock",
  "ins.slowRow": "No sale in {days} days · {count} in stock",
  "ins.itemRow": "{count} in stock · {units} booked in period",
  "ins.noProfit": "Profit unknown",
  "ins.noProducts": "Nothing in this view.",
  "ins.loadMore": "Load more",
  "ins.status.OUT": "Out of stock",
  "ins.status.LOW": "Low stock",
  "ins.fact.completed": "Finished parcels",
  "ins.fact.success": "Delivered",
  "ins.fact.rto": "RTO",
  "ins.fact.inTransit": "On the road now",
  "ins.fact.stuck": "Stuck (no update)",
  "ins.fact.outstanding": "COD outstanding",
  "ins.fact.overdue": "COD overdue",
  "ins.fact.delay": "Usual payout delay",
  "ins.fact.delayValue": "{days} days",
  "ins.fact.discrepancies": "Mismatches",
  "ins.noCouriers": "No courier parcels in this period.",
  "ins.excluded": "{providers}: no live integration, not compared.",
  "ins.units": "Units in stock",
  "ins.lowItems": "Low",
  "ins.outItems": "Out",
  "ins.slowItems": "Slow-moving",
  "ins.totalCustomers": "All customers",
  "ins.activeCustomers": "Ordered in period",
  "ins.newCustomers": "New",
  "ins.returningCustomers": "Returning",
  "ins.repeatShare": "Repeat-order share",
  "ins.repeatShareCaption": "{repeat} of {orders} orders",
  "ins.repeatCustomers": "Ordered 2+ times",
  "ins.multiDelivered": "2+ delivered parcels",
  "ins.repeatRto": "2+ returned parcels",
  "ins.repeatRtoLink": "See repeat-return patterns",
  "ins.lifetime": "All time",
  "ins.why.PROFIT_CHANGED.up": "Profit rose {change} compared with the previous {days} days.",
  "ins.why.PROFIT_CHANGED.down": "Profit fell {change} compared with the previous {days} days.",
  "ins.why.PROFIT_CHANGED_WITH_RTO.up": "Profit rose {change} compared with the previous {days} days, while RTO moved from {from} to {to}.",
  "ins.why.PROFIT_CHANGED_WITH_RTO.down": "Profit fell {change} compared with the previous {days} days, while RTO moved from {from} to {to}.",
  "ins.why.REVENUE_CHANGED.up": "Delivered sales rose {change} compared with the previous {days} days.",
  "ins.why.REVENUE_CHANGED.down": "Delivered sales fell {change} compared with the previous {days} days.",
  "ins.why.ORDERS_CHANGED.up": "Orders rose {change} compared with the previous {days} days.",
  "ins.why.ORDERS_CHANGED.down": "Orders fell {change} compared with the previous {days} days.",
  "ins.why.RECEIVED_CHANGED.up": "COD received rose {change} compared with the previous {days} days.",
  "ins.why.RECEIVED_CHANGED.down": "COD received fell {change} compared with the previous {days} days.",
  "ins.why.RTO_CHANGED": "RTO moved from {from} to {to} compared with the previous {days} days.",
  "ins.why.OVERDUE_CONCENTRATED": "{share} of overdue COD ({courierAmount} of {amount}) is with {courier}.",
  "ins.why.RECEIVABLE_AGE_SHARE": "{share} of current receivables are {bucket} old.",
  "ins.why.RETURN_VALUE_CONCENTRATED": "{product} accounts for {share} of returned parcel value.",
  "ins.why.COST_DATA_INCOMPLETE": "{missing} of {parcels} parcels have no product cost, so profit is incomplete.",
  "ins.why.OPEN_CASES": "{count} reconciliation cases are open, worth {amount}.",
  "ins.why.SLOW_MOVING": "{count} items have stock but no sale in {days} days.",
  "ins.why.OUT_OF_STOCK": "{count} items are out of stock.",
  "ins.why.LOW_STOCK": "{count} items are at or below their low-stock level.",
  "ins.why.NEW_CUSTOMERS": "{count} new customers ordered in the last {days} days.",
  "ins.why.REPEAT_ORDER_SHARE": "{share} of orders in the last {days} days came from returning customers."
} as const;

export const insightsBn = {
  "ins.range": "{days} দিন",
  "ins.vsPrev": "আগের তুলনায় {change}",
  "ins.noCompare": "তুলনার মতো আগের তথ্য নেই",
  "ins.revenue": "ডেলিভারি হওয়া বিক্রি",
  "ins.profit": "লাভ",
  "ins.orders": "অর্ডার",
  "ins.delivered": "ডেলিভারি হয়েছে",
  "ins.rtoRate": "RTO হার",
  "ins.rtoOf": "{completed}টির মধ্যে {rto}টি ফেরত",
  "ins.received": "হাতে আসা COD",
  "ins.receivable": "বাকি COD",
  "ins.overdue": "মেয়াদ পেরোনো COD",
  "ins.onRoad": "পথে থাকা COD",
  "ins.overdueCaption": "{amount} মেয়াদ পেরোনো",
  "ins.discrepancies": "অমিল",
  "ins.discrepancyCaption": "{amount} অমিল",
  "ins.stock": "স্টক সতর্কতা",
  "ins.stockValue": "{low} কম · {out} শেষ",
  "ins.slowCaption": "{count}টিতে {days} দিনে বিক্রি নেই",
  "ins.limited": "তথ্য সীমিত",
  "ins.notEnough": "যথেষ্ট তথ্য নেই",
  "ins.missingCost": "{count}টি পার্সেলের খরচ নেই",
  "ins.estimated": "আনুমানিক অংশ আছে",
  "ins.moneyLockedRole": "আপনার রোলে টাকার হিসাব দেখা যায় না।",
  "ins.whatChanged": "কী বদলেছে",
  "ins.whatChangedSub": "আপনার নিজের হিসাব থেকে তথ্য — কোনো অনুমান নয়",
  "ins.nothingChanged": "এই সময়ে উল্লেখযোগ্য কিছু বদলায়নি।",
  "ins.trendProfit": "সময়ের সাথে লাভ",
  "ins.trendOrders": "সময়ের সাথে অর্ডার",
  "ins.trendSubDay": "প্রতিদিন",
  "ins.trendSubWeek": "প্রতি সপ্তাহে",
  "ins.trendEmpty": "এই সময়ে এখনো কিছু হয়নি।",
  "ins.chartLabel": "{title}: {count}টি সময়কাল",
  "ins.explore": "আরও দেখুন",
  "ins.exploreSub": "একবারে একটি বিষয়",
  "ins.couldNotLoad": "ইনসাইটস লোড করা যায়নি",
  "ins.profitTile": "লাভ ও খরচ",
  "ins.profitTileSub": "বিক্রি থেকে লাভ, পণ্যভিত্তিক লাভ, ফেরতের ক্ষতি",
  "ins.profitEyebrow": "ইনসাইটস",
  "ins.profitTitle": "লাভ ও খরচ",
  "ins.profitDescription": "গত ৩০ দিনের কন্ট্রিবিউশন লাভ, আর টাকা কোথায় যায়।",
  "ins.cashTile": "ক্যাশ ও COD",
  "ins.cashTileSub": "হাতে এসেছে, বাকি, মেয়াদ পেরোনো, পথে",
  "ins.cashDescription": "কী হাতে এসেছে, কুরিয়ারের কাছে কত আছে, আর কোনটা দেরি হচ্ছে।",
  "ins.productsTile": "পণ্য",
  "ins.productsTileSub": "পণ্যভিত্তিক বিক্রি, লাভ, RTO ও স্টক",
  "ins.productsDescription": "প্রতিটি পণ্যের বিক্রি, আয়, ফেরত আর তাকে থাকা স্টক।",
  "ins.couriersTile": "কুরিয়ার",
  "ins.couriersTileSub": "পাশাপাশি তথ্য — সিদ্ধান্ত আপনার",
  "ins.couriersTitle": "কুরিয়ার স্কোরকার্ড",
  "ins.couriersDescription": "আপনার নিজের পার্সেল, কুরিয়ার অনুযায়ী। পাশাপাশি তথ্য — কোনো র‍্যাঙ্কিং নয়।",
  "ins.inventoryTile": "ইনভেন্টরি",
  "ins.inventoryTileSub": "স্টকের অবস্থা ও ধীরে বিক্রি হওয়া আইটেম",
  "ins.inventoryDescription": "স্টক লেজার থেকে স্টকের অবস্থা। ধীরে বিক্রি মানে স্টক আছে কিন্তু {days} দিনে কোনো বিক্রি নেই।",
  "ins.customersTile": "কাস্টমার",
  "ins.customersTileSub": "নতুন, ফিরে আসা ও বারবার অর্ডার করা কাস্টমার",
  "ins.customersDescription": "আপনার নিজের কাস্টমার, শুধু সংখ্যায়। নাম বা স্কোর নয়।",
  "ins.parcelCount.one": "{count}টি পার্সেল",
  "ins.parcelCount.other": "{count}টি পার্সেল",
  "ins.aging": "কত দিন ধরে বাকি",
  "ins.byCourier": "কুরিয়ার অনুযায়ী",
  "ins.nothingOwed": "এখন কোনো কুরিয়ারের কাছে আপনার COD বাকি নেই।",
  "ins.forecast": "সম্ভাব্য আসার সময়",
  "ins.forecastSub": "প্রতিটি কুরিয়ারের নিজের পেমেন্ট ইতিহাস থেকে — নিশ্চিত নয়",
  "ins.estimate": "অনুমান",
  "ins.fc.next_7_days": "আগামী ৭ দিন",
  "ins.fc.days_8_to_14": "৮–১৪ দিন",
  "ins.fc.later": "পরে",
  "ins.fc.past_expected": "স্বাভাবিক সময় পেরিয়ে গেছে",
  "ins.fc.no_history": "এখনো পেমেন্টের ইতিহাস নেই",
  "ins.daysRange": "{min}–{max} দিন",
  "ins.daysOpen": "{min}+ দিন",
  "ins.cat.all": "সব",
  "ins.cat.top_revenue": "সর্বোচ্চ বিক্রি",
  "ins.cat.top_profit": "সর্বোচ্চ লাভ",
  "ins.cat.high_rto": "বেশি RTO",
  "ins.cat.low_stock": "কম স্টক",
  "ins.cat.out_of_stock": "স্টক শেষ",
  "ins.cat.slow_moving": "ধীরে বিক্রি",
  "ins.cat.fast_moving": "দ্রুত বিক্রি",
  "ins.highRtoNote": "কমপক্ষে {min}টি পার্সেল শেষ হওয়া পণ্যই শুধু তুলনা করা হয়।",
  "ins.productRow": "{parcels}টি পার্সেল · RTO {rto}",
  "ins.stockLeft": "স্টকে {count}",
  "ins.slowRow": "{days} দিনে বিক্রি নেই · স্টকে {count}",
  "ins.itemRow": "স্টকে {count} · এই সময়ে বুক {units}",
  "ins.noProfit": "লাভ অজানা",
  "ins.noProducts": "এই তালিকায় কিছু নেই।",
  "ins.loadMore": "আরও দেখুন",
  "ins.status.OUT": "স্টক শেষ",
  "ins.status.LOW": "স্টক কম",
  "ins.fact.completed": "শেষ হওয়া পার্সেল",
  "ins.fact.success": "ডেলিভারি সফল",
  "ins.fact.rto": "RTO",
  "ins.fact.inTransit": "এখন পথে",
  "ins.fact.stuck": "আটকে আছে (আপডেট নেই)",
  "ins.fact.outstanding": "বাকি COD",
  "ins.fact.overdue": "মেয়াদ পেরোনো COD",
  "ins.fact.delay": "সাধারণত পেমেন্টে দেরি",
  "ins.fact.delayValue": "{days} দিন",
  "ins.fact.discrepancies": "অমিল",
  "ins.noCouriers": "এই সময়ে কোনো কুরিয়ার পার্সেল নেই।",
  "ins.excluded": "{providers}: লাইভ ইন্টিগ্রেশন নেই, তুলনা করা হয়নি।",
  "ins.units": "স্টকে মোট ইউনিট",
  "ins.lowItems": "কম",
  "ins.outItems": "শেষ",
  "ins.slowItems": "ধীরে বিক্রি",
  "ins.totalCustomers": "মোট কাস্টমার",
  "ins.activeCustomers": "এই সময়ে অর্ডার করেছেন",
  "ins.newCustomers": "নতুন",
  "ins.returningCustomers": "ফিরে এসেছেন",
  "ins.repeatShare": "আবার অর্ডারের অংশ",
  "ins.repeatShareCaption": "{orders}টি অর্ডারের মধ্যে {repeat}টি",
  "ins.repeatCustomers": "২+ বার অর্ডার করেছেন",
  "ins.multiDelivered": "২+ পার্সেল ডেলিভারি হয়েছে",
  "ins.repeatRto": "২+ পার্সেল ফেরত এসেছে",
  "ins.repeatRtoLink": "বারবার ফেরতের ধরন দেখুন",
  "ins.lifetime": "সব সময়ের",
  "ins.why.PROFIT_CHANGED.up": "আগের {days} দিনের তুলনায় লাভ {change} বেড়েছে।",
  "ins.why.PROFIT_CHANGED.down": "আগের {days} দিনের তুলনায় লাভ {change} কমেছে।",
  "ins.why.PROFIT_CHANGED_WITH_RTO.up": "আগের {days} দিনের তুলনায় লাভ {change} বেড়েছে, আর RTO {from} থেকে {to} হয়েছে।",
  "ins.why.PROFIT_CHANGED_WITH_RTO.down": "আগের {days} দিনের তুলনায় লাভ {change} কমেছে, আর RTO {from} থেকে {to} হয়েছে।",
  "ins.why.REVENUE_CHANGED.up": "আগের {days} দিনের তুলনায় ডেলিভারি হওয়া বিক্রি {change} বেড়েছে।",
  "ins.why.REVENUE_CHANGED.down": "আগের {days} দিনের তুলনায় ডেলিভারি হওয়া বিক্রি {change} কমেছে।",
  "ins.why.ORDERS_CHANGED.up": "আগের {days} দিনের তুলনায় অর্ডার {change} বেড়েছে।",
  "ins.why.ORDERS_CHANGED.down": "আগের {days} দিনের তুলনায় অর্ডার {change} কমেছে।",
  "ins.why.RECEIVED_CHANGED.up": "আগের {days} দিনের তুলনায় হাতে আসা COD {change} বেড়েছে।",
  "ins.why.RECEIVED_CHANGED.down": "আগের {days} দিনের তুলনায় হাতে আসা COD {change} কমেছে।",
  "ins.why.RTO_CHANGED": "আগের {days} দিনের তুলনায় RTO {from} থেকে {to} হয়েছে।",
  "ins.why.OVERDUE_CONCENTRATED": "মেয়াদ পেরোনো COD-এর {share} ({amount}-এর মধ্যে {courierAmount}) {courier}-এর কাছে।",
  "ins.why.RECEIVABLE_AGE_SHARE": "এখন পাওনা টাকার {share} {bucket} পুরনো।",
  "ins.why.RETURN_VALUE_CONCENTRATED": "ফেরত আসা পার্সেলের মূল্যের {share} {product}-এর।",
  "ins.why.COST_DATA_INCOMPLETE": "{parcels}টি পার্সেলের মধ্যে {missing}টির পণ্যের খরচ নেই, তাই লাভের হিসাব অসম্পূর্ণ।",
  "ins.why.OPEN_CASES": "{count}টি রিকনসিলিয়েশন কেস খোলা আছে, মোট {amount}।",
  "ins.why.SLOW_MOVING": "{count}টি আইটেমে স্টক আছে কিন্তু {days} দিনে কোনো বিক্রি নেই।",
  "ins.why.OUT_OF_STOCK": "{count}টি আইটেমের স্টক শেষ।",
  "ins.why.LOW_STOCK": "{count}টি আইটেম লো-স্টক সীমায় বা তার নিচে।",
  "ins.why.NEW_CUSTOMERS": "গত {days} দিনে {count} জন নতুন কাস্টমার অর্ডার করেছেন।",
  "ins.why.REPEAT_ORDER_SHARE": "গত {days} দিনের অর্ডারের {share} এসেছে আগের কাস্টমারদের কাছ থেকে।"
} as const;
