/**
 * Integrations Hub copy. Provider names, API, HTTPS and webhook stay English in
 * Bangla too, the way sellers in Bangladesh say them.
 */
export const integrationsEn = {
  'nav.integrations': 'Integrations',
  'int.title': 'Integrations',
  'int.subtitle': 'Connect your store, website and Page. New orders arrive here on their own.',
  'int.add': 'Add integration',
  'int.addTitle': 'Add an integration',
  'int.choose': 'Where do your orders come from?',
  'int.name': 'Connection name',
  'int.create': 'Continue',
  'int.provider.SHOPIFY': 'Shopify',
  'int.provider.WOOCOMMERCE': 'WooCommerce',
  'int.provider.CUSTOM_WEBSITE': 'Custom website',
  'int.provider.MESSENGER': 'Messenger',
  'int.provider.WHATSAPP': 'WhatsApp Business',
  'int.about.SHOPIFY': 'Orders from your Shopify store arrive automatically.',
  'int.about.WOOCOMMERCE': 'Orders from your WordPress + WooCommerce store arrive automatically.',
  'int.about.CUSTOM_WEBSITE': 'Your own website sends orders with a secure API key.',
  'int.about.MESSENGER': 'Link your Facebook Page and watch the connection health.',
  'int.about.WHATSAPP': 'Connect WhatsApp Business. Customer messages arrive as draft orders in your Inbox.',
  'int.health.CONNECTED': 'Connected',
  'int.health.DEGRADED': 'Needs attention',
  'int.health.WEBHOOK_FAILING': 'Webhook failing',
  'int.health.SYNC_FAILING': 'Sync error',
  'int.health.AUTH_EXPIRED': 'Sign-in expired',
  'int.health.DISCONNECTED': 'Disconnected',
  'int.health.DISABLED': 'Turned off',
  'int.health.SETUP_INCOMPLETE': 'Setup not finished',
  'int.health.NOT_CONNECTED': 'Not connected',
  'int.health.OFFICIAL_SETUP_REQUIRED': 'Official setup required',
  'int.blocker.SHOPIFY_APP_SETUP_REQUIRED':
    'The ecomsbd Shopify app is waiting for Shopify’s official approval. You can connect once it is live.',
  'int.blocker.META_APP_SETUP_REQUIRED':
    'Meta connection setup is temporarily unavailable. ecomsbd configuration is incomplete.',
  'int.blocker.META_APPROVAL_REQUIRED':
    'Public WhatsApp signup needs Meta approval for ecomsbd. Please try again after approval.',
  'int.blocker.CHANNEL_DISABLED': 'Turn on customer email in Messaging first.',
  'int.tile.connected': 'Connected',
  'int.tile.ordersToday': 'Orders received today',
  'int.tile.issues': 'Problems to fix',
  'int.tile.failedToday': 'Failed today',
  'int.col.connection': 'Connection',
  'int.col.status': 'Status',
  'int.col.ordersToday': 'Orders today',
  'int.col.lastSync': 'Last sync',
  'int.col.lastWebhook': 'Last instant update',
  'int.col.issues': 'Problems',
  'int.col.when': 'When',
  'int.col.problem': 'Problem',
  'int.col.order': 'Store order',
  'int.col.state': 'State',
  'int.col.action': 'Action',
  'int.col.kind': 'Type',
  'int.col.result': 'Result',
  'int.lastSuccess': 'Last successful contact',
  'int.lastWebhook': 'Last instant update',
  'int.lastSync': 'Last sync',
  'int.lastError': 'Latest problem',
  'int.webhookState': 'Instant updates',
  'int.webhook.ACTIVE': 'Working',
  'int.webhook.FAILING': 'Failing',
  'int.webhook.NOT_REGISTERED': 'Off — checked every 15 minutes instead',
  'int.never': 'Never',
  'int.none': 'None',
  'int.empty': 'No integrations yet',
  'int.emptyHint': 'Add your store or website and new orders will come in by themselves.',
  'int.open': 'Open',
  'int.issues.title': 'Problems to fix',
  'int.issues.hint': 'Orders that could not come in, and connections that need you.',
  'int.issues.empty': 'Nothing needs your attention.',
  'int.issues.resolved': 'Resolved',
  'int.retry': 'Try again',
  'int.resolve': 'Mark as handled',
  'int.reconnect': 'Reconnect',
  'int.queued': 'Queued — it will run in a few seconds.',
  'int.times': '{count} times',
  'int.status.QUEUED': 'Waiting',
  'int.status.PROCESSED': 'Imported',
  'int.status.IGNORED': 'Skipped',
  'int.status.FAILED': 'Needs attention',
  'int.status.RESOLVED': 'Resolved',
  'int.code.MISSING_PHONE': 'The order has no phone number',
  'int.code.INVALID_PHONE': 'The phone number is not a valid Bangladeshi mobile number',
  'int.code.NO_ITEMS': 'The order has no products',
  'int.code.CURRENCY_NOT_BDT': 'The store does not use Taka (BDT)',
  'int.code.ORDER_REJECTED_BY_MAPPING': 'Some order details could not be read',
  'int.code.CUSTOMER_BLOCKED': 'This customer is blocked in your shop',
  'int.code.ORDER_LIMIT_REACHED': 'Your plan’s monthly order limit is reached',
  'int.code.CONNECTION_NOT_ACTIVE': 'The connection was off when this arrived',
  'int.code.AUTH_EXPIRED': 'The store sign-in expired',
  'int.code.PERMISSION_MISSING': 'The store did not give ecomsbd permission',
  'int.code.NOT_FOUND_AT_PROVIDER': 'The store no longer has this order',
  'int.code.PROVIDER_TIMEOUT': 'The store took too long to answer',
  'int.code.PROVIDER_UNAVAILABLE': 'The store could not be reached',
  'int.code.PROVIDER_RATE_LIMITED': 'The store asked us to slow down',
  'int.code.PROVIDER_REJECTED': 'The store refused the request',
  'int.code.STORE_UNREACHABLE': 'The store address could not be reached safely',
  'int.code.STORE_REDIRECTED': 'The store address redirects; use the final HTTPS address',
  'int.code.MALFORMED_RESPONSE': 'The store sent an unexpected answer',
  'int.code.MALFORMED_PAYLOAD': 'An update from the store could not be read',
  'int.code.SIGNATURE_INVALID': 'An update failed the security check and was refused',
  'int.code.WEBHOOK_REGISTRATION_FAILED': 'Instant updates could not be switched on',
  'int.code.APP_UNINSTALLED': 'The ecomsbd app was removed from the store',
  'int.code.ORDER_CANCELLED_AT_PROVIDER': 'Cancelled in the store after it came to ecomsbd',
  'int.code.DUPLICATE_IGNORED': 'Already here — not added twice',
  'int.code.COALESCED': 'Covered by another update',
  'int.code.ORDER_NOT_READY': 'Not paid or confirmed yet',
  'int.code.CUSTOMER_DATA_REQUEST': 'A customer asked Shopify for their data',
  'int.code.CUSTOMER_REDACT_REQUEST': 'A customer asked Shopify to delete their data',
  'int.code.API_KEY_REVOKED': 'The website’s API key was revoked',
  'int.code.ACCOUNT_MISMATCH': 'This is a different store from the one connected before',
  'int.code.ALREADY_LINKED': 'This store is already connected to another ecomsbd shop',
  'int.code.STATE_INVALID': 'The sign-in link expired. Start again.',
  'int.code.ACCESS_DENIED': 'Permission was not given',
  'int.code.NO_PAGES': 'No Facebook Page was shared',
  'int.code.SELECT_PAGE': 'Choose which Page to connect',
  'int.code.CONNECTED': 'Connected successfully',
  'int.code.WINDOW_TOO_LONG': 'That period is longer than the store allows',
  'int.code.SYNC_ALREADY_RUNNING': 'An import is already running',
  'int.code.RECONNECT_REQUIRED': 'Reconnect the store first',
  'int.code.NOT_RETRYABLE': 'This one cannot be retried',
  'int.code.WEBHOOK_NOT_SET': 'Add your webhook address first',
  'int.code.STORE_URL_INVALID': 'Enter the store’s public HTTPS address',
  'int.code.SHOPIFY_DOMAIN_INVALID': 'Enter your store’s myshopify.com address',
  'int.code.woocommerce': 'Back from WooCommerce. Checking the keys…',
  'int.step.connect': 'Connect',
  'int.step.verify': 'Verify account',
  'int.step.configure': 'Configure',
  'int.step.test': 'Test',
  'int.step.sync': 'Past orders',
  'int.step.automate': 'Automation',
  'int.step.live': 'Go live',
  'int.shopDomain': 'Shopify store address',
  'int.shopHint': 'For example mystore.myshopify.com',
  'int.storeUrl': 'Store address',
  'int.storeHint': 'For example https://mystore.com — it must use HTTPS',
  'int.connectShopify': 'Continue to Shopify',
  'int.connectWoo': 'Continue to WooCommerce',
  'int.connectMeta': 'Continue with Facebook',
  'int.wa.phoneId': 'Phone number ID',
  'int.wa.wabaId': 'WhatsApp Business Account ID',
  'int.wa.token': 'Access token (system user)',
  'int.wa.hint': 'From Meta Business Manager → WhatsApp Manager → API setup. The token is stored encrypted and never shown again.',
  'int.wa.link': 'Connect with WhatsApp',
  'int.wa.syncTemplates': 'Check template approvals',
  'int.wa.synced': '{count} templates checked with Meta',
  'int.wa.note': 'Only templates Meta has approved are sent. Meta bills marketing templates to your WhatsApp Business Account.',
  'int.redirecting': 'Opening the sign-in page…',
  'int.manualKeys': 'Enter WooCommerce API keys instead',
  'int.manualHint':
    'In WordPress open WooCommerce → Settings → Advanced → REST API → Add key. Choose Read/Write, then paste both keys here.',
  'int.consumerKey': 'Consumer key',
  'int.consumerSecret': 'Consumer secret',
  'int.saveKeys': 'Check and save keys',
  'int.test': 'Test connection',
  'int.testing': 'Checking…',
  'int.testOk': 'Everything works.',
  'int.testFailed': 'Something needs fixing.',
  'int.check.AUTH': 'Signed in to the store',
  'int.check.WEBHOOKS': 'The store sends new orders instantly',
  'int.check.API_KEY': 'API key is active',
  'int.check.FIRST_REQUEST': 'Your website reached ecomsbd',
  'int.check.FIRST_ORDER': 'First order received',
  'int.check.WEBHOOK': 'Your website received our test event',
  'int.enable': 'Turn on',
  'int.disable': 'Turn off',
  'int.disconnect': 'Disconnect',
  'int.disconnectConfirm': 'Disconnect? New orders stop coming in. Orders already here stay.',
  'int.disconnectedHint': 'For a store, also remove the ecomsbd app or API key from the store’s own settings.',
  'int.rename': 'Rename',
  'int.save': 'Save',
  'int.importFrom': 'New orders placed after {date} come in automatically.',
  'int.sync.title': 'Import past orders',
  'int.sync.hint': 'Choose how far back to import. Nothing older is imported, and nothing is added twice.',
  'int.sync.days': 'Last {days} days',
  'int.sync.maxDays': 'Up to {days} days back',
  'int.sync.start': 'Start import',
  'int.sync.cancel': 'Stop import',
  'int.sync.history': 'Sync history',
  'int.sync.none': 'No imports yet.',
  'int.sync.kind.INITIAL': 'Past orders',
  'int.sync.kind.INCREMENTAL': 'Catch-up check',
  'int.sync.status.QUEUED': 'Waiting',
  'int.sync.status.RUNNING': 'Importing',
  'int.sync.status.COMPLETED': 'Done',
  'int.sync.status.FAILED': 'Failed',
  'int.sync.status.CANCELLED': 'Stopped',
  'int.sync.counts': '{imported} imported · {duplicates} already here · {skipped} skipped · {failed} need attention',
  'int.sync.of': '{done} of {total}',
  'int.sync.pages': '{pages} pages read',
  'int.events.title': 'Recent activity',
  'int.dev.title': 'Developer setup',
  'int.dev.hint': 'Everything your developer needs. Nothing here gives access to your ecomsbd account.',
  'int.dev.apiBase': 'API base URL',
  'int.dev.ordersEndpoint': 'Create-order address',
  'int.dev.sourceId': 'Connection ID',
  'int.dev.scopes': 'Permissions',
  'int.dev.key': 'API key',
  'int.dev.keyOnce': 'Copy this API key now. It is shown only once and cannot be seen again.',
  'int.dev.secretOnce': 'Copy this signing secret now. It is shown only once.',
  'int.dev.saved': 'I have saved it',
  'int.dev.copy': 'Copy',
  'int.dev.copied': 'Copied',
  'int.dev.rotate': 'Replace API key',
  'int.dev.rotateConfirm': 'The current key stops working right away. Update your website with the new one. Continue?',
  'int.dev.keyActive': 'Active since {date}',
  'int.dev.keyRevoked': 'Revoked — replace it to reconnect',
  'int.dev.lastCall': 'Last request from your website',
  'int.dev.lastOrder': 'Last order received',
  'int.dev.waitingRequest': 'Waiting for the first request…',
  'int.dev.waitingOrder': 'Place a test order on your website.',
  'int.dev.webhookUrl': 'Your website’s webhook address (HTTPS)',
  'int.dev.saveWebhook': 'Save webhook',
  'int.dev.replaceWebhook': 'Replace webhook',
  'int.dev.sendTest': 'Send test event',
  'int.dev.testQueued': 'Test event queued. Refresh in a few seconds.',
  'int.dev.deliveries': '{failed} failed deliveries in the last 24 hours',
  'int.dev.lastDelivery': 'Last delivery',
  'int.dev.quickstart': 'Quick start',
  'int.dev.quickHint':
    'Keep the API key on your server. Never put it in browser JavaScript or a mobile app. Send one Idempotency-Key per website order so a retry never makes a second order.',
  'int.dev.part.create': 'Create an order',
  'int.dev.part.verify': 'Verify a webhook',
  'int.dev.part.status': 'Read order status',
  'int.goLive': 'Go live',
  'int.live': 'Live',
  'int.recipes.title': 'Suggested automation',
  'int.recipes.hint': 'Rules from your existing automation, ready to switch on for these orders.',
  'int.recipes.use': 'Turn on',
  'int.recipes.on': 'On',
  'int.pages.title': 'Choose your Facebook Page',
  'int.pages.use': 'Connect this Page',
  'int.messengerNote':
    'ecomsbd watches that the Page connection stays healthy. Messages stay in Messenger.',
  'int.setup.title': 'Official setup required',
  'int.back': 'All integrations',
} as const;

export const integrationsBn: Record<keyof typeof integrationsEn, string> = {
  'nav.integrations': 'ইন্টিগ্রেশন',
  'int.title': 'ইন্টিগ্রেশন',
  'int.subtitle': 'স্টোর, ওয়েবসাইট ও পেজ যুক্ত করুন। নতুন অর্ডার নিজে থেকেই এখানে চলে আসবে।',
  'int.add': 'ইন্টিগ্রেশন যোগ করুন',
  'int.addTitle': 'নতুন ইন্টিগ্রেশন',
  'int.choose': 'আপনার অর্ডার কোথা থেকে আসে?',
  'int.name': 'সংযোগের নাম',
  'int.create': 'এগিয়ে যান',
  'int.provider.SHOPIFY': 'Shopify',
  'int.provider.WOOCOMMERCE': 'WooCommerce',
  'int.provider.CUSTOM_WEBSITE': 'নিজস্ব ওয়েবসাইট',
  'int.provider.MESSENGER': 'Messenger',
  'int.provider.WHATSAPP': 'WhatsApp Business',
  'int.about.SHOPIFY': 'Shopify স্টোরের অর্ডার নিজে থেকেই চলে আসবে।',
  'int.about.WOOCOMMERCE': 'WordPress + WooCommerce স্টোরের অর্ডার নিজে থেকেই চলে আসবে।',
  'int.about.CUSTOM_WEBSITE': 'আপনার নিজের ওয়েবসাইট নিরাপদ API কী দিয়ে অর্ডার পাঠাবে।',
  'int.about.MESSENGER': 'ফেসবুক পেজ যুক্ত করুন, সংযোগ ঠিক আছে কি না দেখুন।',
  'int.about.WHATSAPP': 'আপনার WhatsApp Business অ্যাকাউন্ট যুক্ত করুন। Customer message থেকে order information ecomsbd Inbox-এ draft হিসেবে আসবে।',
  'int.health.CONNECTED': 'সংযুক্ত',
  'int.health.DEGRADED': 'মনোযোগ দরকার',
  'int.health.WEBHOOK_FAILING': 'ওয়েবহুক কাজ করছে না',
  'int.health.SYNC_FAILING': 'সিঙ্কে সমস্যা',
  'int.health.AUTH_EXPIRED': 'লগইনের মেয়াদ শেষ',
  'int.health.DISCONNECTED': 'সংযোগ বিচ্ছিন্ন',
  'int.health.DISABLED': 'বন্ধ রাখা',
  'int.health.SETUP_INCOMPLETE': 'সেটআপ বাকি',
  'int.health.NOT_CONNECTED': 'সংযুক্ত নয়',
  'int.health.OFFICIAL_SETUP_REQUIRED': 'অফিশিয়াল সেটআপ প্রয়োজন',
  'int.blocker.SHOPIFY_APP_SETUP_REQUIRED':
    'ecomsbd-এর Shopify অ্যাপ Shopify-এর অফিশিয়াল অনুমোদনের অপেক্ষায়। অনুমোদন পেলেই যুক্ত করতে পারবেন।',
  'int.blocker.META_APP_SETUP_REQUIRED':
    'Meta সংযোগ সাময়িকভাবে অনুপলব্ধ। ecomsbd-এর সেটআপ এখনো সম্পূর্ণ হয়নি।',
  'int.blocker.META_APPROVAL_REQUIRED':
    'সবার জন্য WhatsApp সংযোগ চালু করতে ecomsbd-এর Meta অনুমোদন প্রয়োজন।',
  'int.blocker.CHANNEL_DISABLED': 'আগে মেসেজিং থেকে গ্রাহকের ইমেইল চালু করুন।',
  'int.tile.connected': 'সংযুক্ত',
  'int.tile.ordersToday': 'আজ আসা অর্ডার',
  'int.tile.issues': 'যে সমস্যা ঠিক করতে হবে',
  'int.tile.failedToday': 'আজ ব্যর্থ',
  'int.col.connection': 'সংযোগ',
  'int.col.status': 'অবস্থা',
  'int.col.ordersToday': 'আজকের অর্ডার',
  'int.col.lastSync': 'শেষ সিঙ্ক',
  'int.col.lastWebhook': 'শেষ তাৎক্ষণিক আপডেট',
  'int.col.issues': 'সমস্যা',
  'int.col.when': 'কখন',
  'int.col.problem': 'সমস্যা',
  'int.col.order': 'স্টোরের অর্ডার',
  'int.col.state': 'অবস্থা',
  'int.col.action': 'করণীয়',
  'int.col.kind': 'ধরন',
  'int.col.result': 'ফলাফল',
  'int.lastSuccess': 'শেষ সফল যোগাযোগ',
  'int.lastWebhook': 'শেষ তাৎক্ষণিক আপডেট',
  'int.lastSync': 'শেষ সিঙ্ক',
  'int.lastError': 'সর্বশেষ সমস্যা',
  'int.webhookState': 'তাৎক্ষণিক আপডেট',
  'int.webhook.ACTIVE': 'চালু আছে',
  'int.webhook.FAILING': 'কাজ করছে না',
  'int.webhook.NOT_REGISTERED': 'বন্ধ — এর বদলে প্রতি ১৫ মিনিটে দেখা হয়',
  'int.never': 'কখনো নয়',
  'int.none': 'নেই',
  'int.empty': 'এখনো কোনো ইন্টিগ্রেশন নেই',
  'int.emptyHint': 'স্টোর বা ওয়েবসাইট যুক্ত করুন, নতুন অর্ডার নিজে থেকেই আসবে।',
  'int.open': 'খুলুন',
  'int.issues.title': 'যে সমস্যা ঠিক করতে হবে',
  'int.issues.hint': 'যে অর্ডার আসতে পারেনি, আর যে সংযোগে আপনার হাত দরকার।',
  'int.issues.empty': 'এখন কিছু করার নেই।',
  'int.issues.resolved': 'সমাধান হয়েছে',
  'int.retry': 'আবার চেষ্টা করুন',
  'int.resolve': 'সামলে নিয়েছি',
  'int.reconnect': 'আবার যুক্ত করুন',
  'int.queued': 'লাইনে আছে — কয়েক সেকেন্ডের মধ্যে চলবে।',
  'int.times': '{count} বার',
  'int.status.QUEUED': 'অপেক্ষায়',
  'int.status.PROCESSED': 'এসেছে',
  'int.status.IGNORED': 'বাদ দেওয়া',
  'int.status.FAILED': 'মনোযোগ দরকার',
  'int.status.RESOLVED': 'সমাধান হয়েছে',
  'int.code.MISSING_PHONE': 'অর্ডারে ফোন নম্বর নেই',
  'int.code.INVALID_PHONE': 'ফোন নম্বরটি সঠিক বাংলাদেশি মোবাইল নম্বর নয়',
  'int.code.NO_ITEMS': 'অর্ডারে কোনো পণ্য নেই',
  'int.code.CURRENCY_NOT_BDT': 'স্টোরটি টাকায় (BDT) চলে না',
  'int.code.ORDER_REJECTED_BY_MAPPING': 'অর্ডারের কিছু তথ্য পড়া যায়নি',
  'int.code.CUSTOMER_BLOCKED': 'এই গ্রাহক আপনার শপে ব্লক করা',
  'int.code.ORDER_LIMIT_REACHED': 'প্ল্যানের মাসিক অর্ডার সীমা শেষ',
  'int.code.CONNECTION_NOT_ACTIVE': 'এটি আসার সময় সংযোগ বন্ধ ছিল',
  'int.code.AUTH_EXPIRED': 'স্টোরের লগইনের মেয়াদ শেষ',
  'int.code.PERMISSION_MISSING': 'স্টোর ecomsbd-কে অনুমতি দেয়নি',
  'int.code.NOT_FOUND_AT_PROVIDER': 'স্টোরে এই অর্ডারটি আর নেই',
  'int.code.PROVIDER_TIMEOUT': 'স্টোর উত্তর দিতে বেশি সময় নিয়েছে',
  'int.code.PROVIDER_UNAVAILABLE': 'স্টোরে পৌঁছানো যায়নি',
  'int.code.PROVIDER_RATE_LIMITED': 'স্টোর একটু ধীরে চাইতে বলেছে',
  'int.code.PROVIDER_REJECTED': 'স্টোর অনুরোধটি ফিরিয়ে দিয়েছে',
  'int.code.STORE_UNREACHABLE': 'স্টোরের ঠিকানায় নিরাপদে পৌঁছানো যায়নি',
  'int.code.STORE_REDIRECTED': 'স্টোরের ঠিকানা অন্য জায়গায় নিয়ে যায়; শেষের HTTPS ঠিকানাটি দিন',
  'int.code.MALFORMED_RESPONSE': 'স্টোর অপ্রত্যাশিত উত্তর দিয়েছে',
  'int.code.MALFORMED_PAYLOAD': 'স্টোরের একটি আপডেট পড়া যায়নি',
  'int.code.SIGNATURE_INVALID': 'একটি আপডেট নিরাপত্তা যাচাইয়ে টেকেনি, তাই নেওয়া হয়নি',
  'int.code.WEBHOOK_REGISTRATION_FAILED': 'তাৎক্ষণিক আপডেট চালু করা যায়নি',
  'int.code.APP_UNINSTALLED': 'স্টোর থেকে ecomsbd অ্যাপ সরিয়ে ফেলা হয়েছে',
  'int.code.ORDER_CANCELLED_AT_PROVIDER': 'ecomsbd-এ আসার পর স্টোরে বাতিল হয়েছে',
  'int.code.DUPLICATE_IGNORED': 'আগেই এসেছে — দুবার যোগ হয়নি',
  'int.code.COALESCED': 'অন্য আপডেটে সামলানো হয়েছে',
  'int.code.ORDER_NOT_READY': 'এখনো পেমেন্ট বা কনফার্ম হয়নি',
  'int.code.CUSTOMER_DATA_REQUEST': 'একজন গ্রাহক Shopify-এর কাছে তাঁর তথ্য চেয়েছেন',
  'int.code.CUSTOMER_REDACT_REQUEST': 'একজন গ্রাহক Shopify-কে তাঁর তথ্য মুছতে বলেছেন',
  'int.code.API_KEY_REVOKED': 'ওয়েবসাইটের API কী বাতিল হয়েছে',
  'int.code.ACCOUNT_MISMATCH': 'আগে যুক্ত করা স্টোর থেকে এটি আলাদা স্টোর',
  'int.code.ALREADY_LINKED': 'এই স্টোর অন্য একটি ecomsbd শপে যুক্ত আছে',
  'int.code.STATE_INVALID': 'লগইন লিংকের মেয়াদ শেষ। আবার শুরু করুন।',
  'int.code.ACCESS_DENIED': 'অনুমতি দেওয়া হয়নি',
  'int.code.NO_PAGES': 'কোনো ফেসবুক পেজ শেয়ার করা হয়নি',
  'int.code.SELECT_PAGE': 'কোন পেজ যুক্ত করবেন বেছে নিন',
  'int.code.CONNECTED': 'সফলভাবে যুক্ত হয়েছে',
  'int.code.WINDOW_TOO_LONG': 'স্টোর এত পেছনের অর্ডার দেয় না',
  'int.code.SYNC_ALREADY_RUNNING': 'একটি ইমপোর্ট আগে থেকেই চলছে',
  'int.code.RECONNECT_REQUIRED': 'আগে স্টোরটি আবার যুক্ত করুন',
  'int.code.NOT_RETRYABLE': 'এটি আবার চেষ্টা করা যায় না',
  'int.code.WEBHOOK_NOT_SET': 'আগে ওয়েবহুক ঠিকানা দিন',
  'int.code.STORE_URL_INVALID': 'স্টোরের পাবলিক HTTPS ঠিকানা দিন',
  'int.code.SHOPIFY_DOMAIN_INVALID': 'স্টোরের myshopify.com ঠিকানা দিন',
  'int.code.woocommerce': 'WooCommerce থেকে ফিরে এসেছেন। কী যাচাই হচ্ছে…',
  'int.step.connect': 'সংযোগ',
  'int.step.verify': 'অ্যাকাউন্ট যাচাই',
  'int.step.configure': 'সেটিংস',
  'int.step.test': 'পরীক্ষা',
  'int.step.sync': 'পুরোনো অর্ডার',
  'int.step.automate': 'অটোমেশন',
  'int.step.live': 'চালু করুন',
  'int.shopDomain': 'Shopify স্টোরের ঠিকানা',
  'int.shopHint': 'যেমন mystore.myshopify.com',
  'int.storeUrl': 'স্টোরের ঠিকানা',
  'int.storeHint': 'যেমন https://mystore.com — অবশ্যই HTTPS হতে হবে',
  'int.connectShopify': 'Shopify-তে যান',
  'int.connectWoo': 'WooCommerce-এ যান',
  'int.connectMeta': 'Facebook দিয়ে এগিয়ে যান',
  'int.wa.phoneId': 'Phone number ID',
  'int.wa.wabaId': 'WhatsApp Business Account ID',
  'int.wa.token': 'Access token (system user)',
  'int.wa.hint': 'Meta Business Manager → WhatsApp Manager → API setup থেকে নিন। টোকেন এনক্রিপ্ট করে রাখা হয়, আর দেখানো হয় না।',
  'int.wa.link': 'WhatsApp দিয়ে যুক্ত করুন',
  'int.wa.syncTemplates': 'টেমপ্লেট অনুমোদন যাচাই',
  'int.wa.synced': 'Meta থেকে {count}টি টেমপ্লেট যাচাই হয়েছে',
  'int.wa.note': 'শুধু Meta-অনুমোদিত টেমপ্লেট পাঠানো হয়। মার্কেটিং টেমপ্লেটের খরচ Meta আপনার WhatsApp Business অ্যাকাউন্টে নেয়।',
  'int.redirecting': 'লগইন পেজ খোলা হচ্ছে…',
  'int.manualKeys': 'এর বদলে WooCommerce API কী দিন',
  'int.manualHint':
    'WordPress-এ WooCommerce → Settings → Advanced → REST API → Add key খুলুন। Read/Write বেছে নিয়ে দুটি কী এখানে পেস্ট করুন।',
  'int.consumerKey': 'Consumer key',
  'int.consumerSecret': 'Consumer secret',
  'int.saveKeys': 'কী যাচাই করে সেভ করুন',
  'int.test': 'সংযোগ পরীক্ষা করুন',
  'int.testing': 'যাচাই হচ্ছে…',
  'int.testOk': 'সব ঠিকঠাক কাজ করছে।',
  'int.testFailed': 'কিছু একটা ঠিক করতে হবে।',
  'int.check.AUTH': 'স্টোরে লগইন ঠিক আছে',
  'int.check.WEBHOOKS': 'স্টোর নতুন অর্ডার সঙ্গে সঙ্গে পাঠায়',
  'int.check.API_KEY': 'API কী চালু আছে',
  'int.check.FIRST_REQUEST': 'আপনার ওয়েবসাইট ecomsbd-এ পৌঁছেছে',
  'int.check.FIRST_ORDER': 'প্রথম অর্ডার এসেছে',
  'int.check.WEBHOOK': 'আপনার ওয়েবসাইট আমাদের পরীক্ষামূলক ইভেন্ট পেয়েছে',
  'int.enable': 'চালু করুন',
  'int.disable': 'বন্ধ করুন',
  'int.disconnect': 'সংযোগ বিচ্ছিন্ন করুন',
  'int.disconnectConfirm': 'সংযোগ বিচ্ছিন্ন করবেন? নতুন অর্ডার আসা বন্ধ হবে। আগের অর্ডার থেকে যাবে।',
  'int.disconnectedHint': 'স্টোরের ক্ষেত্রে স্টোরের নিজের সেটিংস থেকেও ecomsbd অ্যাপ বা API কী সরিয়ে দিন।',
  'int.rename': 'নাম বদলান',
  'int.save': 'সেভ করুন',
  'int.importFrom': '{date}-এর পরের নতুন অর্ডার নিজে থেকেই আসবে।',
  'int.sync.title': 'পুরোনো অর্ডার আনুন',
  'int.sync.hint': 'কত দিন আগের অর্ডার আনবেন বেছে নিন। এর আগের কিছু আসবে না, কোনো অর্ডার দুবার যোগ হবে না।',
  'int.sync.days': 'গত {days} দিন',
  'int.sync.maxDays': 'সর্বোচ্চ {days} দিন আগ পর্যন্ত',
  'int.sync.start': 'ইমপোর্ট শুরু করুন',
  'int.sync.cancel': 'ইমপোর্ট থামান',
  'int.sync.history': 'সিঙ্কের ইতিহাস',
  'int.sync.none': 'এখনো কোনো ইমপোর্ট হয়নি।',
  'int.sync.kind.INITIAL': 'পুরোনো অর্ডার',
  'int.sync.kind.INCREMENTAL': 'বাদ পড়া অর্ডার খোঁজা',
  'int.sync.status.QUEUED': 'অপেক্ষায়',
  'int.sync.status.RUNNING': 'আনা হচ্ছে',
  'int.sync.status.COMPLETED': 'শেষ',
  'int.sync.status.FAILED': 'ব্যর্থ',
  'int.sync.status.CANCELLED': 'থামানো',
  'int.sync.counts': '{imported}টি এসেছে · {duplicates}টি আগেই ছিল · {skipped}টি বাদ · {failed}টিতে মনোযোগ দরকার',
  'int.sync.of': '{total}টির মধ্যে {done}টি',
  'int.sync.pages': '{pages} পাতা পড়া হয়েছে',
  'int.events.title': 'সাম্প্রতিক কার্যক্রম',
  'int.dev.title': 'ডেভেলপার সেটআপ',
  'int.dev.hint': 'আপনার ডেভেলপারের যা দরকার সব এখানে। এগুলো দিয়ে আপনার ecomsbd অ্যাকাউন্টে ঢোকা যায় না।',
  'int.dev.apiBase': 'API বেস URL',
  'int.dev.ordersEndpoint': 'অর্ডার তৈরির ঠিকানা',
  'int.dev.sourceId': 'সংযোগ আইডি',
  'int.dev.scopes': 'অনুমতি',
  'int.dev.key': 'API কী',
  'int.dev.keyOnce': 'এই API কী এখনই কপি করুন। এটি একবারই দেখানো হবে, পরে আর দেখা যাবে না।',
  'int.dev.secretOnce': 'এই সাইনিং সিক্রেট এখনই কপি করুন। এটি একবারই দেখানো হবে।',
  'int.dev.saved': 'সংরক্ষণ করেছি',
  'int.dev.copy': 'কপি',
  'int.dev.copied': 'কপি হয়েছে',
  'int.dev.rotate': 'API কী বদলান',
  'int.dev.rotateConfirm': 'বর্তমান কী সঙ্গে সঙ্গে বন্ধ হয়ে যাবে। ওয়েবসাইটে নতুন কী বসাতে হবে। এগোবেন?',
  'int.dev.keyActive': '{date} থেকে চালু',
  'int.dev.keyRevoked': 'বাতিল — আবার যুক্ত করতে কী বদলান',
  'int.dev.lastCall': 'ওয়েবসাইট থেকে শেষ অনুরোধ',
  'int.dev.lastOrder': 'শেষ অর্ডার এসেছে',
  'int.dev.waitingRequest': 'প্রথম অনুরোধের অপেক্ষায়…',
  'int.dev.waitingOrder': 'ওয়েবসাইটে একটি পরীক্ষামূলক অর্ডার দিন।',
  'int.dev.webhookUrl': 'আপনার ওয়েবসাইটের ওয়েবহুক ঠিকানা (HTTPS)',
  'int.dev.saveWebhook': 'ওয়েবহুক সেভ করুন',
  'int.dev.replaceWebhook': 'ওয়েবহুক বদলান',
  'int.dev.sendTest': 'পরীক্ষামূলক ইভেন্ট পাঠান',
  'int.dev.testQueued': 'পরীক্ষামূলক ইভেন্ট লাইনে আছে। কয়েক সেকেন্ড পর রিফ্রেশ করুন।',
  'int.dev.deliveries': 'গত ২৪ ঘণ্টায় {failed}টি পাঠানো ব্যর্থ',
  'int.dev.lastDelivery': 'শেষ পাঠানো',
  'int.dev.quickstart': 'দ্রুত শুরু',
  'int.dev.quickHint':
    'API কী শুধু সার্ভারে রাখুন। ব্রাউজারের JavaScript বা মোবাইল অ্যাপে কখনো রাখবেন না। প্রতিটি ওয়েবসাইট অর্ডারে একটি Idempotency-Key দিন, যাতে আবার পাঠালেও দ্বিতীয় অর্ডার না হয়।',
  'int.dev.part.create': 'অর্ডার তৈরি',
  'int.dev.part.verify': 'ওয়েবহুক যাচাই',
  'int.dev.part.status': 'অর্ডারের অবস্থা দেখা',
  'int.goLive': 'চালু করুন',
  'int.live': 'চালু',
  'int.recipes.title': 'প্রস্তাবিত অটোমেশন',
  'int.recipes.hint': 'আপনার অটোমেশনের নিয়ম, এই অর্ডারগুলোর জন্য চালু করার অপেক্ষায়।',
  'int.recipes.use': 'চালু করুন',
  'int.recipes.on': 'চালু',
  'int.pages.title': 'আপনার ফেসবুক পেজ বেছে নিন',
  'int.pages.use': 'এই পেজ যুক্ত করুন',
  'int.messengerNote': 'পেজের সংযোগ ঠিক আছে কি না ecomsbd দেখে রাখে। মেসেজ Messenger-এই থাকে।',
  'int.setup.title': 'অফিশিয়াল সেটআপ প্রয়োজন',
  'int.back': 'সব ইন্টিগ্রেশন',
};
