/**
 * Inventory + procurement copy (V3.5). Everyday Bangladeshi seller words:
 * মাল, সরবরাহকারী, ক্রয় আদেশ, গুদাম, বাকি, পরিশোধ.
 */
export const procurementEn = {
  'nav.procurement': 'Purchasing',
  'pr.title': 'Purchasing',
  'pr.subtitle': 'Suppliers, purchase orders, receiving and what you owe. Every received unit goes through the stock ledger.',
  'pr.tab.orders': 'Purchase orders',
  'pr.tab.suppliers': 'Suppliers',
  'pr.tab.payables': 'Payables',
  'pr.tab.stock': 'Stock & locations',
  'pr.newPo': 'New purchase order',
  'pr.newSupplier': 'New supplier',
  'pr.status.DRAFT': 'Draft',
  'pr.status.ORDERED': 'Ordered',
  'pr.status.PARTIALLY_RECEIVED': 'Partly received',
  'pr.status.RECEIVED': 'Received',
  'pr.status.CANCELLED': 'Cancelled',
  'pr.status.OPEN': 'Open',
  'pr.all': 'All',
  'pr.col.number': 'PO',
  'pr.col.supplier': 'Supplier',
  'pr.col.status': 'Status',
  'pr.col.expected': 'Expected',
  'pr.col.total': 'Order value',
  'pr.col.received': 'Received value',
  'pr.col.payable': 'Payment',
  'pr.col.item': 'Item',
  'pr.col.ordered': 'Ordered',
  'pr.col.receivedQty': 'Received',
  'pr.col.rejected': 'Rejected',
  'pr.col.remaining': 'Still to come',
  'pr.col.unitCost': 'Unit cost',
  'pr.col.onHand': 'On hand',
  'pr.col.incoming': 'Incoming',
  'pr.col.locations': 'By location',
  'pr.col.damaged': 'Damaged / rejected (30 days)',
  'pr.col.phone': 'Phone',
  'pr.col.openOrders': 'Open orders',
  'pr.col.balance': 'You owe',
  'pr.col.due': 'Due',
  'pr.empty': 'Nothing here yet',
  'pr.readOnly': 'You can view purchasing. An owner or manager creates and orders purchase orders.',
  'pr.f.supplier': 'Supplier',
  'pr.f.location': 'Receive at',
  'pr.f.mainLocation': 'Main location',
  'pr.f.expected': 'Expected delivery',
  'pr.f.paymentDue': 'Payment due (optional)',
  'pr.f.reference': 'Reference',
  'pr.f.notes': 'Notes',
  'pr.f.searchItem': 'Search products to add',
  'pr.f.variant': 'Variant',
  'pr.f.quantity': 'Quantity',
  'pr.f.unitCost': 'Unit cost (৳)',
  'pr.f.updateCost': 'Use as current cost',
  'pr.f.updateCostHint': 'When ticked, the received unit cost becomes the item’s cost for future orders. Past orders keep their cost.',
  'pr.f.remove': 'Remove',
  'pr.f.total': 'Order value',
  'pr.saveDraft': 'Save draft',
  'pr.order': 'Mark as ordered',
  'pr.orderHint': 'Records that you sent this order to the supplier. ecomsbd does not contact the supplier.',
  'pr.cancel': 'Cancel purchase order',
  'pr.cancelReason': 'Why cancel?',
  'pr.edit': 'Edit',
  'pr.receive': 'Receive goods',
  'pr.receiveHint': 'Count what arrived. Accepted units go into stock; rejected units do not.',
  'pr.r.accept': 'Accept',
  'pr.r.reject': 'Reject',
  'pr.r.reason': 'Reject reason',
  'pr.r.reason.DAMAGED': 'Damaged',
  'pr.r.reason.WRONG_ITEM': 'Wrong item',
  'pr.r.reason.EXPIRED': 'Expired',
  'pr.r.reason.OTHER': 'Other',
  'pr.r.supplierRef': 'Supplier challan / invoice no.',
  'pr.r.over': 'Reason for accepting more than ordered',
  'pr.r.overHint': 'Only an owner or manager can accept more than was ordered. It is recorded.',
  'pr.r.submit': 'Record receipt',
  'pr.r.done': 'Receipt recorded',
  'pr.receipts': 'Receipts',
  'pr.payments': 'Payments',
  'pr.pay': 'Record payment',
  'pr.p.amount': 'Amount (৳)',
  'pr.p.method': 'Method',
  'pr.p.method.CASH': 'Cash',
  'pr.p.method.BKASH': 'bKash',
  'pr.p.method.NAGAD': 'Nagad',
  'pr.p.method.ROCKET': 'Rocket',
  'pr.p.method.BANK': 'Bank',
  'pr.p.method.CHEQUE': 'Cheque',
  'pr.p.method.OTHER': 'Other',
  'pr.p.reference': 'Transaction ID / reference',
  'pr.p.separate': 'Supplier payments are kept apart from COD and courier payouts.',
  'pr.pay.NOTHING_DUE': 'Nothing due',
  'pr.pay.UNPAID': 'Unpaid',
  'pr.pay.PARTIALLY_PAID': 'Partly paid',
  'pr.pay.PAID': 'Paid',
  'pr.pay.overdue': 'Overdue',
  'pr.pay.advance': 'Advance {amount}',
  'pr.totals.owed': 'Received value',
  'pr.totals.paid': 'Paid',
  'pr.totals.outstanding': 'Outstanding',
  'pr.totals.overdue': 'Overdue',
  'pr.state.OPEN': 'Owing',
  'pr.state.OVERDUE': 'Overdue',
  'pr.state.PAID': 'Paid',
  'pr.state.ALL': 'All',
  'pr.s.name': 'Supplier name',
  'pr.s.contact': 'Contact person',
  'pr.s.phone': 'Phone',
  'pr.s.email': 'Email',
  'pr.s.address': 'Address',
  'pr.s.notes': 'Notes',
  'pr.s.terms': 'Payment terms (days after delivery)',
  'pr.s.active': 'Active',
  'pr.s.inactive': 'Inactive',
  'pr.s.save': 'Save supplier',
  'pr.s.items': 'Items this supplier sells',
  'pr.s.preferred': 'Preferred',
  'pr.s.makePreferred': 'Make preferred',
  'pr.s.preferredHint': 'Automatic draft purchase orders go to the preferred supplier.',
  'pr.s.lastCost': 'Last cost',
  'pr.s.addItem': 'Add item',
  'pr.st.low': 'Low stock only',
  'pr.st.search': 'Search items',
  'pr.st.lowBadge': 'Low',
  'pr.st.noReservation': 'Orders take stock when the parcel is booked, so there is no separate reserved figure.',
  'pr.loc.title': 'Locations',
  'pr.loc.hint': 'Optional. Sales always ship from the main location; move stock back before selling it.',
  'pr.loc.name': 'Name',
  'pr.loc.code': 'Code',
  'pr.loc.add': 'Add location',
  'pr.loc.main': 'Main',
  'pr.loc.close': 'Close',
  'pr.tr.title': 'Transfers',
  'pr.tr.new': 'Move stock',
  'pr.tr.from': 'From',
  'pr.tr.to': 'To',
  'pr.tr.submit': 'Move',
  'pr.tr.units': '{units} units',
  'pr.err.OVER_RECEIPT': 'That is more than was ordered. An owner or manager can accept it with a reason.',
  'pr.err.OVERPAYMENT': 'That pays more than this purchase order is worth.',
  'pr.err.PO_NOT_OPEN': 'This purchase order is not open for receiving.',
  'pr.err.INSUFFICIENT_LOCATION_STOCK': 'Not enough stock at that location.',
  'pr.err.LOCATION_NOT_EMPTY': 'Move this location’s stock out first.',
  'pr.err.SUPPLIER_EXISTS': 'A supplier with this name already exists.',
  'pr.err.STALE': 'Someone changed this purchase order. Reload it.',
  'inv.reason.TRANSFER_OUT': 'Moved to another location',
  'inv.reason.TRANSFER_IN': 'Arrived from another location',
} as const;

export const procurementBn: Record<keyof typeof procurementEn, string> = {
  'nav.procurement': 'মাল কেনা',
  'pr.title': 'মাল কেনা',
  'pr.subtitle': 'সরবরাহকারী, ক্রয় আদেশ, মাল বুঝে নেওয়া আর বাকি টাকা। প্রতিটি মাল স্টক খাতার মাধ্যমে যোগ হয়।',
  'pr.tab.orders': 'ক্রয় আদেশ',
  'pr.tab.suppliers': 'সরবরাহকারী',
  'pr.tab.payables': 'সরবরাহকারীর বাকি',
  'pr.tab.stock': 'স্টক ও গুদাম',
  'pr.newPo': 'নতুন ক্রয় আদেশ',
  'pr.newSupplier': 'নতুন সরবরাহকারী',
  'pr.status.DRAFT': 'খসড়া',
  'pr.status.ORDERED': 'অর্ডার দেওয়া হয়েছে',
  'pr.status.PARTIALLY_RECEIVED': 'আংশিক এসেছে',
  'pr.status.RECEIVED': 'সব এসেছে',
  'pr.status.CANCELLED': 'বাতিল',
  'pr.status.OPEN': 'চলমান',
  'pr.all': 'সব',
  'pr.col.number': 'আদেশ নং',
  'pr.col.supplier': 'সরবরাহকারী',
  'pr.col.status': 'অবস্থা',
  'pr.col.expected': 'আসার কথা',
  'pr.col.total': 'অর্ডারের মূল্য',
  'pr.col.received': 'যে মাল এসেছে তার মূল্য',
  'pr.col.payable': 'পরিশোধ',
  'pr.col.item': 'পণ্য',
  'pr.col.ordered': 'অর্ডার',
  'pr.col.receivedQty': 'এসেছে',
  'pr.col.rejected': 'ফেরত/বাতিল',
  'pr.col.remaining': 'আরও আসবে',
  'pr.col.unitCost': 'একক দাম',
  'pr.col.onHand': 'হাতে আছে',
  'pr.col.incoming': 'আসছে',
  'pr.col.locations': 'কোথায় আছে',
  'pr.col.damaged': 'নষ্ট / ফেরত (৩০ দিন)',
  'pr.col.phone': 'ফোন',
  'pr.col.openOrders': 'চলমান আদেশ',
  'pr.col.balance': 'আপনার বাকি',
  'pr.col.due': 'পরিশোধের তারিখ',
  'pr.empty': 'এখনো কিছু নেই',
  'pr.readOnly': 'আপনি দেখতে পারবেন। ক্রয় আদেশ তৈরি ও অর্ডার দেন মালিক বা ম্যানেজার।',
  'pr.f.supplier': 'সরবরাহকারী',
  'pr.f.location': 'কোথায় মাল নেবেন',
  'pr.f.mainLocation': 'প্রধান জায়গা',
  'pr.f.expected': 'মাল আসার তারিখ',
  'pr.f.paymentDue': 'পরিশোধের তারিখ (ঐচ্ছিক)',
  'pr.f.reference': 'রেফারেন্স',
  'pr.f.notes': 'নোট',
  'pr.f.searchItem': 'পণ্য খুঁজে যোগ করুন',
  'pr.f.variant': 'ভ্যারিয়েন্ট',
  'pr.f.quantity': 'পরিমাণ',
  'pr.f.unitCost': 'একক দাম (৳)',
  'pr.f.updateCost': 'এটাই বর্তমান খরচ ধরুন',
  'pr.f.updateCostHint': 'টিক দিলে মাল আসার পর এই দামই পরের অর্ডারের খরচ হবে। আগের অর্ডারের খরচ বদলাবে না।',
  'pr.f.remove': 'বাদ দিন',
  'pr.f.total': 'অর্ডারের মূল্য',
  'pr.saveDraft': 'খসড়া সংরক্ষণ',
  'pr.order': 'অর্ডার দেওয়া হয়েছে চিহ্নিত করুন',
  'pr.orderHint': 'আপনি সরবরাহকারীকে অর্ডার পাঠিয়েছেন তা লিখে রাখে। ecomsbd সরবরাহকারীর সঙ্গে যোগাযোগ করে না।',
  'pr.cancel': 'ক্রয় আদেশ বাতিল',
  'pr.cancelReason': 'কেন বাতিল?',
  'pr.edit': 'সম্পাদনা',
  'pr.receive': 'মাল বুঝে নিন',
  'pr.receiveHint': 'যা এসেছে গুনে নিন। গ্রহণ করা মাল স্টকে যোগ হবে; বাতিল করা মাল হবে না।',
  'pr.r.accept': 'গ্রহণ',
  'pr.r.reject': 'বাতিল',
  'pr.r.reason': 'বাতিলের কারণ',
  'pr.r.reason.DAMAGED': 'নষ্ট',
  'pr.r.reason.WRONG_ITEM': 'ভুল মাল',
  'pr.r.reason.EXPIRED': 'মেয়াদোত্তীর্ণ',
  'pr.r.reason.OTHER': 'অন্যান্য',
  'pr.r.supplierRef': 'চালান / ইনভয়েস নম্বর',
  'pr.r.over': 'অর্ডারের বেশি মাল নেওয়ার কারণ',
  'pr.r.overHint': 'অর্ডারের বেশি মাল নিতে পারেন শুধু মালিক বা ম্যানেজার। এটি লিখে রাখা হয়।',
  'pr.r.submit': 'মাল বুঝে নেওয়া সংরক্ষণ',
  'pr.r.done': 'সংরক্ষিত হয়েছে',
  'pr.receipts': 'মাল আসার হিসাব',
  'pr.payments': 'পরিশোধ',
  'pr.pay': 'পরিশোধ লিখুন',
  'pr.p.amount': 'টাকার পরিমাণ (৳)',
  'pr.p.method': 'কীভাবে',
  'pr.p.method.CASH': 'নগদ',
  'pr.p.method.BKASH': 'বিকাশ',
  'pr.p.method.NAGAD': 'Nagad',
  'pr.p.method.ROCKET': 'রকেট',
  'pr.p.method.BANK': 'ব্যাংক',
  'pr.p.method.CHEQUE': 'চেক',
  'pr.p.method.OTHER': 'অন্যান্য',
  'pr.p.reference': 'ট্রানজেকশন আইডি / রেফারেন্স',
  'pr.p.separate': 'সরবরাহকারীর পরিশোধ COD ও কুরিয়ারের পেমেন্ট থেকে আলাদা রাখা হয়।',
  'pr.pay.NOTHING_DUE': 'কিছু বাকি নেই',
  'pr.pay.UNPAID': 'পরিশোধ হয়নি',
  'pr.pay.PARTIALLY_PAID': 'আংশিক পরিশোধ',
  'pr.pay.PAID': 'পরিশোধিত',
  'pr.pay.overdue': 'মেয়াদ পেরিয়েছে',
  'pr.pay.advance': 'অগ্রিম {amount}',
  'pr.totals.owed': 'আসা মালের মূল্য',
  'pr.totals.paid': 'পরিশোধ',
  'pr.totals.outstanding': 'বাকি',
  'pr.totals.overdue': 'মেয়াদোত্তীর্ণ বাকি',
  'pr.state.OPEN': 'বাকি আছে',
  'pr.state.OVERDUE': 'মেয়াদোত্তীর্ণ',
  'pr.state.PAID': 'পরিশোধিত',
  'pr.state.ALL': 'সব',
  'pr.s.name': 'সরবরাহকারীর নাম',
  'pr.s.contact': 'যোগাযোগের ব্যক্তি',
  'pr.s.phone': 'ফোন',
  'pr.s.email': 'ইমেইল',
  'pr.s.address': 'ঠিকানা',
  'pr.s.notes': 'নোট',
  'pr.s.terms': 'পরিশোধের সময় (মাল আসার কত দিন পর)',
  'pr.s.active': 'সক্রিয়',
  'pr.s.inactive': 'নিষ্ক্রিয়',
  'pr.s.save': 'সরবরাহকারী সংরক্ষণ',
  'pr.s.items': 'এই সরবরাহকারীর পণ্য',
  'pr.s.preferred': 'পছন্দের',
  'pr.s.makePreferred': 'পছন্দের করুন',
  'pr.s.preferredHint': 'স্বয়ংক্রিয় খসড়া ক্রয় আদেশ পছন্দের সরবরাহকারীর নামে তৈরি হয়।',
  'pr.s.lastCost': 'শেষ দাম',
  'pr.s.addItem': 'পণ্য যোগ করুন',
  'pr.st.low': 'শুধু কম স্টক',
  'pr.st.search': 'পণ্য খুঁজুন',
  'pr.st.lowBadge': 'কম',
  'pr.st.noReservation': 'পার্সেল বুক করার সময় স্টক কমে, তাই আলাদা "রিজার্ভ" হিসাব নেই।',
  'pr.loc.title': 'গুদাম / জায়গা',
  'pr.loc.hint': 'ঐচ্ছিক। বিক্রি সবসময় প্রধান জায়গা থেকে হয়; বিক্রির আগে মাল ফেরত আনুন।',
  'pr.loc.name': 'নাম',
  'pr.loc.code': 'কোড',
  'pr.loc.add': 'জায়গা যোগ করুন',
  'pr.loc.main': 'প্রধান',
  'pr.loc.close': 'বন্ধ করুন',
  'pr.tr.title': 'স্থানান্তর',
  'pr.tr.new': 'মাল সরান',
  'pr.tr.from': 'কোথা থেকে',
  'pr.tr.to': 'কোথায়',
  'pr.tr.submit': 'সরান',
  'pr.tr.units': '{units} পিস',
  'pr.err.OVER_RECEIPT': 'অর্ডারের চেয়ে বেশি। মালিক বা ম্যানেজার কারণসহ নিতে পারেন।',
  'pr.err.OVERPAYMENT': 'এই ক্রয় আদেশের মূল্যের চেয়ে বেশি পরিশোধ।',
  'pr.err.PO_NOT_OPEN': 'এই ক্রয় আদেশে এখন মাল নেওয়া যাবে না।',
  'pr.err.INSUFFICIENT_LOCATION_STOCK': 'ওই জায়গায় যথেষ্ট মাল নেই।',
  'pr.err.LOCATION_NOT_EMPTY': 'আগে এই জায়গার মাল সরান।',
  'pr.err.SUPPLIER_EXISTS': 'এই নামে সরবরাহকারী আগেই আছে।',
  'pr.err.STALE': 'কেউ এই ক্রয় আদেশ বদলেছে। আবার লোড করুন।',
  'inv.reason.TRANSFER_OUT': 'অন্য জায়গায় সরানো হয়েছে',
  'inv.reason.TRANSFER_IN': 'অন্য জায়গা থেকে এসেছে',
};
