/**
 * Customer risk, external risk provider and network intelligence copy (V3.7).
 *
 * Three sources are always named apart: the shop's own history, a connected
 * provider's facts, and anonymous network figures. None of them is a verdict
 * on a person.
 */
export const riskEn = {
  'nav.riskProvider': 'Risk provider',
  'orders.reviewHold': 'Held for review',
  'orders.reviewHoldHint': 'A workflow paused this order. Workflows will not book a courier or update the store until you release it.',
  'orders.reviewRelease': 'Reviewed — release',
  'risk.title': 'Delivery risk',
  'risk.own.title': 'Your shop’s history with this customer',
  'risk.own.hint': 'Only orders and parcels with your shop. This is what Risk Check uses.',
  'risk.own.band': 'Risk Check',
  'risk.own.success': 'Delivered with your shop',
  'risk.own.orders': 'Orders',
  'risk.own.delivered': 'Delivered',
  'risk.own.returned': 'Returned (RTO)',
  'risk.own.cancelled': 'Cancelled before dispatch',
  'risk.own.inTransit': 'On the way',
  'risk.own.repeatedRto': 'Returned more than once with your shop',
  'risk.own.recent': 'Recent parcels',
  'risk.state.LOW': 'Low',
  'risk.state.MEDIUM': 'Medium',
  'risk.state.HIGH': 'High',
  'risk.state.INSUFFICIENT_DATA': 'Not enough history',
  'risk.ext.title': 'External provider facts',
  'risk.ext.hint': 'What a provider you connected reports. Shown separately and never mixed into your shop’s history.',
  'risk.ext.gated': 'No licensed risk provider is available yet. Your shop’s own Risk Check works as usual.',
  'risk.ext.notConfigured': 'No risk provider is turned on for your shop.',
  'risk.ext.setup': 'Set up a risk provider',
  'risk.ext.none': 'Not checked with this provider yet.',
  'risk.ext.check': 'Check with provider',
  'risk.ext.refresh': 'Refresh',
  'risk.ext.checking': 'Checking…',
  'risk.ext.noPermission': 'Only owners and managers can ask a provider.',
  'risk.ext.found': 'Provider has records for this number',
  'risk.ext.notFound': 'Provider has no records for this number',
  'risk.ext.observed': 'Provider data as of {when}',
  'risk.ext.checked': 'Checked {when}',
  'risk.ext.fresh': 'Up to date',
  'risk.ext.stale': 'Out of date — refresh to check again',
  'risk.ext.sample': 'Provider sample: {n}',
  'risk.ext.confidence': 'Provider confidence: {value}',
  'risk.ext.period': 'over {n} days',
  'risk.ext.lastError': 'Last attempt failed: {reason}',
  'risk.ext.cached': 'Stored answer is still current; the provider was not asked again.',
  'risk.ext.skipped': 'Provider paused: {reason}',
  'risk.fact.DELIVERED_PARCELS': 'Delivered parcels',
  'risk.fact.RETURNED_PARCELS': 'Returned parcels',
  'risk.fact.CANCELLED_ORDERS': 'Cancelled orders',
  'risk.fact.TOTAL_PARCELS': 'All parcels',
  'risk.err.PROVIDER_TIMEOUT': 'the provider took too long',
  'risk.err.PROVIDER_UNAVAILABLE': 'the provider is unavailable',
  'risk.err.PROVIDER_RATE_LIMITED': 'too many requests to the provider',
  'risk.err.PROVIDER_AUTH_FAILED': 'the provider rejected your credentials',
  'risk.err.PROVIDER_REJECTED': 'the provider refused the request',
  'risk.err.PROVIDER_BAD_RESPONSE': 'the provider sent an answer we could not read',
  'risk.net.title': 'Network context',
  'risk.net.hint': 'Anonymous monthly figures from consenting shops. They describe the network, not this customer.',
  'risk.net.none': 'No anonymous figures published yet.',
  'rp.title': 'Risk provider',
  'rp.subtitle': 'Connect a licensed external risk provider. Your shop’s own Risk Check never depends on it.',
  'rp.gated': 'No licensed, documented risk provider is available in ecomsbd yet. When one is added it will appear here. Nothing about your customers is shared in the meantime.',
  'rp.contract': 'Provider contract',
  'rp.capabilities': 'Can do',
  'rp.cap.PHONE_DELIVERY_HISTORY': 'Delivery history for a phone number',
  'rp.cap.CONNECTION_TEST': 'Connection test',
  'rp.credentials': 'Credentials',
  'rp.credentialsSet': 'Saved (ends in {hint}). Enter new values to replace them.',
  'rp.credentialsNote': 'Stored encrypted. They are never shown again, not even to you.',
  'rp.cacheTtl': 'Keep answers for (hours)',
  'rp.cacheHint': 'A stored answer is reused until it is older than this, so you do not pay twice for the same number.',
  'rp.save': 'Save',
  'rp.test': 'Test connection',
  'rp.enable': 'Turn on',
  'rp.disable': 'Turn off',
  'rp.remove': 'Remove credentials',
  'rp.saved': 'Saved. Run a connection test before turning it on.',
  'rp.testOk': 'Connection works.',
  'rp.testFailed': 'Connection test failed: {reason}',
  'rp.health': 'Health',
  'rp.health.UNKNOWN': 'Not tested',
  'rp.health.HEALTHY': 'Working',
  'rp.health.DEGRADED': 'Having problems',
  'rp.health.DOWN': 'Down — calls paused',
  'rp.lastTest': 'Last test',
  'rp.lastSuccess': 'Last successful answer',
  'rp.lastFailure': 'Last failure',
  'rp.rateLimitedUntil': 'Paused by the provider until',
  'rp.on': 'On',
  'rp.off': 'Off',
  'rp.privacy': 'Only the customer’s phone number is sent, and only when someone asks. Every lookup is recorded. There is no shared blacklist and no way to see another shop’s customers.',
  'net.title': 'Network intelligence',
  'net.subtitle': 'Anonymous monthly benchmarks from consenting shops, next to your own figures. No shop, customer or phone can be looked up.',
  'net.tab.overview': 'Overview',
  'net.tab.cohorts': 'Cohorts',
  'net.tab.couriers': 'Couriers',
  'net.consent': 'Consent to anonymous aggregation',
  'net.optOut': 'Opt out',
  'net.optedIn': 'Your shop contributes to future months.',
  'net.notOptedIn': 'Your shop does not contribute.',
  'net.consentNote': 'Only closed monthly aggregates. Opting out stops future contributions; published anonymous results remain.',
  'net.period': 'Period',
  'net.computed': 'Computed {when}',
  'net.noRelease': 'No anonymous release yet. The first one is computed a week after a month closes.',
  'net.dimension': 'Compare by',
  'net.dim.ALL': 'All shops',
  'net.dim.COURIER': 'Courier',
  'net.dim.CATEGORY': 'Broad category',
  'net.dim.VOLUME_BAND': 'Monthly parcel volume',
  'net.cohort.ALL': 'All shops',
  'net.cohort.UNDER_100': 'Under 100 parcels',
  'net.cohort.100_TO_499': '100–499 parcels',
  'net.cohort.500_PLUS': '500+ parcels',
  'net.metric': 'Metric',
  'net.cohort': 'Cohort',
  'net.value': 'Value',
  'net.shops': 'Shops',
  'net.sample': 'Sample',
  'net.metric.RTO_RATE': 'Return (RTO) rate',
  'net.metric.DELIVERY_SUCCESS': 'Delivery success',
  'net.metric.DELIVERY_HOURS': 'Booking to delivery (median)',
  'net.metric.STUCK_RATE': 'Parcels stuck over 10 days',
  'net.metric.PAYOUT_DELAY_DAYS': 'Delivery to payout (median)',
  'net.metric.RECON_DISCREPANCY_RATE': 'Payout lines with a discrepancy',
  'net.metric.DELIVERY_CHARGE': 'Courier charge per parcel (median)',
  'net.insufficient': 'Data not sufficient',
  'net.unit.hours': '{n} h',
  'net.unit.days': '{n} days',
  'net.unit.taka': '৳{n}',
  'net.quality.title': 'How to read these figures',
  'net.quality.body': 'A figure is published only when at least {shops} shops and {sample} observations take part, no shop is more than {share}% of it, and both outcomes are present. Rates are rounded to 5%; sample sizes are shown as bands. Otherwise it says “Data not sufficient”. Thresholds are never lowered to show a figure.',
  'net.quality.freshness': 'Released once per closed calendar month (UTC), a week after it ends, and never changed afterwards.',
  'net.cour.title': 'Your couriers, last {days} days',
  'net.cour.hint': 'Facts from your own parcels, payouts and reconciliation. No overall score and no recommendation.',
  'net.cour.courier': 'Courier',
  'net.cour.completed': 'Completed',
  'net.cour.deliveryRate': 'Delivered',
  'net.cour.rto': 'RTO',
  'net.cour.hours': 'Booking → delivery',
  'net.cour.stuck': 'Stuck (> {days} days no update)',
  'net.cour.payout': 'Delivery → payout',
  'net.cour.outstanding': 'COD outstanding',
  'net.cour.overdue': 'Overdue (> {days} days)',
  'net.cour.mismatch': 'Reconciliation mismatches',
  'net.cour.charge': 'Charge per parcel',
  'net.cour.notLive': 'No live integration: counts only',
  'net.cour.empty': 'No courier parcels in this window.',
  'net.cour.network': 'Network, by courier',
  'net.small': 'too few to show',
} as const;

export const riskBn: Record<keyof typeof riskEn, string> = {
  'nav.riskProvider': 'রিস্ক প্রোভাইডার',
  'orders.reviewHold': 'পর্যালোচনার জন্য আটকানো',
  'orders.reviewHoldHint': 'একটি ওয়ার্কফ্লো এই অর্ডার থামিয়েছে। আপনি ছেড়ে না দেওয়া পর্যন্ত ওয়ার্কফ্লো কুরিয়ার বুক বা স্টোর আপডেট করবে না।',
  'orders.reviewRelease': 'দেখা হয়েছে — ছেড়ে দিন',
  'risk.title': 'ডেলিভারি ঝুঁকি',
  'risk.own.title': 'এই গ্রাহকের সঙ্গে আপনার শপের ইতিহাস',
  'risk.own.hint': 'শুধু আপনার শপের অর্ডার ও পার্সেল। রিস্ক চেক এটাই ব্যবহার করে।',
  'risk.own.band': 'রিস্ক চেক',
  'risk.own.success': 'আপনার শপ থেকে ডেলিভারি হয়েছে',
  'risk.own.orders': 'অর্ডার',
  'risk.own.delivered': 'ডেলিভারি হয়েছে',
  'risk.own.returned': 'ফেরত (RTO)',
  'risk.own.cancelled': 'পাঠানোর আগে বাতিল',
  'risk.own.inTransit': 'পথে আছে',
  'risk.own.repeatedRto': 'আপনার শপ থেকে একাধিকবার ফেরত এসেছে',
  'risk.own.recent': 'সাম্প্রতিক পার্সেল',
  'risk.state.LOW': 'কম',
  'risk.state.MEDIUM': 'মাঝারি',
  'risk.state.HIGH': 'বেশি',
  'risk.state.INSUFFICIENT_DATA': 'যথেষ্ট ইতিহাস নেই',
  'risk.ext.title': 'বাইরের প্রোভাইডারের তথ্য',
  'risk.ext.hint': 'আপনার যুক্ত করা প্রোভাইডার যা জানায়। আলাদা দেখানো হয়, আপনার শপের ইতিহাসের সঙ্গে কখনো মেশানো হয় না।',
  'risk.ext.gated': 'এখনো কোনো লাইসেন্সপ্রাপ্ত রিস্ক প্রোভাইডার নেই। আপনার শপের নিজস্ব রিস্ক চেক আগের মতোই চলছে।',
  'risk.ext.notConfigured': 'আপনার শপে কোনো রিস্ক প্রোভাইডার চালু নেই।',
  'risk.ext.setup': 'রিস্ক প্রোভাইডার সেট আপ করুন',
  'risk.ext.none': 'এই প্রোভাইডারে এখনো দেখা হয়নি।',
  'risk.ext.check': 'প্রোভাইডারে দেখুন',
  'risk.ext.refresh': 'আবার দেখুন',
  'risk.ext.checking': 'দেখা হচ্ছে…',
  'risk.ext.noPermission': 'শুধু মালিক ও ম্যানেজার প্রোভাইডারে দেখতে পারেন।',
  'risk.ext.found': 'এই নম্বরের রেকর্ড প্রোভাইডারের কাছে আছে',
  'risk.ext.notFound': 'এই নম্বরের কোনো রেকর্ড প্রোভাইডারের কাছে নেই',
  'risk.ext.observed': '{when} পর্যন্ত প্রোভাইডারের তথ্য',
  'risk.ext.checked': 'দেখা হয়েছে {when}',
  'risk.ext.fresh': 'হালনাগাদ',
  'risk.ext.stale': 'পুরোনো — আবার দেখতে রিফ্রেশ করুন',
  'risk.ext.sample': 'প্রোভাইডারের নমুনা: {n}',
  'risk.ext.confidence': 'প্রোভাইডারের আস্থা: {value}',
  'risk.ext.period': '{n} দিনে',
  'risk.ext.lastError': 'শেষ চেষ্টা ব্যর্থ: {reason}',
  'risk.ext.cached': 'সংরক্ষিত উত্তর এখনো হালনাগাদ; প্রোভাইডারকে আবার জিজ্ঞেস করা হয়নি।',
  'risk.ext.skipped': 'প্রোভাইডার বিরতিতে: {reason}',
  'risk.fact.DELIVERED_PARCELS': 'ডেলিভারি হওয়া পার্সেল',
  'risk.fact.RETURNED_PARCELS': 'ফেরত আসা পার্সেল',
  'risk.fact.CANCELLED_ORDERS': 'বাতিল অর্ডার',
  'risk.fact.TOTAL_PARCELS': 'সব পার্সেল',
  'risk.err.PROVIDER_TIMEOUT': 'প্রোভাইডার অনেক দেরি করেছে',
  'risk.err.PROVIDER_UNAVAILABLE': 'প্রোভাইডার এখন পাওয়া যাচ্ছে না',
  'risk.err.PROVIDER_RATE_LIMITED': 'প্রোভাইডারে অনেক বেশি অনুরোধ',
  'risk.err.PROVIDER_AUTH_FAILED': 'প্রোভাইডার আপনার ক্রেডেনশিয়াল গ্রহণ করেনি',
  'risk.err.PROVIDER_REJECTED': 'প্রোভাইডার অনুরোধটি ফিরিয়ে দিয়েছে',
  'risk.err.PROVIDER_BAD_RESPONSE': 'প্রোভাইডারের উত্তর পড়া যায়নি',
  'risk.net.title': 'নেটওয়ার্কের প্রেক্ষাপট',
  'risk.net.hint': 'সম্মত শপগুলোর মাসিক বেনামি হিসাব। এটি নেটওয়ার্কের কথা বলে, এই গ্রাহকের নয়।',
  'risk.net.none': 'এখনো কোনো বেনামি হিসাব প্রকাশ হয়নি।',
  'rp.title': 'রিস্ক প্রোভাইডার',
  'rp.subtitle': 'লাইসেন্সপ্রাপ্ত বাইরের রিস্ক প্রোভাইডার যুক্ত করুন। আপনার শপের নিজস্ব রিস্ক চেক এর ওপর নির্ভর করে না।',
  'rp.gated': 'ecomsbd-এ এখনো কোনো লাইসেন্সপ্রাপ্ত ও ডকুমেন্টেড রিস্ক প্রোভাইডার নেই। যুক্ত হলে এখানে দেখাবে। ততদিন আপনার গ্রাহকদের কোনো তথ্য শেয়ার হয় না।',
  'rp.contract': 'প্রোভাইডারের চুক্তি',
  'rp.capabilities': 'যা করতে পারে',
  'rp.cap.PHONE_DELIVERY_HISTORY': 'ফোন নম্বরের ডেলিভারি ইতিহাস',
  'rp.cap.CONNECTION_TEST': 'কানেকশন টেস্ট',
  'rp.credentials': 'ক্রেডেনশিয়াল',
  'rp.credentialsSet': 'সংরক্ষিত (শেষে {hint})। বদলাতে নতুন মান দিন।',
  'rp.credentialsNote': 'এনক্রিপ্ট করে রাখা হয়। আর কখনো দেখানো হয় না, আপনাকেও না।',
  'rp.cacheTtl': 'উত্তর রাখা হবে (ঘণ্টা)',
  'rp.cacheHint': 'এর চেয়ে পুরোনো না হওয়া পর্যন্ত সংরক্ষিত উত্তর আবার ব্যবহার হয়, তাই একই নম্বরের জন্য দুবার খরচ হয় না।',
  'rp.save': 'সংরক্ষণ',
  'rp.test': 'কানেকশন টেস্ট',
  'rp.enable': 'চালু করুন',
  'rp.disable': 'বন্ধ করুন',
  'rp.remove': 'ক্রেডেনশিয়াল মুছুন',
  'rp.saved': 'সংরক্ষিত। চালু করার আগে কানেকশন টেস্ট করুন।',
  'rp.testOk': 'কানেকশন কাজ করছে।',
  'rp.testFailed': 'কানেকশন টেস্ট ব্যর্থ: {reason}',
  'rp.health': 'অবস্থা',
  'rp.health.UNKNOWN': 'টেস্ট হয়নি',
  'rp.health.HEALTHY': 'কাজ করছে',
  'rp.health.DEGRADED': 'সমস্যা হচ্ছে',
  'rp.health.DOWN': 'বন্ধ — অনুরোধ স্থগিত',
  'rp.lastTest': 'শেষ টেস্ট',
  'rp.lastSuccess': 'শেষ সফল উত্তর',
  'rp.lastFailure': 'শেষ ব্যর্থতা',
  'rp.rateLimitedUntil': 'প্রোভাইডার বিরতি দিয়েছে যতক্ষণ',
  'rp.on': 'চালু',
  'rp.off': 'বন্ধ',
  'rp.privacy': 'শুধু গ্রাহকের ফোন নম্বর পাঠানো হয়, আর শুধু কেউ চাইলে। প্রতিটি খোঁজ রেকর্ড হয়। কোনো শেয়ার করা ব্ল্যাকলিস্ট নেই, অন্য শপের গ্রাহক দেখার কোনো উপায় নেই।',
  'net.title': 'নেটওয়ার্ক ইন্টেলিজেন্স',
  'net.subtitle': 'সম্মত শপগুলোর মাসিক বেনামি বেঞ্চমার্ক, আপনার নিজের হিসাবের পাশে। কোনো শপ, গ্রাহক বা ফোন খোঁজা যায় না।',
  'net.tab.overview': 'সারসংক্ষেপ',
  'net.tab.cohorts': 'গ্রুপ',
  'net.tab.couriers': 'কুরিয়ার',
  'net.consent': 'বেনামি সমষ্টিতে অংশ নিতে সম্মতি দিন',
  'net.optOut': 'অংশগ্রহণ বন্ধ করুন',
  'net.optedIn': 'আপনার শপ ভবিষ্যতের মাসগুলোতে অংশ নেবে।',
  'net.notOptedIn': 'আপনার শপ অংশ নিচ্ছে না।',
  'net.consentNote': 'শুধু পুরো মাসের সমষ্টিগত তথ্য। সম্মতি প্রত্যাহার করলে ভবিষ্যতের হিসাবে অংশ নেবে না; প্রকাশিত বেনামি ফল থাকবে।',
  'net.period': 'সময়কাল',
  'net.computed': 'হিসাব হয়েছে {when}',
  'net.noRelease': 'এখনো কোনো বেনামি হিসাব নেই। মাস শেষ হওয়ার এক সপ্তাহ পরে প্রথমটি হিসাব হয়।',
  'net.dimension': 'তুলনার ভিত্তি',
  'net.dim.ALL': 'সব শপ',
  'net.dim.COURIER': 'কুরিয়ার',
  'net.dim.CATEGORY': 'ব্যবসার ধরন',
  'net.dim.VOLUME_BAND': 'মাসিক পার্সেলের পরিমাণ',
  'net.cohort.ALL': 'সব শপ',
  'net.cohort.UNDER_100': '১০০-এর কম পার্সেল',
  'net.cohort.100_TO_499': '১০০–৪৯৯ পার্সেল',
  'net.cohort.500_PLUS': '৫০০+ পার্সেল',
  'net.metric': 'মাপকাঠি',
  'net.cohort': 'গ্রুপ',
  'net.value': 'মান',
  'net.shops': 'শপ',
  'net.sample': 'নমুনা',
  'net.metric.RTO_RATE': 'ফেরতের (RTO) হার',
  'net.metric.DELIVERY_SUCCESS': 'ডেলিভারি সফলতা',
  'net.metric.DELIVERY_HOURS': 'বুকিং থেকে ডেলিভারি (মধ্যমা)',
  'net.metric.STUCK_RATE': '১০ দিনের বেশি আটকে থাকা পার্সেল',
  'net.metric.PAYOUT_DELAY_DAYS': 'ডেলিভারি থেকে পেআউট (মধ্যমা)',
  'net.metric.RECON_DISCREPANCY_RATE': 'গরমিলসহ পেআউট লাইন',
  'net.metric.DELIVERY_CHARGE': 'পার্সেলপ্রতি কুরিয়ার চার্জ (মধ্যমা)',
  'net.insufficient': 'যথেষ্ট তথ্য নেই',
  'net.unit.hours': '{n} ঘণ্টা',
  'net.unit.days': '{n} দিন',
  'net.unit.taka': '৳{n}',
  'net.quality.title': 'এই হিসাব কীভাবে পড়বেন',
  'net.quality.body': 'কমপক্ষে {shops}টি শপ ও {sample}টি পর্যবেক্ষণ থাকলে, কোনো শপ {share}%-এর বেশি না হলে এবং দুই ধরনের ফলই থাকলে তবেই হিসাব প্রকাশ হয়। হার ৫% ধাপে, নমুনা শুধু সীমা হিসেবে দেখানো হয়। নইলে লেখা থাকে “যথেষ্ট তথ্য নেই”। হিসাব দেখানোর জন্য সীমা কখনো কমানো হয় না।',
  'net.quality.freshness': 'প্রতিটি পুরো ক্যালেন্ডার মাসের (UTC) জন্য একবার, মাস শেষের এক সপ্তাহ পরে প্রকাশ হয়; পরে আর বদলায় না।',
  'net.cour.title': 'আপনার কুরিয়ার, গত {days} দিন',
  'net.cour.hint': 'আপনার নিজের পার্সেল, পেআউট ও রিকনসিলিয়েশনের তথ্য। কোনো সামগ্রিক স্কোর বা সুপারিশ নেই।',
  'net.cour.courier': 'কুরিয়ার',
  'net.cour.completed': 'সম্পন্ন',
  'net.cour.deliveryRate': 'ডেলিভারি',
  'net.cour.rto': 'RTO',
  'net.cour.hours': 'বুকিং → ডেলিভারি',
  'net.cour.stuck': 'আটকে আছে (> {days} দিন আপডেট নেই)',
  'net.cour.payout': 'ডেলিভারি → পেআউট',
  'net.cour.outstanding': 'বাকি COD',
  'net.cour.overdue': 'মেয়াদোত্তীর্ণ (> {days} দিন)',
  'net.cour.mismatch': 'রিকনসিলিয়েশনে গরমিল',
  'net.cour.charge': 'পার্সেলপ্রতি চার্জ',
  'net.cour.notLive': 'লাইভ ইন্টিগ্রেশন নেই: শুধু সংখ্যা',
  'net.cour.empty': 'এই সময়ে কোনো কুরিয়ার পার্সেল নেই।',
  'net.cour.network': 'নেটওয়ার্ক, কুরিয়ার অনুযায়ী',
  'net.small': 'দেখানোর মতো যথেষ্ট নয়',
};
