/**
 * Two-way sync copy (V3.2). "Conflict" is অমিল in Bangla: sellers say two
 * sides do not match, not that they are fighting.
 */
export const syncEn = {
  'sync.tab.overview': 'Overview',
  'sync.tab.settings': 'Sync settings',
  'sync.tab.mapping': 'Product mapping',
  'sync.tab.conflicts': 'Conflicts',
  'sync.title': 'Who is in charge',
  'sync.hint': 'Choose who is in charge of each thing. Nothing changes in your store or your stock until you turn it on.',
  'sync.orders': 'Orders',
  'sync.ordersFixed': 'New store orders always come into ecomsbd. ecomsbd runs packing, courier and money.',
  'sync.catalog': 'Match store products with ecomsbd products',
  'sync.products': 'Product details',
  'sync.products.MANUAL': 'I match products myself — nothing is copied either way',
  'sync.products.EXTERNAL': 'The store is in charge — new store products are added to ecomsbd and store prices update ecomsbd',
  'sync.products.ECOMSBD': 'ecomsbd is in charge — price changes in ecomsbd go to the store',
  'sync.inventory': 'Stock',
  'sync.inventory.NONE': 'Do not sync stock',
  'sync.inventory.ECOMSBD': 'ecomsbd controls stock — the store is updated from ecomsbd',
  'sync.inventory.EXTERNAL': 'The store controls stock — ecomsbd follows it, and every change is recorded in stock history',
  'sync.order_status': 'Order status',
  'sync.order_status.OFF': 'Keep order status separate',
  'sync.order_status.TWO_WAY': 'Two-way — confirmations, cancellations and deliveries go both ways where the store supports it',
  'sync.fulfillment': 'Courier tracking',
  'sync.fulfillment.OFF': 'Do not send tracking to the store',
  'sync.fulfillment.ON': 'Send the courier and tracking number to the store after booking',
  'sync.location': 'Shopify location that holds your stock',
  'sync.chooseLocation': 'Choose a location',
  'sync.save': 'Save sync settings',
  'sync.saved': 'Sync settings saved.',
  'sync.blocker.RECONNECT_FOR_PERMISSION': 'Reconnect the store to allow this.',
  'sync.blocker.CHOOSE_LOCATION': 'Choose which Shopify location holds your stock.',
  'sync.blocker.USE_API_AND_WEBHOOKS': 'A custom website syncs through its API key and webhooks.',
  'sync.reconnect': 'Reconnect to allow',
  'sync.reconnectHint': 'Shopify will ask you to allow: {scopes}',
  'sync.statusMap': 'What each ecomsbd status becomes in the store',
  'sync.notPushed': 'Not sent — the store has no matching status',
  'sync.state.CONFIRMED': 'Confirmed',
  'sync.state.CANCELLED': 'Cancelled',
  'sync.state.FULFILLED': 'Booked with courier',
  'sync.state.DELIVERED': 'Delivered',
  'sync.state.RETURNED': 'Returned',
  'sync.lastCatalog': 'Store products last checked',
  'sync.lastInventory': 'Stock last compared',
  'sync.every5': 'Stock is compared every 5 minutes. A change made in the store waits 30 minutes for its order to arrive before it is called a conflict.',
  'map.title': 'Product mapping',
  'map.hint': 'Matched by the store’s own product ID or an exact SKU. Never by name.',
  'map.sync': 'Check store products now',
  'map.syncQueued': 'Checking store products. Refresh in a minute.',
  'map.search': 'Search name or SKU',
  'map.all': 'All',
  'map.state.MATCHED': 'Matched',
  'map.state.UNMATCHED': 'Not matched',
  'map.state.CONFLICT': 'Needs a decision',
  'map.state.IGNORED': 'Ignored',
  'map.state.DELETED': 'Removed from store',
  'map.col.store': 'Store product',
  'map.col.sku': 'SKU',
  'map.col.ecomsbd': 'ecomsbd product',
  'map.col.stock': 'Store stock',
  'map.col.state': 'State',
  'map.choose': 'Match',
  'map.product': 'ecomsbd product',
  'map.variant': 'Variant',
  'map.save': 'Save match',
  'map.unmap': 'Unmatch',
  'map.ignore': 'Ignore this item',
  'map.none': 'No store products yet. Turn on product matching in Sync settings, then check store products.',
  'map.source.SKU': 'by SKU',
  'map.source.MANUAL': 'by you',
  'map.source.CREATED': 'added from the store',
  'map.notTracked': 'Not counted in store',
  'conf.title': 'Conflicts',
  'conf.hint': 'Things ecomsbd will not decide alone. Nothing changes until you choose.',
  'conf.empty': 'No conflicts.',
  'conf.recommended': 'Recommended',
  'conf.ecomsbd': 'ecomsbd',
  'conf.store': 'Store',
  'conf.available': '{count} available',
  'conf.lastAgreed': 'Last agreed: {count}',
  'conf.kind.SKU_AMBIGUOUS': 'This SKU fits more than one ecomsbd product',
  'conf.kind.SKU_DUPLICATE': 'Another store product already uses this ecomsbd product',
  'conf.kind.EXTERNAL_ITEM_DELETED': 'This product was removed from the store',
  'conf.kind.STOCK_INITIAL_MISMATCH': 'Stock differs between the store and ecomsbd',
  'conf.kind.STOCK_CHANGED_EXTERNALLY': 'Stock was changed in the store',
  'conf.kind.STOCK_CHANGED_IN_ECOMSBD': 'Stock was changed in ecomsbd while the store is in charge',
  'conf.kind.STOCK_CHANGED_BOTH': 'Stock changed in both places',
  'conf.kind.CANCELLED_AFTER_BOOKING': 'Cancelled by the store or website after the courier was booked',
  'conf.kind.ORDER_CHANGED_EXTERNALLY': 'The order was changed in the store after it arrived',
  'conf.kind.STATUS_DIVERGED': 'The store shows a different state from ecomsbd',
  'conf.action.MAP_MANUALLY': 'Match it by hand',
  'conf.action.IGNORE_ITEM': 'Ignore this item',
  'conf.action.DISMISS': 'Dismiss',
  'conf.action.UNMAP': 'Unmatch it',
  'conf.action.USE_ECOMSBD': 'Use the ecomsbd count',
  'conf.action.USE_EXTERNAL': 'Use the store count',
  'conf.action.ACCEPT_DIFFERENCE': 'Keep both as they are',
  'conf.action.CONTACT_COURIER': 'Contact the courier to stop the parcel',
  'conf.action.KEEP_ORDER': 'Keep the order',
  'conf.action.HANDLED_WITH_COURIER': 'Sorted with the courier',
  'conf.action.REVIEW_ORDER': 'Check the order',
  'conf.action.MARK_REVIEWED': 'I have checked it',
  'int.op.PUSH_INVENTORY': 'Stock sent to the store',
  'int.op.PUSH_PRICE': 'Price sent to the store',
  'int.op.PUSH_CANCEL': 'Cancellation sent to the store',
  'int.op.PUSH_CONFIRM': 'Confirmation sent to the store',
  'int.op.PUSH_FULFILLMENT': 'Courier tracking sent to the store',
  'int.op.PUSH_DELIVERED': 'Delivery sent to the store',
  'int.col.conflicts': 'Conflicts',
  'int.tile.conflicts': 'Conflicts to decide',
  'int.sync.kind.CATALOG': 'Product check',
  'int.code.STOCK_CHANGED_DURING_PUSH': 'Stock changed in the store at the same moment — checked again next time',
  'int.code.NOT_STOCKED_AT_LOCATION': 'This item is not stocked at the chosen Shopify location',
  'int.code.NOTHING_TO_FULFILL': 'Nothing left to fulfil in the store',
  'int.code.NOT_SUPPORTED_BY_PROVIDER': 'The store has no matching status',
  'int.code.STORE_STATUS_FINAL': 'The store order is already finished there',
  'int.code.MAPPING_CHANGED': 'The product match changed before this was sent',
  'int.code.NO_LONGER_WANTED': 'The order changed again before this was sent',
  'int.code.CANCELLED_FROM_STORE': 'Cancelled in ecomsbd because the store cancelled it',
  'int.code.CONFLICT_OPENED': 'Waiting for your decision under Conflicts',
  'int.code.CANCELLED_AFTER_BOOKING': 'Cancelled after the courier was booked',
  'int.code.ALREADY_MAPPED': 'Another store product already uses that ecomsbd product',
  'int.code.VARIANT_REQUIRED': 'Choose which variant this item is',
  'int.code.RECONNECT_FOR_PERMISSION': 'Reconnect the store to allow this',
  'int.code.CHOOSE_LOCATION': 'Choose the Shopify location first',
  'int.code.CATALOG_OFF': 'Turn on product matching first',
  'int.code.CONFLICT_CLOSED': 'This conflict was already settled',
  'int.code.UNKNOWN_ACTION': 'Choose one of the offered actions',
  'int.dev.stockWrite': 'Let the website change stock',
  'int.dev.stockWriteHint': 'Only if your website keeps its own stock count. Every change is recorded in stock history.',
  'int.dev.part.orderStatus': 'Confirm or cancel from your website',
  'int.dev.part.lookup': 'Find a product or variant by SKU',
  'int.dev.part.stock': 'Change stock from your website',
  'int.dev.part.events': 'Receive status, tracking and stock events',
  'int.dev.part.errors': 'Handle conflicts and errors',
  'inv.reason.EXTERNAL_SYNC': 'Matched to the store’s stock',
} as const;

export const syncBn: Record<keyof typeof syncEn, string> = {
  'sync.tab.overview': 'সারসংক্ষেপ',
  'sync.tab.settings': 'সিঙ্ক সেটিংস',
  'sync.tab.mapping': 'পণ্য মেলানো',
  'sync.tab.conflicts': 'অমিল',
  'sync.title': 'কোনটার দায়িত্ব কার',
  'sync.hint': 'প্রতিটি বিষয়ের দায়িত্ব কার, বেছে নিন। আপনি চালু না করা পর্যন্ত স্টোর বা স্টকে কিছুই বদলাবে না।',
  'sync.orders': 'অর্ডার',
  'sync.ordersFixed': 'স্টোরের নতুন অর্ডার সবসময় ecomsbd-এ আসে। প্যাকিং, কুরিয়ার আর টাকার হিসাব ecomsbd চালায়।',
  'sync.catalog': 'স্টোরের পণ্য ecomsbd-এর পণ্যের সঙ্গে মেলান',
  'sync.products': 'পণ্যের তথ্য',
  'sync.products.MANUAL': 'আমি নিজে পণ্য মেলাব — কোনো দিকে কিছু কপি হবে না',
  'sync.products.EXTERNAL': 'স্টোরের দায়িত্বে — স্টোরের নতুন পণ্য ecomsbd-এ যোগ হবে, স্টোরের দাম ecomsbd-এ বসবে',
  'sync.products.ECOMSBD': 'ecomsbd-এর দায়িত্বে — ecomsbd-এ দাম বদলালে স্টোরে যাবে',
  'sync.inventory': 'স্টক',
  'sync.inventory.NONE': 'স্টক সিঙ্ক করবেন না',
  'sync.inventory.ECOMSBD': 'স্টক ecomsbd নিয়ন্ত্রণ করবে — স্টোর ecomsbd থেকে আপডেট হবে',
  'sync.inventory.EXTERNAL': 'স্টক স্টোর নিয়ন্ত্রণ করবে — ecomsbd স্টোরকে অনুসরণ করবে, প্রতিটি বদল স্টক ইতিহাসে থাকবে',
  'sync.order_status': 'অর্ডারের অবস্থা',
  'sync.order_status.OFF': 'অর্ডারের অবস্থা আলাদা রাখুন',
  'sync.order_status.TWO_WAY': 'দুই দিকে — স্টোর যেখানে সমর্থন করে, নিশ্চিত, বাতিল ও ডেলিভারি দুই দিকেই যাবে',
  'sync.fulfillment': 'কুরিয়ার ট্র্যাকিং',
  'sync.fulfillment.OFF': 'স্টোরে ট্র্যাকিং পাঠাবেন না',
  'sync.fulfillment.ON': 'বুকিংয়ের পর কুরিয়ার ও ট্র্যাকিং নম্বর স্টোরে পাঠান',
  'sync.location': 'যে Shopify লোকেশনে আপনার স্টক থাকে',
  'sync.chooseLocation': 'লোকেশন বেছে নিন',
  'sync.save': 'সিঙ্ক সেটিংস সেভ করুন',
  'sync.saved': 'সিঙ্ক সেটিংস সেভ হয়েছে।',
  'sync.blocker.RECONNECT_FOR_PERMISSION': 'এটি চালু করতে স্টোর আবার যুক্ত করুন।',
  'sync.blocker.CHOOSE_LOCATION': 'কোন Shopify লোকেশনে স্টক থাকে, বেছে নিন।',
  'sync.blocker.USE_API_AND_WEBHOOKS': 'নিজস্ব ওয়েবসাইট API কী আর ওয়েবহুক দিয়ে সিঙ্ক হয়।',
  'sync.reconnect': 'অনুমতি দিতে আবার যুক্ত করুন',
  'sync.reconnectHint': 'Shopify এগুলোর অনুমতি চাইবে: {scopes}',
  'sync.statusMap': 'ecomsbd-এর কোন অবস্থা স্টোরে কী হবে',
  'sync.notPushed': 'পাঠানো হয় না — স্টোরে এমন অবস্থা নেই',
  'sync.state.CONFIRMED': 'নিশ্চিত',
  'sync.state.CANCELLED': 'বাতিল',
  'sync.state.FULFILLED': 'কুরিয়ারে বুক করা',
  'sync.state.DELIVERED': 'ডেলিভারি হয়েছে',
  'sync.state.RETURNED': 'ফেরত',
  'sync.lastCatalog': 'স্টোরের পণ্য শেষ দেখা হয়েছে',
  'sync.lastInventory': 'স্টক শেষ মেলানো হয়েছে',
  'sync.every5': 'প্রতি ৫ মিনিটে স্টক মেলানো হয়। স্টোরে কোনো বদল হলে তার অর্ডার আসার জন্য ৩০ মিনিট অপেক্ষা করা হয়, তারপর অমিল ধরা হয়।',
  'map.title': 'পণ্য মেলানো',
  'map.hint': 'স্টোরের নিজস্ব পণ্য আইডি বা হুবহু SKU দিয়ে মেলানো হয়। নাম দিয়ে কখনো নয়।',
  'map.sync': 'এখনই স্টোরের পণ্য দেখুন',
  'map.syncQueued': 'স্টোরের পণ্য দেখা হচ্ছে। এক মিনিট পর রিফ্রেশ করুন।',
  'map.search': 'নাম বা SKU খুঁজুন',
  'map.all': 'সব',
  'map.state.MATCHED': 'মিলেছে',
  'map.state.UNMATCHED': 'মেলেনি',
  'map.state.CONFLICT': 'সিদ্ধান্ত দরকার',
  'map.state.IGNORED': 'বাদ রাখা',
  'map.state.DELETED': 'স্টোর থেকে সরানো',
  'map.col.store': 'স্টোরের পণ্য',
  'map.col.sku': 'SKU',
  'map.col.ecomsbd': 'ecomsbd-এর পণ্য',
  'map.col.stock': 'স্টোরের স্টক',
  'map.col.state': 'অবস্থা',
  'map.choose': 'মেলান',
  'map.product': 'ecomsbd-এর পণ্য',
  'map.variant': 'ভ্যারিয়েন্ট',
  'map.save': 'মেলানো সেভ করুন',
  'map.unmap': 'মেলানো সরান',
  'map.ignore': 'এই পণ্যটি বাদ রাখুন',
  'map.none': 'এখনো স্টোরের কোনো পণ্য নেই। সিঙ্ক সেটিংসে পণ্য মেলানো চালু করে স্টোরের পণ্য দেখুন।',
  'map.source.SKU': 'SKU দিয়ে',
  'map.source.MANUAL': 'আপনি মিলিয়েছেন',
  'map.source.CREATED': 'স্টোর থেকে যোগ হয়েছে',
  'map.notTracked': 'স্টোরে গোনা হয় না',
  'conf.title': 'অমিল',
  'conf.hint': 'যেগুলো ecomsbd একা ঠিক করবে না। আপনি বেছে না নেওয়া পর্যন্ত কিছু বদলাবে না।',
  'conf.empty': 'কোনো অমিল নেই।',
  'conf.recommended': 'প্রস্তাবিত',
  'conf.ecomsbd': 'ecomsbd',
  'conf.store': 'স্টোর',
  'conf.available': '{count}টি বিক্রির জন্য আছে',
  'conf.lastAgreed': 'শেষবার মিলেছিল: {count}',
  'conf.kind.SKU_AMBIGUOUS': 'এই SKU ecomsbd-এর একাধিক পণ্যের সঙ্গে মেলে',
  'conf.kind.SKU_DUPLICATE': 'স্টোরের আরেকটি পণ্য আগে থেকেই এই ecomsbd পণ্যের সঙ্গে মেলানো',
  'conf.kind.EXTERNAL_ITEM_DELETED': 'পণ্যটি স্টোর থেকে সরানো হয়েছে',
  'conf.kind.STOCK_INITIAL_MISMATCH': 'স্টোর আর ecomsbd-এ স্টক আলাদা',
  'conf.kind.STOCK_CHANGED_EXTERNALLY': 'স্টোরে স্টক বদলানো হয়েছে',
  'conf.kind.STOCK_CHANGED_IN_ECOMSBD': 'স্টোরের দায়িত্বে থাকা অবস্থায় ecomsbd-এ স্টক বদলানো হয়েছে',
  'conf.kind.STOCK_CHANGED_BOTH': 'দুই জায়গাতেই স্টক বদলেছে',
  'conf.kind.CANCELLED_AFTER_BOOKING': 'কুরিয়ার বুকিংয়ের পর স্টোর বা ওয়েবসাইট অর্ডার বাতিল করেছে',
  'conf.kind.ORDER_CHANGED_EXTERNALLY': 'অর্ডার আসার পর স্টোরে বদলানো হয়েছে',
  'conf.kind.STATUS_DIVERGED': 'স্টোরে ecomsbd থেকে আলাদা অবস্থা দেখাচ্ছে',
  'conf.action.MAP_MANUALLY': 'নিজে মেলান',
  'conf.action.IGNORE_ITEM': 'এই পণ্যটি বাদ রাখুন',
  'conf.action.DISMISS': 'বাদ দিন',
  'conf.action.UNMAP': 'মেলানো সরান',
  'conf.action.USE_ECOMSBD': 'ecomsbd-এর হিসাব রাখুন',
  'conf.action.USE_EXTERNAL': 'স্টোরের হিসাব রাখুন',
  'conf.action.ACCEPT_DIFFERENCE': 'দুটোই যেমন আছে রাখুন',
  'conf.action.CONTACT_COURIER': 'পার্সেল থামাতে কুরিয়ারের সঙ্গে যোগাযোগ করুন',
  'conf.action.KEEP_ORDER': 'অর্ডার রেখে দিন',
  'conf.action.HANDLED_WITH_COURIER': 'কুরিয়ারের সঙ্গে মিটিয়ে নিয়েছি',
  'conf.action.REVIEW_ORDER': 'অর্ডারটি দেখে নিন',
  'conf.action.MARK_REVIEWED': 'দেখে নিয়েছি',
  'int.op.PUSH_INVENTORY': 'স্টক স্টোরে পাঠানো হয়েছে',
  'int.op.PUSH_PRICE': 'দাম স্টোরে পাঠানো হয়েছে',
  'int.op.PUSH_CANCEL': 'বাতিলের খবর স্টোরে পাঠানো হয়েছে',
  'int.op.PUSH_CONFIRM': 'নিশ্চিতের খবর স্টোরে পাঠানো হয়েছে',
  'int.op.PUSH_FULFILLMENT': 'কুরিয়ার ট্র্যাকিং স্টোরে পাঠানো হয়েছে',
  'int.op.PUSH_DELIVERED': 'ডেলিভারির খবর স্টোরে পাঠানো হয়েছে',
  'int.col.conflicts': 'অমিল',
  'int.tile.conflicts': 'যে অমিলে সিদ্ধান্ত দরকার',
  'int.sync.kind.CATALOG': 'পণ্য দেখা',
  'int.code.STOCK_CHANGED_DURING_PUSH': 'একই সময়ে স্টোরে স্টক বদলেছে — পরেরবার আবার দেখা হবে',
  'int.code.NOT_STOCKED_AT_LOCATION': 'বেছে নেওয়া Shopify লোকেশনে এই পণ্যের স্টক রাখা হয় না',
  'int.code.NOTHING_TO_FULFILL': 'স্টোরে পাঠানোর মতো আর কিছু বাকি নেই',
  'int.code.NOT_SUPPORTED_BY_PROVIDER': 'স্টোরে এমন অবস্থা নেই',
  'int.code.STORE_STATUS_FINAL': 'স্টোরে অর্ডারটি আগেই শেষ হয়ে গেছে',
  'int.code.MAPPING_CHANGED': 'পাঠানোর আগেই পণ্যের মেলানো বদলে গেছে',
  'int.code.NO_LONGER_WANTED': 'পাঠানোর আগেই অর্ডার আবার বদলেছে',
  'int.code.CANCELLED_FROM_STORE': 'স্টোর বাতিল করায় ecomsbd-এও বাতিল হয়েছে',
  'int.code.CONFLICT_OPENED': 'অমিলে আপনার সিদ্ধান্তের অপেক্ষায়',
  'int.code.CANCELLED_AFTER_BOOKING': 'কুরিয়ার বুকিংয়ের পর বাতিল',
  'int.code.ALREADY_MAPPED': 'স্টোরের আরেকটি পণ্য আগে থেকেই ওই ecomsbd পণ্যের সঙ্গে মেলানো',
  'int.code.VARIANT_REQUIRED': 'কোন ভ্যারিয়েন্ট, বেছে নিন',
  'int.code.RECONNECT_FOR_PERMISSION': 'এটি চালু করতে স্টোর আবার যুক্ত করুন',
  'int.code.CHOOSE_LOCATION': 'আগে Shopify লোকেশন বেছে নিন',
  'int.code.CATALOG_OFF': 'আগে পণ্য মেলানো চালু করুন',
  'int.code.CONFLICT_CLOSED': 'এই অমিল আগেই মিটে গেছে',
  'int.code.UNKNOWN_ACTION': 'দেওয়া বিকল্পগুলোর একটি বেছে নিন',
  'int.dev.stockWrite': 'ওয়েবসাইটকে স্টক বদলাতে দিন',
  'int.dev.stockWriteHint': 'শুধু যদি ওয়েবসাইট নিজের স্টক গোনে। প্রতিটি বদল স্টক ইতিহাসে থাকবে।',
  'int.dev.part.orderStatus': 'ওয়েবসাইট থেকে নিশ্চিত বা বাতিল করুন',
  'int.dev.part.lookup': 'SKU দিয়ে পণ্য বা ভ্যারিয়েন্ট খুঁজুন',
  'int.dev.part.stock': 'ওয়েবসাইট থেকে স্টক বদলান',
  'int.dev.part.events': 'অবস্থা, ট্র্যাকিং ও স্টকের ইভেন্ট নিন',
  'int.dev.part.errors': 'অমিল আর সমস্যা সামলান',
  'inv.reason.EXTERNAL_SYNC': 'স্টোরের স্টকের সঙ্গে মেলানো',
};
