import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../core/api/api_error.dart';
import '../../data/account/models.dart';
import '../../data/billing/billing_providers.dart';
import '../../design/components/badges.dart';
import '../../design/components/surfaces.dart';
import '../../design/glass.dart';
import '../../design/tokens.dart';
import '../billing/plans_screen.dart' show formatDay;
import '../shared/responsive.dart';
import 'settings_screen.dart' show SettingsError;

/// Export your data, or close your account.
///
/// Master spec sections 99 and 100. The screen is built around one obligation:
/// **say what will actually happen before the seller agrees to it.** The
/// retention wording comes from the server, so the sentence a seller reads is
/// generated by the same code that carries it out — it cannot drift into a
/// promise the software does not keep.
class DataPrivacyScreen extends ConsumerWidget {
  const DataPrivacyScreen({super.key});

  static const List<({String kind, String label})> _exports =
      <({String kind, String label})>[
        (kind: 'ORDERS', label: 'Orders'),
        (kind: 'CUSTOMERS', label: 'Customers'),
        (kind: 'PRODUCTS', label: 'Products'),
        (kind: 'PAYOUTS', label: 'Payouts'),
        (kind: 'RECONCILIATION', label: 'COD reconciliation'),
        (kind: 'PROFIT_SUMMARY', label: 'Profit summary'),
      ];

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final privacy = ref.watch(privacyStatusProvider);

    return Scaffold(
      backgroundColor: EcomsbdColors.background,
      body: EcomsbdBackground(
        child: SafeArea(
          child: ContentWidthLimit(
            child: ListView(
              padding: const EdgeInsets.fromLTRB(
                EcomsbdSpacing.page,
                EcomsbdLayout.pushedTopPadding,
                EcomsbdSpacing.page,
                EcomsbdSpacing.xxl,
              ),
              children: <Widget>[
                Row(
                  children: <Widget>[
                    IconButton(
                      onPressed: () => Navigator.of(context).maybePop(),
                      icon: const Icon(Icons.arrow_back_rounded),
                      tooltip: 'Back',
                    ),
                    const Expanded(
                      child: Text('Your data', style: EcomsbdType.pageTitle),
                    ),
                  ],
                ),

                const SectionHeader(
                  title: 'Export',
                  subtitle: 'A CSV of your own records, ready to download',
                ),
                const _ExportSection(kinds: _exports),

                const SectionHeader(title: 'Closing your account'),
                privacy.when(
                  loading: () => const Padding(
                    padding: EdgeInsets.all(EcomsbdSpacing.lg),
                    child: Center(child: CircularProgressIndicator()),
                  ),
                  error: (error, _) => SettingsError(
                    error: error,
                    onRetry: () => ref.invalidate(privacyStatusProvider),
                  ),
                  data: (status) => _DeletionSection(status: status),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

class _ExportSection extends ConsumerStatefulWidget {
  const _ExportSection({required this.kinds});

  final List<({String kind, String label})> kinds;

  @override
  ConsumerState<_ExportSection> createState() => _ExportSectionState();
}

class _ExportSectionState extends ConsumerState<_ExportSection> {
  String? _busyKind;

  @override
  Widget build(BuildContext context) {
    final exports = ref.watch(exportsProvider);

    return Column(
      children: <Widget>[
        GlassCard(
          child: Column(
            children: <Widget>[
              for (var index = 0; index < widget.kinds.length; index++) ...[
                if (index > 0) const Divider(height: EcomsbdSpacing.lg),
                Row(
                  children: <Widget>[
                    Expanded(
                      child: Text(
                        widget.kinds[index].label,
                        style: EcomsbdType.bodyStrong,
                      ),
                    ),
                    TextButton(
                      onPressed: _busyKind == null
                          ? () => _request(widget.kinds[index].kind)
                          : null,
                      style: TextButton.styleFrom(
                        minimumSize: const Size(0, EcomsbdTouch.minTarget),
                      ),
                      child: Text(
                        _busyKind == widget.kinds[index].kind
                            ? 'Preparing…'
                            : 'Export',
                      ),
                    ),
                  ],
                ),
              ],
            ],
          ),
        ),
        exports.maybeWhen(
          data: (rows) => rows.isEmpty
              ? const SizedBox.shrink()
              : Padding(
                  padding: const EdgeInsets.only(top: EcomsbdSpacing.sm),
                  child: GlassCard(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: <Widget>[
                        const Text(
                          'Recent exports',
                          style: EcomsbdType.sectionTitle,
                        ),
                        const SizedBox(height: EcomsbdSpacing.sm),
                        for (final job in rows.take(5))
                          Padding(
                            padding: const EdgeInsets.only(bottom: 6),
                            child: Row(
                              children: <Widget>[
                                Expanded(
                                  child: Text(
                                    '${job.label} · ${job.rowCount} rows',
                                    style: EcomsbdType.caption.copyWith(
                                      color: EcomsbdColors.muted,
                                    ),
                                  ),
                                ),
                                StatusChip(
                                  label: job.hasExpired
                                      ? 'Link expired'
                                      : job.isReady
                                      ? 'Ready'
                                      : job.status,
                                  tone: job.hasExpired
                                      ? Tone.neutral
                                      : Tone.good,
                                ),
                              ],
                            ),
                          ),
                        const SizedBox(height: 4),
                        Text(
                          'Download links expire quickly on purpose — an '
                          'export is a copy of your shop behind a link.',
                          style: EcomsbdType.caption.copyWith(
                            color: EcomsbdColors.muted2,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
          orElse: () => const SizedBox.shrink(),
        ),
      ],
    );
  }

  Future<void> _request(String kind) async {
    setState(() => _busyKind = kind);
    final messenger = ScaffoldMessenger.of(context);
    try {
      final job = await ref
          .read(accountRepositoryProvider)
          .createExport(kind: kind);
      ref.invalidate(exportsProvider);

      // The token comes back exactly once. The screen says so rather than
      // implying the seller can come back for it later.
      messenger.showSnackBar(
        SnackBar(
          content: Text(
            job.rowCount == 0
                ? 'Nothing to export yet for ${job.label.toLowerCase()}.'
                : '${job.label}: ${job.rowCount} rows ready. '
                      'The download link works for a short time only.',
          ),
        ),
      );
    } on ApiError catch (error) {
      messenger.showSnackBar(SnackBar(content: Text(error.displayMessage)));
    } finally {
      if (mounted) setState(() => _busyKind = null);
    }
  }
}

class _DeletionSection extends ConsumerStatefulWidget {
  const _DeletionSection({required this.status});

  final PrivacyStatus status;

  @override
  ConsumerState<_DeletionSection> createState() => _DeletionSectionState();
}

class _DeletionSectionState extends ConsumerState<_DeletionSection> {
  bool _busy = false;

  @override
  Widget build(BuildContext context) {
    final status = widget.status;

    if (status.deletionRequested) {
      return GlassSurface(
        fill: Tone.warning.surface,
        borderColor: Tone.warning.ink.withValues(alpha: 0.2),
        borderRadius: EcomsbdRadii.cardLarge,
        padding: const EdgeInsets.all(EcomsbdSpacing.md),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            const Text(
              'Your account will close',
              style: EcomsbdType.sectionTitle,
            ),
            const SizedBox(height: 6),
            Text(
              status.scheduledFor == null
                  ? 'Deletion is scheduled.'
                  : 'On ${formatDay(status.scheduledFor!)}. Everything works '
                        'normally until then, and you can change your mind.',
              style: EcomsbdType.caption.copyWith(color: EcomsbdColors.muted),
            ),
            const SizedBox(height: EcomsbdSpacing.md),
            SizedBox(
              width: double.infinity,
              child: FilledButton(
                onPressed: _busy ? null : _cancel,
                style: FilledButton.styleFrom(
                  minimumSize: const Size(0, EcomsbdTouch.minTarget),
                  shape: const StadiumBorder(),
                ),
                child: Text(_busy ? 'Cancelling…' : 'Keep my account'),
              ),
            ),
          ],
        ),
      );
    }

    return Column(
      children: <Widget>[
        GlassCard(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              Text(status.retentionNote, style: EcomsbdType.caption),
              const SizedBox(height: EcomsbdSpacing.md),
              _List(
                title: 'Permanently removed',
                items: status.anonymisedOnDeletion,
                tone: Tone.bad,
              ),
              const SizedBox(height: EcomsbdSpacing.sm),
              _List(
                title: 'Kept, with names and numbers removed',
                items: status.retainedAfterDeletion,
                tone: Tone.info,
              ),
            ],
          ),
        ),
        const SizedBox(height: EcomsbdSpacing.sm),
        SizedBox(
          width: double.infinity,
          child: OutlinedButton(
            onPressed: _busy ? null : _requestDeletion,
            style: OutlinedButton.styleFrom(
              foregroundColor: Tone.bad.ink,
              minimumSize: const Size(0, EcomsbdTouch.minTarget),
              shape: const StadiumBorder(),
            ),
            child: const Text('Close my account'),
          ),
        ),
        const SizedBox(height: EcomsbdSpacing.xs),
        Text(
          'You will have ${status.graceDays} days to change your mind, and '
          'everything keeps working during them.',
          textAlign: TextAlign.center,
          style: EcomsbdType.caption.copyWith(color: EcomsbdColors.muted2),
        ),
      ],
    );
  }

  Future<void> _requestDeletion() async {
    final controller = TextEditingController();
    final messenger = ScaffoldMessenger.of(context);

    final confirmed = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Close this shop?'),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            const Text(
              'Type CLOSE to confirm. Nothing happens immediately — you will '
              'have time to change your mind.',
            ),
            const SizedBox(height: EcomsbdSpacing.md),
            TextField(
              controller: controller,
              autofocus: true,
              decoration: const InputDecoration(hintText: 'CLOSE'),
              textCapitalization: TextCapitalization.characters,
            ),
          ],
        ),
        actions: <Widget>[
          TextButton(
            onPressed: () => Navigator.of(context).pop(false),
            child: const Text('Cancel'),
          ),
          // Typed confirmation, not a checkbox. This is the one action in the
          // product a seller cannot undo by tapping again.
          ValueListenableBuilder<TextEditingValue>(
            valueListenable: controller,
            builder: (context, value, _) => FilledButton(
              onPressed: value.text.trim().toUpperCase() == 'CLOSE'
                  ? () => Navigator.of(context).pop(true)
                  : null,
              child: const Text('Close my account'),
            ),
          ),
        ],
      ),
    );
    controller.dispose();
    if (!(confirmed ?? false)) return;

    setState(() => _busy = true);
    try {
      final schedule = await ref
          .read(accountRepositoryProvider)
          .requestDeletion(confirm: 'CLOSE');
      ref.invalidate(privacyStatusProvider);
      messenger.showSnackBar(
        SnackBar(
          content: Text(
            'Your account will close on ${formatDay(schedule.scheduledFor)}.',
          ),
        ),
      );
    } on ApiError catch (error) {
      messenger.showSnackBar(SnackBar(content: Text(error.displayMessage)));
    } finally {
      if (mounted) setState(() => _busy = false);
    }
  }

  Future<void> _cancel() async {
    setState(() => _busy = true);
    final messenger = ScaffoldMessenger.of(context);
    try {
      await ref.read(accountRepositoryProvider).cancelDeletion();
      ref.invalidate(privacyStatusProvider);
      messenger.showSnackBar(
        const SnackBar(content: Text('Your account will stay open.')),
      );
    } on ApiError catch (error) {
      messenger.showSnackBar(SnackBar(content: Text(error.displayMessage)));
    } finally {
      if (mounted) setState(() => _busy = false);
    }
  }
}

class _List extends StatelessWidget {
  const _List({required this.title, required this.items, required this.tone});

  final String title;
  final List<String> items;
  final Tone tone;

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        Text(title, style: EcomsbdType.chip.copyWith(color: tone.ink)),
        const SizedBox(height: 4),
        for (final item in items)
          Padding(
            padding: const EdgeInsets.only(bottom: 2),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: <Widget>[
                const Text('· ', style: EcomsbdType.caption),
                Expanded(
                  child: Text(
                    item,
                    style: EcomsbdType.caption.copyWith(
                      color: EcomsbdColors.muted,
                    ),
                  ),
                ),
              ],
            ),
          ),
      ],
    );
  }
}
