import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:url_launcher/url_launcher.dart';

import '../../core/api/api_error.dart';
import '../../data/account/models.dart';
import '../../data/billing/billing_providers.dart';
import '../../design/components/badges.dart';
import '../../design/components/surfaces.dart';
import '../../design/glass.dart';
import '../../design/tokens.dart';
import '../billing/plans_screen.dart' show formatDay;
import '../shared/responsive.dart';
import 'settings_screen.dart' show SettingsError;
import '../../l10n/app_strings.dart';
import '../../l10n/app_locale.dart';

/// Export your data, or close your account.
///
/// Master spec sections 99 and 100. The screen is built around one obligation:
/// **say what will actually happen before the seller agrees to it.** The
/// retention wording comes from the server, so the sentence a seller reads is
/// generated by the same code that carries it out — it cannot drift into a
/// promise the software does not keep.
class DataPrivacyScreen extends ConsumerWidget {
  const DataPrivacyScreen({super.key});

  /// Export kinds with the key their wording lives under; the kind itself is
  /// API contract. Resolved where rendered -- a const list cannot look up.
  static const List<({String kind, String labelKey})> _exports =
      <({String kind, String labelKey})>[
        (kind: 'ORDERS', labelKey: 'orders.title'),
        (kind: 'CUSTOMERS', labelKey: 'entity.customers'),
        (kind: 'PRODUCTS', labelKey: 'entity.products'),
        (kind: 'PAYOUTS', labelKey: 'money.payouts'),
        (kind: 'RECONCILIATION', labelKey: 'priv.codReconciliation'),
        (kind: 'PROFIT_SUMMARY', labelKey: 'priv.profitSummary'),
      ];

  Future<void> _openLegalPage(BuildContext context, String path) async {
    final localizedPath = AppStrings.of(context).locale == AppLocale.bn
        ? '$path/bn'
        : path;
    var opened = false;
    try {
      opened = await launchUrl(
        Uri.https('scalemyprints.com', localizedPath),
        mode: LaunchMode.externalApplication,
      );
    } catch (_) {
      // Keep the address available when no browser can open it.
    }
    if (!opened && context.mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(context.tr('priv.legalOpenError', <String, Object?>{
            'url': 'https://scalemyprints.com$localizedPath',
          })),
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final privacy = ref.watch(privacyStatusProvider);

    return Scaffold(
      backgroundColor: EcomsbdColors.background,
      body: EcomsbdBackground(
        child: SafeArea(
          child: ContentWidthLimit(
            child: ListView(
              padding: const EdgeInsets.fromLTRB(
                EcomsbdSpacing.page,
                EcomsbdLayout.pushedTopPadding,
                EcomsbdSpacing.page,
                EcomsbdSpacing.xxl,
              ),
              children: <Widget>[
                Row(
                  children: <Widget>[
                    IconButton(
                      onPressed: () => Navigator.of(context).maybePop(),
                      icon: const Icon(Icons.arrow_back_rounded),
                      tooltip: context.tr('common.back'),
                    ),
                    Expanded(
                      child: Text(
                        context.tr('priv.title'),
                        style: EcomsbdType.pageTitle,
                      ),
                    ),
                  ],
                ),

                GlassCard(
                  child: ListTile(
                    contentPadding: EdgeInsets.zero,
                    leading: const Icon(Icons.policy_outlined),
                    title: Text(context.tr('priv.policy')),
                    subtitle: const Text('scalemyprints.com/privacy-policy'),
                    trailing: const Icon(Icons.open_in_new_rounded),
                    onTap: () => _openLegalPage(context, '/privacy-policy'),
                  ),
                ),

                SectionHeader(
                  title: context.tr('priv.export'),
                  subtitle: context.tr('priv.exportSub'),
                ),
                const _ExportSection(kinds: _exports),

                SectionHeader(title: context.tr('priv.closingAccount')),
                TextButton.icon(
                  onPressed: () => _openLegalPage(context, '/account-deletion'),
                  icon: const Icon(Icons.open_in_new_rounded, size: 18),
                  label: Text(context.tr('priv.deletionHelp')),
                ),
                privacy.when(
                  loading: () => const Padding(
                    padding: EdgeInsets.all(EcomsbdSpacing.lg),
                    child: Center(child: CircularProgressIndicator()),
                  ),
                  error: (error, _) => SettingsError(
                    error: error,
                    onRetry: () => ref.invalidate(privacyStatusProvider),
                  ),
                  data: (status) => _DeletionSection(status: status),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

class _ExportSection extends ConsumerStatefulWidget {
  const _ExportSection({required this.kinds});

  final List<({String kind, String labelKey})> kinds;

  @override
  ConsumerState<_ExportSection> createState() => _ExportSectionState();
}

class _ExportSectionState extends ConsumerState<_ExportSection> {
  String? _busyKind;

  @override
  Widget build(BuildContext context) {
    final exports = ref.watch(exportsProvider);

    return Column(
      children: <Widget>[
        GlassCard(
          child: Column(
            children: <Widget>[
              for (var index = 0; index < widget.kinds.length; index++) ...[
                if (index > 0) const Divider(height: EcomsbdSpacing.lg),
                Row(
                  children: <Widget>[
                    Expanded(
                      child: Text(
                        context.tr(widget.kinds[index].labelKey),
                        style: EcomsbdType.bodyStrong,
                      ),
                    ),
                    TextButton(
                      onPressed: _busyKind == null
                          ? () => _request(widget.kinds[index].kind)
                          : null,
                      style: TextButton.styleFrom(
                        minimumSize: const Size(0, EcomsbdTouch.minTarget),
                      ),
                      child: Text(
                        _busyKind == widget.kinds[index].kind
                            ? context.tr('priv.preparing')
                            : context.tr('priv.export'),
                      ),
                    ),
                  ],
                ),
              ],
            ],
          ),
        ),
        exports.maybeWhen(
          data: (rows) => rows.isEmpty
              ? const SizedBox.shrink()
              : Padding(
                  padding: const EdgeInsets.only(top: EcomsbdSpacing.sm),
                  child: GlassCard(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: <Widget>[
                        Text(
                          context.tr('priv.recentExports'),
                          style: EcomsbdType.sectionTitle,
                        ),
                        const SizedBox(height: EcomsbdSpacing.sm),
                        for (final job in rows.take(5))
                          Padding(
                            padding: const EdgeInsets.only(bottom: 6),
                            child: Row(
                              children: <Widget>[
                                Expanded(
                                  child: Text(
                                    '${job.label} · ${job.rowCount} rows',
                                    style: EcomsbdType.caption.copyWith(
                                      color: EcomsbdColors.muted,
                                    ),
                                  ),
                                ),
                                StatusChip(
                                  label: job.hasExpired
                                      ? context.tr('priv.linkExpired')
                                      : job.isReady
                                      ? context.tr('priv.ready')
                                      : job.status,
                                  tone: job.hasExpired
                                      ? Tone.neutral
                                      : Tone.good,
                                ),
                              ],
                            ),
                          ),
                        const SizedBox(height: 4),
                        Text(
                          context.tr('priv.linkNote'),
                          style: EcomsbdType.caption.copyWith(
                            color: EcomsbdColors.muted2,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
          orElse: () => const SizedBox.shrink(),
        ),
      ],
    );
  }

  Future<void> _request(String kind) async {
    setState(() => _busyKind = kind);
    final messenger = ScaffoldMessenger.of(context);
    // Resolved before the await: the copy is locale-bound, not
    // context-bound, so it outlives the gap.
    final strings = context.strings;
    try {
      final job = await ref
          .read(accountRepositoryProvider)
          .createExport(kind: kind);
      ref.invalidate(exportsProvider);

      // The token comes back exactly once. The screen says so rather than
      // implying the seller can come back for it later.
      messenger.showSnackBar(
        SnackBar(
          content: Text(
            job.rowCount == 0
                ? strings.t('priv.exportEmpty', <String, Object?>{
                    'kind': job.label.toLowerCase(),
                  })
                : strings.t('priv.exportReady', <String, Object?>{
                    'kind': job.label,
                    'rows': job.rowCount,
                  }),
          ),
        ),
      );
    } on ApiError catch (error) {
      messenger.showSnackBar(SnackBar(content: Text(error.displayMessage)));
    } finally {
      if (mounted) setState(() => _busyKind = null);
    }
  }
}

class _DeletionSection extends ConsumerStatefulWidget {
  const _DeletionSection({required this.status});

  final PrivacyStatus status;

  @override
  ConsumerState<_DeletionSection> createState() => _DeletionSectionState();
}

class _DeletionSectionState extends ConsumerState<_DeletionSection> {
  bool _busy = false;

  @override
  Widget build(BuildContext context) {
    final status = widget.status;

    if (status.deletionRequested) {
      return GlassSurface(
        fill: Tone.warning.surface,
        borderColor: Tone.warning.ink.withValues(alpha: 0.2),
        borderRadius: EcomsbdRadii.cardLarge,
        padding: const EdgeInsets.all(EcomsbdSpacing.md),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            Text(context.tr('priv.willClose'), style: EcomsbdType.sectionTitle),
            const SizedBox(height: 6),
            Text(
              status.scheduledFor == null
                  ? context.tr('priv.deletionScheduled')
                  : context.tr('priv.closesOn', <String, Object?>{
                      'date': formatDay(status.scheduledFor!),
                    }),
              style: EcomsbdType.caption.copyWith(color: EcomsbdColors.muted),
            ),
            const SizedBox(height: EcomsbdSpacing.md),
            SizedBox(
              width: double.infinity,
              child: FilledButton(
                onPressed: _busy ? null : _cancel,
                style: FilledButton.styleFrom(
                  minimumSize: const Size(0, EcomsbdTouch.minTarget),
                  shape: const StadiumBorder(),
                ),
                child: Text(
                  _busy
                      ? context.tr('priv.cancelling')
                      : context.tr('priv.keepAccount'),
                ),
              ),
            ),
          ],
        ),
      );
    }

    return Column(
      children: <Widget>[
        GlassCard(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              Text(status.retentionNote, style: EcomsbdType.caption),
              const SizedBox(height: EcomsbdSpacing.md),
              _List(
                title: context.tr('priv.removedPermanently'),
                items: status.anonymisedOnDeletion,
                tone: Tone.bad,
              ),
              const SizedBox(height: EcomsbdSpacing.sm),
              _List(
                title: context.tr('priv.keptAnonymised'),
                items: status.retainedAfterDeletion,
                tone: Tone.info,
              ),
            ],
          ),
        ),
        const SizedBox(height: EcomsbdSpacing.sm),
        SizedBox(
          width: double.infinity,
          child: OutlinedButton(
            onPressed: _busy ? null : _requestDeletion,
            style: OutlinedButton.styleFrom(
              foregroundColor: Tone.bad.ink,
              minimumSize: const Size(0, EcomsbdTouch.minTarget),
              shape: const StadiumBorder(),
            ),
            child: Text(context.tr('priv.closeAccount')),
          ),
        ),
        const SizedBox(height: EcomsbdSpacing.xs),
        Text(
          context.tr('priv.graceDays', <String, Object?>{
            'days': status.graceDays,
          }),
          textAlign: TextAlign.center,
          style: EcomsbdType.caption.copyWith(color: EcomsbdColors.muted2),
        ),
      ],
    );
  }

  Future<void> _requestDeletion() async {
    final controller = TextEditingController();
    final messenger = ScaffoldMessenger.of(context);
    final strings = context.strings;

    final confirmed = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        title: Text(context.tr('priv.closeShopTitle')),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            Text(context.tr('priv.closeShopBody')),
            const SizedBox(height: EcomsbdSpacing.md),
            TextField(
              controller: controller,
              autofocus: true,
              decoration: const InputDecoration(hintText: 'CLOSE'),
              textCapitalization: TextCapitalization.characters,
            ),
          ],
        ),
        actions: <Widget>[
          TextButton(
            onPressed: () => Navigator.of(context).pop(false),
            child: Text(context.tr('common.cancel')),
          ),
          // Typed confirmation, not a checkbox. This is the one action in the
          // product a seller cannot undo by tapping again.
          ValueListenableBuilder<TextEditingValue>(
            valueListenable: controller,
            builder: (context, value, _) => FilledButton(
              onPressed: value.text.trim().toUpperCase() == 'CLOSE'
                  ? () => Navigator.of(context).pop(true)
                  : null,
              child: Text(context.tr('priv.closeAccount')),
            ),
          ),
        ],
      ),
    );
    controller.dispose();
    if (!(confirmed ?? false)) return;

    setState(() => _busy = true);
    try {
      final schedule = await ref
          .read(accountRepositoryProvider)
          .requestDeletion(confirm: 'CLOSE');
      ref.invalidate(privacyStatusProvider);
      messenger.showSnackBar(
        SnackBar(
          content: Text(
            strings.t('priv.willCloseOn', <String, Object?>{
              'date': formatDay(schedule.scheduledFor),
            }),
          ),
        ),
      );
    } on ApiError catch (error) {
      messenger.showSnackBar(SnackBar(content: Text(error.displayMessage)));
    } finally {
      if (mounted) setState(() => _busy = false);
    }
  }

  Future<void> _cancel() async {
    setState(() => _busy = true);
    final messenger = ScaffoldMessenger.of(context);
    final strings = context.strings;
    try {
      await ref.read(accountRepositoryProvider).cancelDeletion();
      ref.invalidate(privacyStatusProvider);
      messenger.showSnackBar(
        SnackBar(content: Text(strings.t('priv.stayOpen'))),
      );
    } on ApiError catch (error) {
      messenger.showSnackBar(SnackBar(content: Text(error.displayMessage)));
    } finally {
      if (mounted) setState(() => _busy = false);
    }
  }
}

class _List extends StatelessWidget {
  const _List({required this.title, required this.items, required this.tone});

  final String title;
  final List<String> items;
  final Tone tone;

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        Text(title, style: EcomsbdType.chip.copyWith(color: tone.ink)),
        const SizedBox(height: 4),
        for (final item in items)
          Padding(
            padding: const EdgeInsets.only(bottom: 2),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: <Widget>[
                const Text('· ', style: EcomsbdType.caption),
                Expanded(
                  child: Text(
                    item,
                    style: EcomsbdType.caption.copyWith(
                      color: EcomsbdColors.muted,
                    ),
                  ),
                ),
              ],
            ),
          ),
      ],
    );
  }
}
