"""couriers: accounts, provider evidence, booking attempts, payments

Phase C, first slice. Master spec sections 5, 31, 47, 62.13, 78, 83, 108.

Eight new tables and seven additive columns on ``consignments``. Nothing
existing is altered or dropped, so the upgrade is safe on a live database and
the downgrade is exact.

*   courier_accounts          — one shop's credentials per provider, AES-GCM at
                                rest, bound to the row id as AAD so an envelope
                                copied elsewhere fails to decrypt. The unique
                                (tenant, provider) key exists because every
                                recovery path has to be able to answer "which
                                credentials booked this parcel?".
*   courier_raw_payloads      — what the provider actually said. Section 83:
                                support must be able to explain a result months
                                later, which a normalized row cannot do.
*   courier_events            — immutable observations, deduplicated on content
                                so hourly polling of one parcel for a week is
                                one row plus a counter rather than 168 rows.
*   courier_booking_attempts  — written *before* the create call goes out. This
                                is the table that makes BOOKING_UNKNOWN
                                recoverable: it holds the exact invoice that was
                                sent, so a lost answer is resolved by asking the
                                provider about that invoice instead of shipping
                                a second parcel.
*   courier_return_requests   — ecomsbd's own duplicate protection, because
                                Steadfast documents no idempotency for return
                                creation. The unique idempotency key stops a
                                double tap before any provider call.
*   courier_provider_payments — one row per provider payment, ever. The unique
                                (tenant, provider, payment id) key is the whole
                                reason a repeated sync cannot double a seller's
                                settled total.
*   courier_sync_cursors      — per-shop watermarks, so a restart resumes and
                                two workers contend on a row lock rather than
                                both importing the same payment.
*   courier_webhook_deliveries— raw inbound bodies, deduplicated by body hash.
                                Deliberately not tenant-owned: a webhook arrives
                                before we know whose it is, and refusing to
                                store it until then discards exactly the
                                requests that are hardest to debug.

The consignment columns split two things that were previously one: when the
provider's status was last *observed* (provider_status_at, last_polled_at) and
when the parcel's own state last *changed* (last_status_at). A parcel polled
hourly for a week has a fresh observation and a week-old state, and conflating
them makes a stalled sync invisible.

Revision ID: a5b2552fea6c
Revises: 2ded3d35eac0
Create Date: 2026-09-11 04:33:42.361902+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
import app.db.types

revision: str = "a5b2552fea6c"
down_revision: str | None = "2ded3d35eac0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "courier_webhook_deliveries",
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("courier_account_id", sa.Uuid(), nullable=True),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("raw_body", sa.Text(), nullable=True),
        sa.Column("body_sha256", sa.String(length=64), nullable=False),
        sa.Column("header_names", app.db.types.JSONColumn, nullable=False),
        sa.Column("provider_event_id", sa.String(length=120), nullable=True),
        sa.Column("reason", sa.String(length=300), nullable=True),
        sa.Column("delivery_count", sa.Integer(), nullable=False),
        sa.Column("received_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("processed_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("last_seen_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("created_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "delivery_count > 0", name=op.f("ck_courier_webhook_deliveries_delivery_count_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_courier_webhook_deliveries")),
        sa.UniqueConstraint("provider", "body_sha256", name="uq_courier_webhook_deliveries_body"),
    )
    with op.batch_alter_table("courier_webhook_deliveries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_courier_webhook_deliveries_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            "ix_courier_webhook_deliveries_state",
            ["provider", "state", "received_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_courier_webhook_deliveries_tenant", ["tenant_id", "received_at"], unique=False
        )

    op.create_table(
        "courier_accounts",
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("label", sa.String(length=80), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("api_key_encrypted", sa.Text(), nullable=True),
        sa.Column("secret_key_encrypted", sa.Text(), nullable=True),
        sa.Column("key_version", sa.String(length=20), nullable=True),
        sa.Column("masked_identifier", sa.String(length=40), nullable=True),
        sa.Column("last_verified_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("last_validation_result", sa.String(length=24), nullable=True),
        sa.Column("last_validation_message", sa.String(length=300), nullable=True),
        sa.Column("consecutive_auth_failures", sa.Integer(), nullable=False),
        sa.Column("capabilities_json", app.db.types.JSONColumn, nullable=False),
        sa.Column("connected_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("disconnected_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("connected_by", sa.Uuid(), nullable=True),
        sa.Column("reported_balance_paisa", sa.BigInteger(), nullable=True),
        sa.Column("reported_balance_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("metadata_json", app.db.types.JSONColumn, nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("updated_at", app.db.types.TZDateTime(), nullable=False),
        sa.CheckConstraint(
            "consecutive_auth_failures >= 0", name=op.f("ck_courier_accounts_failures_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_courier_accounts_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_courier_accounts")),
        sa.UniqueConstraint("tenant_id", "provider", name="uq_courier_accounts_tenant_id_provider"),
    )
    with op.batch_alter_table("courier_accounts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_courier_accounts_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_courier_accounts_tenant_id"), ["tenant_id"], unique=False
        )
        batch_op.create_index(
            "ix_courier_accounts_tenant_status", ["tenant_id", "status"], unique=False
        )

    op.create_table(
        "courier_raw_payloads",
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("courier_account_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("endpoint", sa.String(length=120), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("correlation_id", sa.String(length=40), nullable=True),
        sa.Column("request_payload", app.db.types.JSONColumn, nullable=True),
        sa.Column("response_payload", app.db.types.JSONColumn, nullable=True),
        sa.Column("payload_sha256", sa.String(length=64), nullable=False),
        sa.Column("schema_undocumented", sa.Boolean(), nullable=False),
        sa.Column("received_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("created_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["courier_account_id"],
            ["courier_accounts.id"],
            name=op.f("fk_courier_raw_payloads_courier_account_id_courier_accounts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_courier_raw_payloads_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_courier_raw_payloads")),
    )
    with op.batch_alter_table("courier_raw_payloads", schema=None) as batch_op:
        batch_op.create_index(
            "ix_courier_raw_payloads_correlation", ["correlation_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_courier_raw_payloads_courier_account_id"),
            ["courier_account_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_courier_raw_payloads_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            "ix_courier_raw_payloads_hash", ["tenant_id", "payload_sha256"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_courier_raw_payloads_tenant_id"), ["tenant_id"], unique=False
        )
        batch_op.create_index(
            "ix_courier_raw_payloads_tenant_kind",
            ["tenant_id", "kind", "received_at"],
            unique=False,
        )

    op.create_table(
        "courier_sync_cursors",
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("courier_account_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("cursor_value", sa.String(length=300), nullable=True),
        sa.Column("watermark_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("last_run_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("last_success_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("next_run_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.String(length=400), nullable=True),
        sa.Column("stats_json", app.db.types.JSONColumn, nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("updated_at", app.db.types.TZDateTime(), nullable=False),
        sa.CheckConstraint(
            "consecutive_failures >= 0", name=op.f("ck_courier_sync_cursors_failures_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["courier_account_id"],
            ["courier_accounts.id"],
            name=op.f("fk_courier_sync_cursors_courier_account_id_courier_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_courier_sync_cursors_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_courier_sync_cursors")),
        sa.UniqueConstraint(
            "tenant_id",
            "provider",
            "courier_account_id",
            "kind",
            name="uq_courier_sync_cursors_scope",
        ),
    )
    with op.batch_alter_table("courier_sync_cursors", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_courier_sync_cursors_courier_account_id"),
            ["courier_account_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_courier_sync_cursors_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index("ix_courier_sync_cursors_due", ["kind", "next_run_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_courier_sync_cursors_next_run_at"), ["next_run_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_courier_sync_cursors_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "courier_provider_payments",
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("courier_account_id", sa.Uuid(), nullable=True),
        sa.Column("provider_payment_id", sa.String(length=120), nullable=False),
        sa.Column("provider_reference", sa.String(length=160), nullable=True),
        sa.Column("sync_state", sa.String(length=16), nullable=False),
        sa.Column("total_paisa", sa.BigInteger(), nullable=True),
        sa.Column("provider_status", sa.String(length=40), nullable=True),
        sa.Column("paid_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("consignment_count", sa.Integer(), nullable=True),
        sa.Column("payload_sha256", sa.String(length=64), nullable=True),
        sa.Column("first_seen_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("last_seen_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("detail_fetched_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("imported_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("payout_id", sa.Uuid(), nullable=True),
        sa.Column("raw_payload_id", sa.Uuid(), nullable=True),
        sa.Column("error_message", sa.String(length=400), nullable=True),
        sa.Column("observed_fields", app.db.types.JSONColumn, nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("updated_at", app.db.types.TZDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["courier_account_id"],
            ["courier_accounts.id"],
            name=op.f("fk_courier_provider_payments_courier_account_id_courier_accounts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["payout_id"],
            ["payouts.id"],
            name=op.f("fk_courier_provider_payments_payout_id_payouts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["raw_payload_id"],
            ["courier_raw_payloads.id"],
            name=op.f("fk_courier_provider_payments_raw_payload_id_courier_raw_payloads"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_courier_provider_payments_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_courier_provider_payments")),
        sa.UniqueConstraint(
            "tenant_id",
            "provider",
            "provider_payment_id",
            name="uq_courier_provider_payments_provider_id",
        ),
    )
    with op.batch_alter_table("courier_provider_payments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_courier_provider_payments_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_courier_provider_payments_payout_id"), ["payout_id"], unique=False
        )
        batch_op.create_index(
            "ix_courier_provider_payments_seen", ["tenant_id", "first_seen_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_courier_provider_payments_tenant_id"), ["tenant_id"], unique=False
        )
        batch_op.create_index(
            "ix_courier_provider_payments_tenant_state", ["tenant_id", "sync_state"], unique=False
        )

    op.create_table(
        "courier_booking_attempts",
        sa.Column("consignment_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("courier_account_id", sa.Uuid(), nullable=True),
        sa.Column("merchant_reference", sa.String(length=120), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("is_bulk", sa.Boolean(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=True),
        sa.Column("provider_consignment_id", sa.String(length=120), nullable=True),
        sa.Column("tracking_code", sa.String(length=120), nullable=True),
        sa.Column("requested_cod_taka", sa.Integer(), nullable=True),
        sa.Column("cod_residual_paisa", sa.BigInteger(), nullable=False),
        sa.Column("provider_phone_masked", sa.String(length=20), nullable=True),
        sa.Column("error_code", sa.String(length=60), nullable=True),
        sa.Column("error_message", sa.String(length=400), nullable=True),
        sa.Column("correlation_id", sa.String(length=40), nullable=True),
        sa.Column("raw_payload_id", sa.Uuid(), nullable=True),
        sa.Column("started_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("completed_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("recovery_attempts", sa.Integer(), nullable=False),
        sa.Column("last_recovery_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("next_recovery_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("recovery_note", sa.String(length=400), nullable=True),
        sa.Column("resolved_by", sa.Uuid(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("updated_at", app.db.types.TZDateTime(), nullable=False),
        sa.CheckConstraint(
            "attempt_number > 0", name=op.f("ck_courier_booking_attempts_attempt_number_positive")
        ),
        sa.CheckConstraint(
            "recovery_attempts >= 0",
            name=op.f("ck_courier_booking_attempts_recovery_attempts_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["consignment_id"],
            ["consignments.id"],
            name=op.f("fk_courier_booking_attempts_consignment_id_consignments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["courier_account_id"],
            ["courier_accounts.id"],
            name=op.f("fk_courier_booking_attempts_courier_account_id_courier_accounts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_courier_booking_attempts_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["raw_payload_id"],
            ["courier_raw_payloads.id"],
            name=op.f("fk_courier_booking_attempts_raw_payload_id_courier_raw_payloads"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_courier_booking_attempts_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_courier_booking_attempts")),
        sa.UniqueConstraint(
            "tenant_id",
            "consignment_id",
            "attempt_number",
            name="uq_courier_booking_attempts_consignment_attempt",
        ),
    )
    with op.batch_alter_table("courier_booking_attempts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_courier_booking_attempts_batch_id"), ["batch_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_courier_booking_attempts_consignment_id"),
            ["consignment_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_courier_booking_attempts_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_courier_booking_attempts_order_id"), ["order_id"], unique=False
        )
        batch_op.create_index(
            "ix_courier_booking_attempts_reference",
            ["tenant_id", "provider", "merchant_reference"],
            unique=False,
        )
        batch_op.create_index(
            "ix_courier_booking_attempts_state",
            ["tenant_id", "state", "next_recovery_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_courier_booking_attempts_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "courier_events",
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("courier_account_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("consignment_id", sa.Uuid(), nullable=True),
        sa.Column("provider_consignment_id", sa.String(length=120), nullable=True),
        sa.Column("tracking_code", sa.String(length=120), nullable=True),
        sa.Column("merchant_reference", sa.String(length=120), nullable=True),
        sa.Column("raw_status", sa.String(length=120), nullable=True),
        sa.Column("normalized_status", sa.String(length=24), nullable=True),
        sa.Column("status_undocumented", sa.Boolean(), nullable=False),
        sa.Column("raw_payload_id", sa.Uuid(), nullable=True),
        sa.Column("dedupe_key", sa.String(length=80), nullable=False),
        sa.Column("correlation_id", sa.String(length=40), nullable=True),
        sa.Column("occurred_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("observed_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("last_seen_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("observation_count", sa.Integer(), nullable=False),
        sa.Column("created_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "observation_count > 0", name=op.f("ck_courier_events_observation_count_positive")
        ),
        sa.ForeignKeyConstraint(
            ["consignment_id"],
            ["consignments.id"],
            name=op.f("fk_courier_events_consignment_id_consignments"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["courier_account_id"],
            ["courier_accounts.id"],
            name=op.f("fk_courier_events_courier_account_id_courier_accounts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["raw_payload_id"],
            ["courier_raw_payloads.id"],
            name=op.f("fk_courier_events_raw_payload_id_courier_raw_payloads"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_courier_events_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_courier_events")),
        sa.UniqueConstraint(
            "tenant_id", "provider", "dedupe_key", name="uq_courier_events_tenant_dedupe"
        ),
    )
    with op.batch_alter_table("courier_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_courier_events_consignment", ["consignment_id", "observed_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_courier_events_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            "ix_courier_events_provider_ref", ["tenant_id", "provider_consignment_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_courier_events_tenant_id"), ["tenant_id"], unique=False
        )
        batch_op.create_index(
            "ix_courier_events_tenant_kind", ["tenant_id", "kind", "observed_at"], unique=False
        )

    op.create_table(
        "courier_return_requests",
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("courier_account_id", sa.Uuid(), nullable=True),
        sa.Column("consignment_id", sa.Uuid(), nullable=False),
        sa.Column("reference_kind", sa.String(length=20), nullable=False),
        sa.Column("reference_value", sa.String(length=120), nullable=False),
        sa.Column("provider_return_id", sa.String(length=120), nullable=True),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("provider_status", sa.String(length=40), nullable=True),
        sa.Column("reason", sa.String(length=400), nullable=True),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column("requested_by", sa.Uuid(), nullable=True),
        sa.Column("requested_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("last_synced_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("correlation_id", sa.String(length=40), nullable=True),
        sa.Column("raw_payload_id", sa.Uuid(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("updated_at", app.db.types.TZDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["consignment_id"],
            ["consignments.id"],
            name=op.f("fk_courier_return_requests_consignment_id_consignments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["courier_account_id"],
            ["courier_accounts.id"],
            name=op.f("fk_courier_return_requests_courier_account_id_courier_accounts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["raw_payload_id"],
            ["courier_raw_payloads.id"],
            name=op.f("fk_courier_return_requests_raw_payload_id_courier_raw_payloads"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_courier_return_requests_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_courier_return_requests")),
        sa.UniqueConstraint(
            "tenant_id", "idempotency_key", name="uq_courier_return_requests_idempotency"
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "provider",
            "provider_return_id",
            name="uq_courier_return_requests_provider_id",
        ),
    )
    with op.batch_alter_table("courier_return_requests", schema=None) as batch_op:
        batch_op.create_index(
            "ix_courier_return_requests_consignment", ["consignment_id", "state"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_courier_return_requests_consignment_id"),
            ["consignment_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_courier_return_requests_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_courier_return_requests_tenant_id"), ["tenant_id"], unique=False
        )
        batch_op.create_index(
            "ix_courier_return_requests_tenant_state", ["tenant_id", "state"], unique=False
        )

    with op.batch_alter_table("consignments", schema=None) as batch_op:
        batch_op.add_column(sa.Column("courier_account_id", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("booking_attempt_count", sa.Integer(), nullable=False))
        batch_op.add_column(
            sa.Column("provider_status_at", app.db.types.TZDateTime(), nullable=True)
        )
        batch_op.add_column(sa.Column("last_polled_at", app.db.types.TZDateTime(), nullable=True))
        batch_op.add_column(sa.Column("next_poll_at", app.db.types.TZDateTime(), nullable=True))
        batch_op.add_column(sa.Column("poll_failure_count", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("needs_quantity_resolution", sa.Boolean(), nullable=False))
        batch_op.create_index(
            batch_op.f("ix_consignments_courier_account_id"), ["courier_account_id"], unique=False
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_consignments_courier_account_id_courier_accounts"),
            "courier_accounts",
            ["courier_account_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("consignments", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_consignments_courier_account_id_courier_accounts"), type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_consignments_courier_account_id"))
        batch_op.drop_column("needs_quantity_resolution")
        batch_op.drop_column("poll_failure_count")
        batch_op.drop_column("next_poll_at")
        batch_op.drop_column("last_polled_at")
        batch_op.drop_column("provider_status_at")
        batch_op.drop_column("booking_attempt_count")
        batch_op.drop_column("courier_account_id")

    with op.batch_alter_table("courier_return_requests", schema=None) as batch_op:
        batch_op.drop_index("ix_courier_return_requests_tenant_state")
        batch_op.drop_index(batch_op.f("ix_courier_return_requests_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_courier_return_requests_created_at"))
        batch_op.drop_index(batch_op.f("ix_courier_return_requests_consignment_id"))
        batch_op.drop_index("ix_courier_return_requests_consignment")

    op.drop_table("courier_return_requests")
    with op.batch_alter_table("courier_events", schema=None) as batch_op:
        batch_op.drop_index("ix_courier_events_tenant_kind")
        batch_op.drop_index(batch_op.f("ix_courier_events_tenant_id"))
        batch_op.drop_index("ix_courier_events_provider_ref")
        batch_op.drop_index(batch_op.f("ix_courier_events_created_at"))
        batch_op.drop_index("ix_courier_events_consignment")

    op.drop_table("courier_events")
    with op.batch_alter_table("courier_booking_attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_courier_booking_attempts_tenant_id"))
        batch_op.drop_index("ix_courier_booking_attempts_state")
        batch_op.drop_index("ix_courier_booking_attempts_reference")
        batch_op.drop_index(batch_op.f("ix_courier_booking_attempts_order_id"))
        batch_op.drop_index(batch_op.f("ix_courier_booking_attempts_created_at"))
        batch_op.drop_index(batch_op.f("ix_courier_booking_attempts_consignment_id"))
        batch_op.drop_index(batch_op.f("ix_courier_booking_attempts_batch_id"))

    op.drop_table("courier_booking_attempts")
    with op.batch_alter_table("courier_provider_payments", schema=None) as batch_op:
        batch_op.drop_index("ix_courier_provider_payments_tenant_state")
        batch_op.drop_index(batch_op.f("ix_courier_provider_payments_tenant_id"))
        batch_op.drop_index("ix_courier_provider_payments_seen")
        batch_op.drop_index(batch_op.f("ix_courier_provider_payments_payout_id"))
        batch_op.drop_index(batch_op.f("ix_courier_provider_payments_created_at"))

    op.drop_table("courier_provider_payments")
    with op.batch_alter_table("courier_sync_cursors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_courier_sync_cursors_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_courier_sync_cursors_next_run_at"))
        batch_op.drop_index("ix_courier_sync_cursors_due")
        batch_op.drop_index(batch_op.f("ix_courier_sync_cursors_created_at"))
        batch_op.drop_index(batch_op.f("ix_courier_sync_cursors_courier_account_id"))

    op.drop_table("courier_sync_cursors")
    with op.batch_alter_table("courier_raw_payloads", schema=None) as batch_op:
        batch_op.drop_index("ix_courier_raw_payloads_tenant_kind")
        batch_op.drop_index(batch_op.f("ix_courier_raw_payloads_tenant_id"))
        batch_op.drop_index("ix_courier_raw_payloads_hash")
        batch_op.drop_index(batch_op.f("ix_courier_raw_payloads_created_at"))
        batch_op.drop_index(batch_op.f("ix_courier_raw_payloads_courier_account_id"))
        batch_op.drop_index("ix_courier_raw_payloads_correlation")

    op.drop_table("courier_raw_payloads")
    with op.batch_alter_table("courier_accounts", schema=None) as batch_op:
        batch_op.drop_index("ix_courier_accounts_tenant_status")
        batch_op.drop_index(batch_op.f("ix_courier_accounts_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_courier_accounts_created_at"))

    op.drop_table("courier_accounts")
    with op.batch_alter_table("courier_webhook_deliveries", schema=None) as batch_op:
        batch_op.drop_index("ix_courier_webhook_deliveries_tenant")
        batch_op.drop_index("ix_courier_webhook_deliveries_state")
        batch_op.drop_index(batch_op.f("ix_courier_webhook_deliveries_created_at"))

    op.drop_table("courier_webhook_deliveries")
    # ### end Alembic commands ###
