"""money core: payouts, source files and adjustments

Phase D, second slice. Four tenant-owned tables:

*   payout_source_files — the statement a payout was read from
    (master spec section 83), kept so support can explain a reconciliation
    result later. The SHA-256 is unique per shop, which is what makes
    re-importing the same file idempotent (section 81.2). storage_key is the
    Cloudflare R2 object this will eventually live in; R2 is not provisioned,
    so the content sits in raw_content until it is.
*   payouts — one payment from a courier, however it arrived. The
    unique (tenant, provider, provider_reference) is section 81.1: two rows for
    one provider reference would double a seller's settled total.
*   payout_lines — one row of a statement, keeping the raw parsed row
    and the candidate scores from the last matching run. The check constraint
    applied_paisa <= amount_paisa is section 17.1 in the database: one payout
    line can never settle more than its own amount.
*   payout_adjustments — what the provider took off, held separately
    from the parcel principal (sections 81.9, 84) so an unknown deduction stays
    visible instead of being folded into "delivery fee".

Additive only. No earlier table is altered.

Revision ID: 0a338ffe2303
Revises: 4dca92679b9a
Create Date: 2026-09-10 03:15:58.565248+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
import app.db.types

revision: str = "0a338ffe2303"
down_revision: str | None = "4dca92679b9a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payout_source_files",
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=True),
        sa.Column("raw_content", sa.Text(), nullable=True),
        sa.Column("uploaded_by", sa.Uuid(), nullable=True),
        sa.Column("imported_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("created_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_payout_source_files_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payout_source_files")),
        sa.UniqueConstraint("tenant_id", "sha256", name="uq_payout_source_files_tenant_sha256"),
    )
    with op.batch_alter_table("payout_source_files", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_payout_source_files_sha256"), ["sha256"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_payout_source_files_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "payouts",
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("provider_reference", sa.String(length=160), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("total_paisa", sa.BigInteger(), nullable=False),
        sa.Column("applied_paisa", sa.BigInteger(), nullable=False),
        sa.Column("paid_on", sa.Date(), nullable=True),
        sa.Column("received_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("note", sa.String(length=400), nullable=True),
        sa.Column("source_file_id", sa.Uuid(), nullable=True),
        sa.Column("metadata_json", app.db.types.JSONColumn, nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("updated_at", app.db.types.TZDateTime(), nullable=False),
        sa.CheckConstraint(
            "total_paisa >= 0", name=op.f("ck_payouts_ck_payouts_total_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["source_file_id"],
            ["payout_source_files.id"],
            name=op.f("fk_payouts_source_file_id_payout_source_files"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_payouts_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payouts")),
        sa.UniqueConstraint(
            "tenant_id",
            "provider",
            "provider_reference",
            name="uq_payouts_tenant_provider_reference",
        ),
    )
    with op.batch_alter_table("payouts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_payouts_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_payouts_source_file_id"), ["source_file_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_payouts_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index("ix_payouts_tenant_paid_on", ["tenant_id", "paid_on"], unique=False)
        batch_op.create_index("ix_payouts_tenant_status", ["tenant_id", "status"], unique=False)

    op.create_table(
        "payout_lines",
        sa.Column("payout_id", sa.Uuid(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("amount_paisa", sa.BigInteger(), nullable=False),
        sa.Column("applied_paisa", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("confidence", sa.String(length=20), nullable=True),
        sa.Column("provider_consignment_id", sa.String(length=120), nullable=True),
        sa.Column("tracking_code", sa.String(length=120), nullable=True),
        sa.Column("merchant_reference", sa.String(length=120), nullable=True),
        sa.Column("customer_phone_last4", sa.String(length=4), nullable=True),
        sa.Column("delivered_on", sa.Date(), nullable=True),
        sa.Column("receivable_id", sa.Uuid(), nullable=True),
        sa.Column("matched_by", sa.Uuid(), nullable=True),
        sa.Column("match_reason", sa.String(length=400), nullable=True),
        sa.Column("matched_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("raw", app.db.types.JSONColumn, nullable=False),
        sa.Column("candidates", app.db.types.JSONColumn, nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("updated_at", app.db.types.TZDateTime(), nullable=False),
        sa.CheckConstraint(
            "amount_paisa >= 0", name=op.f("ck_payout_lines_ck_payout_lines_amount_non_negative")
        ),
        sa.CheckConstraint(
            "applied_paisa <= amount_paisa",
            name=op.f("ck_payout_lines_ck_payout_lines_applied_within_amount"),
        ),
        sa.CheckConstraint(
            "applied_paisa >= 0", name=op.f("ck_payout_lines_ck_payout_lines_applied_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["payout_id"],
            ["payouts.id"],
            name=op.f("fk_payout_lines_payout_id_payouts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["receivable_id"],
            ["cod_receivables.id"],
            name=op.f("fk_payout_lines_receivable_id_cod_receivables"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_payout_lines_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payout_lines")),
    )
    with op.batch_alter_table("payout_lines", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_payout_lines_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_payout_lines_payout_id"), ["payout_id"], unique=False)
        batch_op.create_index(
            "ix_payout_lines_payout_row", ["payout_id", "row_number"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_payout_lines_receivable_id"), ["receivable_id"], unique=False
        )
        batch_op.create_index(
            "ix_payout_lines_tenant_consignment_ref",
            ["tenant_id", "provider_consignment_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_payout_lines_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(
            "ix_payout_lines_tenant_status", ["tenant_id", "status"], unique=False
        )
        batch_op.create_index(
            "ix_payout_lines_tenant_tracking", ["tenant_id", "tracking_code"], unique=False
        )

    op.create_table(
        "payout_adjustments",
        sa.Column("payout_id", sa.Uuid(), nullable=False),
        sa.Column("payout_line_id", sa.Uuid(), nullable=True),
        sa.Column("consignment_id", sa.Uuid(), nullable=True),
        sa.Column("type", sa.String(length=24), nullable=False),
        sa.Column("amount_paisa", sa.BigInteger(), nullable=False),
        sa.Column("provider_label", sa.String(length=200), nullable=True),
        sa.Column("raw_text", sa.String(length=500), nullable=True),
        sa.Column("recognized_rule", sa.String(length=80), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("updated_at", app.db.types.TZDateTime(), nullable=False),
        sa.CheckConstraint(
            "amount_paisa >= 0",
            name=op.f("ck_payout_adjustments_ck_payout_adjustments_amount_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["consignment_id"],
            ["consignments.id"],
            name=op.f("fk_payout_adjustments_consignment_id_consignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["payout_id"],
            ["payouts.id"],
            name=op.f("fk_payout_adjustments_payout_id_payouts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["payout_line_id"],
            ["payout_lines.id"],
            name=op.f("fk_payout_adjustments_payout_line_id_payout_lines"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_payout_adjustments_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payout_adjustments")),
    )
    with op.batch_alter_table("payout_adjustments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_payout_adjustments_consignment_id"), ["consignment_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_payout_adjustments_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_payout_adjustments_payout_id"), ["payout_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_payout_adjustments_payout_line_id"), ["payout_line_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_payout_adjustments_tenant_id"), ["tenant_id"], unique=False
        )
        batch_op.create_index(
            "ix_payout_adjustments_tenant_type", ["tenant_id", "type"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payout_adjustments", schema=None) as batch_op:
        batch_op.drop_index("ix_payout_adjustments_tenant_type")
        batch_op.drop_index(batch_op.f("ix_payout_adjustments_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_payout_adjustments_payout_line_id"))
        batch_op.drop_index(batch_op.f("ix_payout_adjustments_payout_id"))
        batch_op.drop_index(batch_op.f("ix_payout_adjustments_created_at"))
        batch_op.drop_index(batch_op.f("ix_payout_adjustments_consignment_id"))

    op.drop_table("payout_adjustments")
    with op.batch_alter_table("payout_lines", schema=None) as batch_op:
        batch_op.drop_index("ix_payout_lines_tenant_tracking")
        batch_op.drop_index("ix_payout_lines_tenant_status")
        batch_op.drop_index(batch_op.f("ix_payout_lines_tenant_id"))
        batch_op.drop_index("ix_payout_lines_tenant_consignment_ref")
        batch_op.drop_index(batch_op.f("ix_payout_lines_receivable_id"))
        batch_op.drop_index("ix_payout_lines_payout_row")
        batch_op.drop_index(batch_op.f("ix_payout_lines_payout_id"))
        batch_op.drop_index(batch_op.f("ix_payout_lines_created_at"))

    op.drop_table("payout_lines")
    with op.batch_alter_table("payouts", schema=None) as batch_op:
        batch_op.drop_index("ix_payouts_tenant_status")
        batch_op.drop_index("ix_payouts_tenant_paid_on")
        batch_op.drop_index(batch_op.f("ix_payouts_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_payouts_source_file_id"))
        batch_op.drop_index(batch_op.f("ix_payouts_created_at"))

    op.drop_table("payouts")
    with op.batch_alter_table("payout_source_files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payout_source_files_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_payout_source_files_sha256"))

    op.drop_table("payout_source_files")
    # ### end Alembic commands ###
