"""notifications: delivery attempts and preferences

Phase F, fourth slice. Master spec sections 94 and 95.

*   notification_deliveries — one row per (notification, channel, target). The
                              unique constraint *is* the idempotency: a
                              dispatcher that runs twice loses the race on the
                              second row and sends nothing. The target is stored
                              hashed, because a push token is a credential and a
                              phone number is PII.
*   notification_preferences— section 95's opt-out, server-side. Routine
                              tracking push is opt-*in*, because one push per
                              parcel event is how a product teaches people to
                              ignore it.

Additive only. No earlier table is altered.

Revision ID: 2ded3d35eac0
Revises: 7fc2d1491940
Create Date: 2026-09-10 16:24:42.256630+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
import app.db.types

revision: str = "2ded3d35eac0"
down_revision: str | None = "7fc2d1491940"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_deliveries",
        sa.Column("notification_id", sa.Uuid(), nullable=False),
        sa.Column("channel", sa.String(length=8), nullable=False),
        sa.Column("target_hash", sa.String(length=64), nullable=False),
        sa.Column("target_suffix", sa.String(length=8), nullable=True),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=True),
        sa.Column("provider_reference", sa.String(length=200), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("last_error", sa.String(length=400), nullable=True),
        sa.Column("suppression_reason", sa.String(length=200), nullable=True),
        sa.Column("estimated_segments", sa.Integer(), nullable=False),
        sa.Column("provider_segments", sa.Integer(), nullable=True),
        sa.Column("created_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("sent_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "attempts >= 0", name=op.f("ck_notification_deliveries_attempts_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_notification_deliveries_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_deliveries")),
        sa.UniqueConstraint(
            "notification_id",
            "channel",
            "target_hash",
            name="uq_notification_deliveries_notification_channel_target",
        ),
    )
    with op.batch_alter_table("notification_deliveries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notification_deliveries_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_notification_deliveries_notification_id"),
            ["notification_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_notification_deliveries_state_next", ["state", "next_attempt_at"], unique=False
        )
        batch_op.create_index(
            "ix_notification_deliveries_tenant_created", ["tenant_id", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_notification_deliveries_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "notification_preferences",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("push_enabled", sa.Boolean(), nullable=False),
        sa.Column("sms_enabled", sa.Boolean(), nullable=False),
        sa.Column("muted_kinds", app.db.types.JSONColumn, nullable=False),
        sa.Column("routine_tracking_push", sa.Boolean(), nullable=False),
        sa.Column("quiet_hours_start", sa.Integer(), nullable=True),
        sa.Column("quiet_hours_end", sa.Integer(), nullable=True),
        sa.Column("updated_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_notification_preferences_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_preferences")),
        sa.UniqueConstraint(
            "tenant_id", "user_id", name="uq_notification_preferences_tenant_id_user_id"
        ),
    )
    with op.batch_alter_table("notification_preferences", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notification_preferences_tenant_id"), ["tenant_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification_preferences", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notification_preferences_tenant_id"))

    op.drop_table("notification_preferences")
    with op.batch_alter_table("notification_deliveries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notification_deliveries_tenant_id"))
        batch_op.drop_index("ix_notification_deliveries_tenant_created")
        batch_op.drop_index("ix_notification_deliveries_state_next")
        batch_op.drop_index(batch_op.f("ix_notification_deliveries_notification_id"))
        batch_op.drop_index(batch_op.f("ix_notification_deliveries_created_at"))

    op.drop_table("notification_deliveries")
    # ### end Alembic commands ###
