"""billing: subscription domain, transactions and usage counters

Phase F, first slice. Master spec section 93 names the tables; sections 90 and
91 say what has to be true about them.

Tenant-owned:

*   billing_transactions      — every verified or refused money movement
*   subscription_events       — the append-only "why is this shop on GRACE?" log
*   billing_provider_customers— the tenant's identity at a provider, hashed
*   billing_attempts          — one dunning attempt each
*   usage_counters            — metered quota spend, one row per period

Platform-scoped **on purpose** (no tenant_id foreign key, no tenancy guard):

*   play_purchase_tokens      — replay protection has to see every tenant's
                                tokens, or the wrong tenant's replay reads as
                                "unseen" and buys a second entitlement from one
                                payment
*   billing_webhook_events    — a webhook arrives unauthenticated, before any
                                tenant is known

The two columns added to ``subscriptions`` with NOT NULL carry a server default
so the statement is safe against a table that already has rows.

Additive only. No earlier table is altered destructively.

Revision ID: ed1f2c323ce8
Revises: d646e9a8c42a
Create Date: 2026-09-10 08:33:04.979543+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
import app.db.types

revision: str = "ed1f2c323ce8"
down_revision: str | None = "d646e9a8c42a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "billing_webhook_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("dedupe_key", sa.String(length=220), nullable=False),
        sa.Column("dedupe_source", sa.String(length=20), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("subscription_id", sa.Uuid(), nullable=True),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=True),
        sa.Column("signature_verified", sa.Boolean(), nullable=False),
        sa.Column("delivery_count", sa.Integer(), nullable=False),
        sa.Column("error", sa.String(length=400), nullable=True),
        sa.Column("payload", app.db.types.JSONColumn, nullable=False),
        sa.Column("payload_sha256", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("received_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("processed_at", app.db.types.TZDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_billing_webhook_events")),
        sa.UniqueConstraint(
            "provider", "dedupe_key", name="uq_billing_webhook_events_provider_dedupe_key"
        ),
    )
    with op.batch_alter_table("billing_webhook_events", schema=None) as batch_op:
        batch_op.create_index("ix_billing_webhook_events_received", ["received_at"], unique=False)
        batch_op.create_index("ix_billing_webhook_events_state", ["state"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_billing_webhook_events_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "play_purchase_tokens",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("package_name", sa.String(length=200), nullable=False),
        sa.Column("product_id", sa.String(length=200), nullable=False),
        sa.Column("plan_code", sa.String(length=32), nullable=False),
        sa.Column("purchase_state", sa.String(length=40), nullable=True),
        sa.Column("acknowledged", sa.Boolean(), nullable=False),
        sa.Column("acknowledged_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("provider_order_id", sa.String(length=200), nullable=True),
        sa.Column("expiry_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("auto_renewing", sa.Boolean(), nullable=False),
        sa.Column("first_verified_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("last_verified_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("presentation_count", sa.Integer(), nullable=False),
        sa.Column("revoked_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("metadata_json", app.db.types.JSONColumn, nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("updated_at", app.db.types.TZDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_play_purchase_tokens")),
        sa.UniqueConstraint("token_hash", name="uq_play_purchase_tokens_token_hash"),
    )
    with op.batch_alter_table("play_purchase_tokens", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_play_purchase_tokens_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index("ix_play_purchase_tokens_order", ["provider_order_id"], unique=False)
        batch_op.create_index("ix_play_purchase_tokens_tenant", ["tenant_id"], unique=False)

    op.create_table(
        "billing_attempts",
        sa.Column("subscription_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("failure_code", sa.String(length=80), nullable=True),
        sa.Column("failure_detail", sa.String(length=400), nullable=True),
        sa.Column("amount_paisa", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("occurred_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("next_retry_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("resolved_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("updated_at", app.db.types.TZDateTime(), nullable=False),
        sa.CheckConstraint(
            "attempt_number >= 1", name=op.f("ck_billing_attempts_attempt_number_positive")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_billing_attempts_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_billing_attempts")),
    )
    with op.batch_alter_table("billing_attempts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_billing_attempts_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            "ix_billing_attempts_next_retry", ["state", "next_retry_at"], unique=False
        )
        batch_op.create_index(
            "ix_billing_attempts_subscription", ["subscription_id", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_billing_attempts_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "billing_provider_customers",
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("reference_hash", sa.String(length=64), nullable=False),
        sa.Column("reference_suffix", sa.String(length=8), nullable=True),
        sa.Column("linked_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("linked_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("metadata_json", app.db.types.JSONColumn, nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("updated_at", app.db.types.TZDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_billing_provider_customers_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_billing_provider_customers")),
        sa.UniqueConstraint(
            "tenant_id", "provider", name="uq_billing_provider_customers_tenant_id_provider"
        ),
    )
    with op.batch_alter_table("billing_provider_customers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_billing_provider_customers_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            "ix_billing_provider_customers_reference_hash",
            ["provider", "reference_hash"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_billing_provider_customers_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "billing_transactions",
        sa.Column("subscription_id", sa.Uuid(), nullable=True),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_event_id", sa.String(length=200), nullable=True),
        sa.Column("provider_reference", sa.String(length=200), nullable=True),
        sa.Column("plan_code", sa.String(length=32), nullable=False),
        sa.Column("provider_product_id", sa.String(length=200), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("amount_paisa", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("verification_result", sa.String(length=40), nullable=False),
        sa.Column("verification_detail", sa.String(length=400), nullable=True),
        sa.Column("metadata_json", app.db.types.JSONColumn, nullable=False),
        sa.Column("occurred_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("received_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("updated_at", app.db.types.TZDateTime(), nullable=False),
        sa.CheckConstraint(
            "amount_paisa >= 0", name=op.f("ck_billing_transactions_amount_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_billing_transactions_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_billing_transactions")),
        sa.UniqueConstraint(
            "provider",
            "provider_event_id",
            name="uq_billing_transactions_provider_provider_event_id",
        ),
    )
    with op.batch_alter_table("billing_transactions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_billing_transactions_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            "ix_billing_transactions_reference", ["provider", "provider_reference"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_billing_transactions_subscription_id"), ["subscription_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_billing_transactions_tenant_id"), ["tenant_id"], unique=False
        )
        batch_op.create_index(
            "ix_billing_transactions_tenant_occurred", ["tenant_id", "occurred_at"], unique=False
        )

    op.create_table(
        "subscription_events",
        sa.Column("subscription_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("from_status", sa.String(length=32), nullable=True),
        sa.Column("to_status", sa.String(length=32), nullable=True),
        sa.Column("from_plan", sa.String(length=32), nullable=True),
        sa.Column("to_plan", sa.String(length=32), nullable=True),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_event_id", sa.String(length=200), nullable=True),
        sa.Column("transaction_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.String(length=400), nullable=True),
        sa.Column("payload", app.db.types.JSONColumn, nullable=False),
        sa.Column("occurred_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("created_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_subscription_events_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription_events")),
    )
    with op.batch_alter_table("subscription_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_subscription_events_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            "ix_subscription_events_subscription", ["subscription_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_subscription_events_tenant_created", ["tenant_id", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_subscription_events_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "usage_counters",
        sa.Column("entitlement_key", sa.String(length=60), nullable=False),
        sa.Column("period_key", sa.String(length=10), nullable=False),
        sa.Column("period_type", sa.String(length=10), nullable=False),
        sa.Column("used", sa.Integer(), nullable=False),
        sa.Column("limit_value", sa.Integer(), nullable=False),
        sa.Column("plan_code", sa.String(length=32), nullable=False),
        sa.Column("first_used_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("last_used_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("used >= 0", name=op.f("ck_usage_counters_used_non_negative")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_usage_counters_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_counters")),
        sa.UniqueConstraint(
            "tenant_id",
            "entitlement_key",
            "period_key",
            name="uq_usage_counters_tenant_id_entitlement_key_period_key",
        ),
    )
    with op.batch_alter_table("usage_counters", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_usage_counters_tenant_id"), ["tenant_id"], unique=False
        )
        batch_op.create_index(
            "ix_usage_counters_tenant_period", ["tenant_id", "period_key"], unique=False
        )

    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("trial_end", app.db.types.TZDateTime(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "cancel_at_period_end",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
        batch_op.add_column(sa.Column("grace_until", app.db.types.TZDateTime(), nullable=True))
        batch_op.add_column(sa.Column("provider_product_id", sa.String(length=200), nullable=True))
        batch_op.add_column(
            sa.Column(
                "distribution_channel",
                sa.String(length=20),
                nullable=False,
                server_default="DIRECT",
            )
        )
        batch_op.add_column(sa.Column("last_synced_at", app.db.types.TZDateTime(), nullable=True))
        batch_op.add_column(sa.Column("status_reason", sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.drop_column("status_reason")
        batch_op.drop_column("last_synced_at")
        batch_op.drop_column("distribution_channel")
        batch_op.drop_column("provider_product_id")
        batch_op.drop_column("grace_until")
        batch_op.drop_column("cancel_at_period_end")
        batch_op.drop_column("trial_end")

    with op.batch_alter_table("usage_counters", schema=None) as batch_op:
        batch_op.drop_index("ix_usage_counters_tenant_period")
        batch_op.drop_index(batch_op.f("ix_usage_counters_tenant_id"))

    op.drop_table("usage_counters")
    with op.batch_alter_table("subscription_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subscription_events_tenant_id"))
        batch_op.drop_index("ix_subscription_events_tenant_created")
        batch_op.drop_index("ix_subscription_events_subscription")
        batch_op.drop_index(batch_op.f("ix_subscription_events_created_at"))

    op.drop_table("subscription_events")
    with op.batch_alter_table("billing_transactions", schema=None) as batch_op:
        batch_op.drop_index("ix_billing_transactions_tenant_occurred")
        batch_op.drop_index(batch_op.f("ix_billing_transactions_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_billing_transactions_subscription_id"))
        batch_op.drop_index("ix_billing_transactions_reference")
        batch_op.drop_index(batch_op.f("ix_billing_transactions_created_at"))

    op.drop_table("billing_transactions")
    with op.batch_alter_table("billing_provider_customers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_billing_provider_customers_tenant_id"))
        batch_op.drop_index("ix_billing_provider_customers_reference_hash")
        batch_op.drop_index(batch_op.f("ix_billing_provider_customers_created_at"))

    op.drop_table("billing_provider_customers")
    with op.batch_alter_table("billing_attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_billing_attempts_tenant_id"))
        batch_op.drop_index("ix_billing_attempts_subscription")
        batch_op.drop_index("ix_billing_attempts_next_retry")
        batch_op.drop_index(batch_op.f("ix_billing_attempts_created_at"))

    op.drop_table("billing_attempts")
    with op.batch_alter_table("play_purchase_tokens", schema=None) as batch_op:
        batch_op.drop_index("ix_play_purchase_tokens_tenant")
        batch_op.drop_index("ix_play_purchase_tokens_order")
        batch_op.drop_index(batch_op.f("ix_play_purchase_tokens_created_at"))

    op.drop_table("play_purchase_tokens")
    with op.batch_alter_table("billing_webhook_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_billing_webhook_events_tenant_id"))
        batch_op.drop_index("ix_billing_webhook_events_state")
        batch_op.drop_index("ix_billing_webhook_events_received")

    op.drop_table("billing_webhook_events")
    # ### end Alembic commands ###
