"""privacy: export jobs and account deletion requests

Phase F, third slice. Master spec sections 99 and 100.

*   export_jobs        — tenant-owned. Holds the generated CSV, a hashed,
                         expiring download token and the audit-relevant
                         parameters. The content is dropped when the link
                         expires; the row stays, so "who exported the customer
                         list in March?" is still answerable afterwards.
*   deletion_requests  — platform-scoped **on purpose**: the row has to outlive
                         the tenant's own data, or the record of the deletion
                         disappears with the thing it documents.

Additive only. No earlier table is altered.

Revision ID: 7fc2d1491940
Revises: b773e55601bf
Create Date: 2026-09-10 16:04:18.754056+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
import app.db.types

revision: str = "7fc2d1491940"
down_revision: str | None = "b773e55601bf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deletion_requests",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("requested_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.String(length=400), nullable=True),
        sa.Column("requested_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("scheduled_for", app.db.types.TZDateTime(), nullable=False),
        sa.Column("cancelled_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("completed_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("steps", app.db.types.JSONColumn, nullable=False),
        sa.Column("error", sa.String(length=400), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deletion_requests")),
    )
    with op.batch_alter_table("deletion_requests", schema=None) as batch_op:
        batch_op.create_index(
            "ix_deletion_requests_status_due", ["status", "scheduled_for"], unique=False
        )
        batch_op.create_index("ix_deletion_requests_tenant", ["tenant_id"], unique=False)

    op.create_table(
        "export_jobs",
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("export_format", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("requested_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("parameters", app.db.types.JSONColumn, nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=200), nullable=True),
        sa.Column("storage_key", sa.String(length=500), nullable=True),
        sa.Column("content", sa.LargeBinary(), nullable=True),
        sa.Column("download_token_hash", sa.String(length=64), nullable=True),
        sa.Column("expires_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("downloaded_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("download_count", sa.Integer(), nullable=False),
        sa.Column("error", sa.String(length=400), nullable=True),
        sa.Column("created_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("completed_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("row_count >= 0", name=op.f("ck_export_jobs_row_count_non_negative")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_export_jobs_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_export_jobs")),
        sa.UniqueConstraint("download_token_hash", name="uq_export_jobs_download_token_hash"),
    )
    with op.batch_alter_table("export_jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_export_jobs_created_at"), ["created_at"], unique=False)
        batch_op.create_index("ix_export_jobs_status", ["status"], unique=False)
        batch_op.create_index(
            "ix_export_jobs_tenant_created", ["tenant_id", "created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_export_jobs_tenant_id"), ["tenant_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("export_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_export_jobs_tenant_id"))
        batch_op.drop_index("ix_export_jobs_tenant_created")
        batch_op.drop_index("ix_export_jobs_status")
        batch_op.drop_index(batch_op.f("ix_export_jobs_created_at"))

    op.drop_table("export_jobs")
    with op.batch_alter_table("deletion_requests", schema=None) as batch_op:
        batch_op.drop_index("ix_deletion_requests_tenant")
        batch_op.drop_index("ix_deletion_requests_status_due")

    op.drop_table("deletion_requests")
    # ### end Alembic commands ###
