"""admin: platform admins, support cases, repair log and provider health

Phase F, second slice. Master spec sections 44, 49, 102 and 103.

Four platform-scoped tables. None of them is tenant-owned, and that is the
point: an ops console reads *across* shops, so these rows are addressed by an
explicit tenant column rather than filtered by the tenancy guard.

*   platform_admins       — operator credentials, token stored hashed. A
                            separate authority from shop membership: a
                            compromised seller session grants nothing here.
*   support_cases         — section 102, linkable to an order, consignment,
                            payout, reconciliation case or subscription. Holds
                            no credential; section 102 forbids asking a seller
                            to send one.
*   admin_repair_actions  — section 103. Every repair records who, why, and its
                            outcome, with a unique (action, idempotency_key) so
                            two operators reacting to one alert run it once.
*   provider_health       — sections 49 and 75. Per (provider, capability,
                            scope), so one shop's bad courier credential does
                            not mark the provider down for everyone.

``provider_health.scope_key`` carries the tenant id, or ``"*"`` for the
platform-wide row, and is what the unique constraint keys on. A nullable
``tenant_id`` cannot do that job: SQL treats NULLs as distinct in a unique
index, so the platform row would duplicate on every observation.

Additive only. No earlier table is altered.

Revision ID: b773e55601bf
Revises: ed1f2c323ce8
Create Date: 2026-09-10 09:37:10.606728+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
import app.db.types

revision: str = "b773e55601bf"
down_revision: str | None = "ed1f2c323ce8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_repair_actions",
        sa.Column("action", sa.String(length=60), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("target_type", sa.String(length=60), nullable=True),
        sa.Column("target_id", sa.String(length=80), nullable=True),
        sa.Column("admin_id", sa.Uuid(), nullable=True),
        sa.Column("admin_label", sa.String(length=120), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("outcome", sa.String(length=20), nullable=False),
        sa.Column("result", app.db.types.JSONColumn, nullable=False),
        sa.Column("error", sa.String(length=400), nullable=True),
        sa.Column("created_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("completed_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_repair_actions")),
        sa.UniqueConstraint(
            "action", "idempotency_key", name="uq_admin_repair_actions_action_idempotency_key"
        ),
    )
    with op.batch_alter_table("admin_repair_actions", schema=None) as batch_op:
        batch_op.create_index("ix_admin_repair_actions_created", ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_admin_repair_actions_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index("ix_admin_repair_actions_tenant", ["tenant_id"], unique=False)

    op.create_table(
        "platform_admins",
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_used_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("expires_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("revoked_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("revoked_reason", sa.String(length=400), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("updated_at", app.db.types.TZDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_admins")),
        sa.UniqueConstraint("token_hash", name="uq_platform_admins_token_hash"),
    )
    with op.batch_alter_table("platform_admins", schema=None) as batch_op:
        batch_op.create_index("ix_platform_admins_active", ["is_active"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_platform_admins_created_at"), ["created_at"], unique=False
        )

    op.create_table(
        "provider_health",
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("capability", sa.String(length=40), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("scope_key", sa.String(length=40), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("breaker_state", sa.String(length=12), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("auth_failure_count", sa.Integer(), nullable=False),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("latency_ms_ema", sa.Integer(), nullable=False),
        sa.Column("last_success_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("last_error_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("last_error_code", sa.String(length=80), nullable=True),
        sa.Column("last_error_summary", sa.String(length=300), nullable=True),
        sa.Column("breaker_opened_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("updated_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "consecutive_failures >= 0", name=op.f("ck_provider_health_failures_non_negative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_health")),
        sa.UniqueConstraint("provider", "capability", "scope_key", name="uq_provider_health_scope"),
    )
    with op.batch_alter_table("provider_health", schema=None) as batch_op:
        batch_op.create_index("ix_provider_health_state", ["state"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_provider_health_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "support_cases",
        sa.Column("reference", sa.String(length=32), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("case_type", sa.String(length=24), nullable=False),
        sa.Column("severity", sa.String(length=12), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("consignment_id", sa.Uuid(), nullable=True),
        sa.Column("payout_id", sa.Uuid(), nullable=True),
        sa.Column("reconciliation_case_id", sa.Uuid(), nullable=True),
        sa.Column("subscription_id", sa.Uuid(), nullable=True),
        sa.Column("opened_by_admin_id", sa.Uuid(), nullable=True),
        sa.Column("assigned_to", sa.String(length=120), nullable=True),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column("resolved_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("metadata_json", app.db.types.JSONColumn, nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("updated_at", app.db.types.TZDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_support_cases")),
    )
    with op.batch_alter_table("support_cases", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_support_cases_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index("ix_support_cases_reference", ["reference"], unique=False)
        batch_op.create_index(
            "ix_support_cases_status_created", ["status", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_support_cases_tenant_created", ["tenant_id", "created_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("support_cases", schema=None) as batch_op:
        batch_op.drop_index("ix_support_cases_tenant_created")
        batch_op.drop_index("ix_support_cases_status_created")
        batch_op.drop_index("ix_support_cases_reference")
        batch_op.drop_index(batch_op.f("ix_support_cases_created_at"))

    op.drop_table("support_cases")
    with op.batch_alter_table("provider_health", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_provider_health_tenant_id"))
        batch_op.drop_index("ix_provider_health_state")

    op.drop_table("provider_health")
    with op.batch_alter_table("platform_admins", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_platform_admins_created_at"))
        batch_op.drop_index("ix_platform_admins_active")

    op.drop_table("platform_admins")
    with op.batch_alter_table("admin_repair_actions", schema=None) as batch_op:
        batch_op.drop_index("ix_admin_repair_actions_tenant")
        batch_op.drop_index(batch_op.f("ix_admin_repair_actions_created_at"))
        batch_op.drop_index("ix_admin_repair_actions_created")

    op.drop_table("admin_repair_actions")
    # ### end Alembic commands ###
