"""money core: financial ledger and cod receivables

Phase D, first slice. Two tenant-owned tables:

*   financial_ledger_entries — the append-only operational ledger
    (master spec section 80). There is no update path to it anywhere in the
    application: a correction is a reversal row pointing at the original
    through reversal_of. The amount is always non-negative and the direction
    carries the sign, which is why the check constraint can be that simple —
    a signed amount plus a direction column would be two representations of
    one fact, free to disagree.
*   cod_receivables — what a courier still owes for one parcel
    (sections 15, 10.3). Deliberately separate from both the consignment and
    the payout, because section 1.4 requires a parcel to be able to be
    DELIVERED while its money is still unpaid.

The oversettlement check on cod_receivables is section 17.2 written as a
constraint: settled_paisa can never exceed collectible_paisa +
adjustment_paisa, so no code path — including one written later by someone who
has not read section 17 — can record more money arriving than was owed
without an explicit adjustment.

Additive only. No Phase A or Phase B table is altered.

Revision ID: 4dca92679b9a
Revises: 358010432a38
Create Date: 2026-09-10 03:04:43.099388+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
import app.db.types

revision: str = '4dca92679b9a'
down_revision: str | None = '358010432a38'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_ledger_entries',
    sa.Column('occurred_at', app.db.types.TZDateTime(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount_paisa', sa.BigInteger(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('bucket', sa.String(length=24), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('source_ref', sa.String(length=200), nullable=True),
    sa.Column('reversal_of', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.String(length=400), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('metadata_json', app.db.types.JSONColumn, nullable=False),
    sa.Column('created_at', app.db.types.TZDateTime(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('amount_paisa >= 0', name=op.f('ck_financial_ledger_entries_ck_ledger_amount_non_negative')),
    sa.ForeignKeyConstraint(['reversal_of'], ['financial_ledger_entries.id'], name=op.f('fk_financial_ledger_entries_reversal_of_financial_ledger_entries'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_financial_ledger_entries_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_ledger_entries'))
    )
    with op.batch_alter_table('financial_ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_ledger_entries_business_date'), ['business_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_ledger_entries_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_ledger_entries_reversal_of'), ['reversal_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_ledger_entries_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_ledger_tenant_bucket_date', ['tenant_id', 'bucket', 'business_date'], unique=False)
        batch_op.create_index('ix_ledger_tenant_entity', ['tenant_id', 'entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_ledger_tenant_occurred', ['tenant_id', 'occurred_at'], unique=False)

    op.create_table('cod_receivables',
    sa.Column('consignment_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('collectible_paisa', sa.BigInteger(), nullable=False),
    sa.Column('settled_paisa', sa.BigInteger(), nullable=False),
    sa.Column('adjustment_paisa', sa.BigInteger(), nullable=False),
    sa.Column('deduction_paisa', sa.BigInteger(), nullable=False),
    sa.Column('eligible_at', app.db.types.TZDateTime(), nullable=True),
    sa.Column('eligible_business_date', sa.Date(), nullable=True),
    sa.Column('settled_at', app.db.types.TZDateTime(), nullable=True),
    sa.Column('status_reason', sa.String(length=400), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('metadata_json', app.db.types.JSONColumn, nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.types.TZDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.TZDateTime(), nullable=False),
    sa.CheckConstraint('collectible_paisa >= 0', name=op.f('ck_cod_receivables_ck_cod_receivables_collectible_non_negative')),
    sa.CheckConstraint('settled_paisa <= collectible_paisa + adjustment_paisa', name=op.f('ck_cod_receivables_ck_cod_receivables_no_oversettlement')),
    sa.CheckConstraint('settled_paisa >= 0', name=op.f('ck_cod_receivables_ck_cod_receivables_settled_non_negative')),
    sa.ForeignKeyConstraint(['consignment_id'], ['consignments.id'], name=op.f('fk_cod_receivables_consignment_id_consignments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_cod_receivables_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_cod_receivables_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cod_receivables')),
    sa.UniqueConstraint('tenant_id', 'consignment_id', name='uq_cod_receivables_tenant_consignment')
    )
    with op.batch_alter_table('cod_receivables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cod_receivables_consignment_id'), ['consignment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cod_receivables_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cod_receivables_order_id'), ['order_id'], unique=False)
        batch_op.create_index('ix_cod_receivables_tenant_eligible', ['tenant_id', 'eligible_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cod_receivables_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_cod_receivables_tenant_status', ['tenant_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cod_receivables', schema=None) as batch_op:
        batch_op.drop_index('ix_cod_receivables_tenant_status')
        batch_op.drop_index(batch_op.f('ix_cod_receivables_tenant_id'))
        batch_op.drop_index('ix_cod_receivables_tenant_eligible')
        batch_op.drop_index(batch_op.f('ix_cod_receivables_order_id'))
        batch_op.drop_index(batch_op.f('ix_cod_receivables_created_at'))
        batch_op.drop_index(batch_op.f('ix_cod_receivables_consignment_id'))

    op.drop_table('cod_receivables')
    with op.batch_alter_table('financial_ledger_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_ledger_tenant_occurred')
        batch_op.drop_index('ix_ledger_tenant_entity')
        batch_op.drop_index('ix_ledger_tenant_bucket_date')
        batch_op.drop_index(batch_op.f('ix_financial_ledger_entries_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_financial_ledger_entries_reversal_of'))
        batch_op.drop_index(batch_op.f('ix_financial_ledger_entries_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_financial_ledger_entries_business_date'))

    op.drop_table('financial_ledger_entries')
    # ### end Alembic commands ###
