"""money core: reconciliation cases

Phase D, third slice. One tenant-owned table.

reconciliation_cases is the "separate issue entity" master spec section 16
requires for each of its eight cases. The separation is the point: a
"delivered but unpaid" that exists only as a filter on a list is a problem
nobody is accountable for, whereas a case has an owner, a resolution and a
note saying what happened.

The unique key is (tenant, kind, subject_type, subject_id, dedupe_key), which
is what stops the engine growing the list every time it runs — a case list
that doubles on each scan is one the seller stops reading, and then the engine
has achieved nothing. dedupe_key defaults to an empty string rather than null
because a null never equals a null, so a nullable column would not constrain.

Additive only. No earlier table is altered.

Revision ID: 52129fd8eb7e
Revises: 0a338ffe2303
Create Date: 2026-09-10 03:24:03.417862+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
import app.db.types

revision: str = '52129fd8eb7e'
down_revision: str | None = '0a338ffe2303'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_cases',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=120), nullable=False),
    sa.Column('amount_paisa', sa.BigInteger(), nullable=False),
    sa.Column('summary', sa.String(length=400), nullable=False),
    sa.Column('detail', app.db.types.JSONColumn, nullable=False),
    sa.Column('receivable_id', sa.Uuid(), nullable=True),
    sa.Column('payout_id', sa.Uuid(), nullable=True),
    sa.Column('payout_line_id', sa.Uuid(), nullable=True),
    sa.Column('consignment_id', sa.Uuid(), nullable=True),
    sa.Column('opened_at', app.db.types.TZDateTime(), nullable=False),
    sa.Column('resolved_at', app.db.types.TZDateTime(), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('resolution', sa.String(length=400), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.types.TZDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.TZDateTime(), nullable=False),
    sa.CheckConstraint('amount_paisa >= 0', name=op.f('ck_reconciliation_cases_ck_reconciliation_cases_amount_non_negative')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_reconciliation_cases_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliation_cases')),
    sa.UniqueConstraint('tenant_id', 'kind', 'subject_type', 'subject_id', 'dedupe_key', name='uq_reconciliation_cases_subject')
    )
    with op.batch_alter_table('reconciliation_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reconciliation_cases_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_cases_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_cases_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_reconciliation_cases_tenant_kind', ['tenant_id', 'kind'], unique=False)
        batch_op.create_index('ix_reconciliation_cases_tenant_status', ['tenant_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reconciliation_cases', schema=None) as batch_op:
        batch_op.drop_index('ix_reconciliation_cases_tenant_status')
        batch_op.drop_index('ix_reconciliation_cases_tenant_kind')
        batch_op.drop_index(batch_op.f('ix_reconciliation_cases_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_cases_subject_id'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_cases_created_at'))

    op.drop_table('reconciliation_cases')
    # ### end Alembic commands ###
