"""profit: charge snapshots and profit snapshots

Phase E, first slice. Two tenant-owned tables, both append-only.

*   consignment_charges — what a parcel cost, as it was known at a
    point in time. A better figure arriving later (a settled statement amount
    replacing a booking quote) is a new row that points the old one at it
    through superseded_by; the superseded row is otherwise left exactly as
    written. Master spec section 17.3: historical charge snapshots are
    immutable except via audited correction.
*   profit_snapshots — section 18.2's field list plus the revision
    machinery section 17.4 requires. A recalculation writes revision + 1 and
    marks the previous row not-current; the old figures stay readable forever.
    Section 55's acceptance criterion is the reason: "old order profit does not
    change after new rate rule."

Both carry the source of every input, so section 85's truth hierarchy —
settled, booked, seller-entered, estimate, unknown — survives into the figure
and the UI can mark an estimated profit as estimated rather than exact.

Additive only. No earlier table is altered.

Revision ID: ef349f877a82
Revises: 52129fd8eb7e
Create Date: 2026-09-10 04:08:33.154917+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
import app.db.types

revision: str = 'ef349f877a82'
down_revision: str | None = '52129fd8eb7e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consignment_charges',
    sa.Column('consignment_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount_paisa', sa.BigInteger(), nullable=False),
    sa.Column('provider_label', sa.String(length=200), nullable=True),
    sa.Column('source_ref', sa.String(length=200), nullable=True),
    sa.Column('superseded_by', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.String(length=400), nullable=True),
    sa.Column('occurred_at', app.db.types.TZDateTime(), nullable=False),
    sa.Column('metadata_json', app.db.types.JSONColumn, nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.types.TZDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.TZDateTime(), nullable=False),
    sa.CheckConstraint('amount_paisa >= 0', name=op.f('ck_consignment_charges_ck_consignment_charges_amount_non_negative')),
    sa.ForeignKeyConstraint(['consignment_id'], ['consignments.id'], name=op.f('fk_consignment_charges_consignment_id_consignments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by'], ['consignment_charges.id'], name=op.f('fk_consignment_charges_superseded_by_consignment_charges'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_consignment_charges_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consignment_charges'))
    )
    with op.batch_alter_table('consignment_charges', schema=None) as batch_op:
        batch_op.create_index('ix_consignment_charges_consignment_current', ['consignment_id', 'superseded_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_consignment_charges_consignment_id'), ['consignment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consignment_charges_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_consignment_charges_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_consignment_charges_tenant_kind', ['tenant_id', 'kind'], unique=False)

    op.create_table('profit_snapshots',
    sa.Column('consignment_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('superseded_by', sa.Uuid(), nullable=True),
    sa.Column('calculation_version', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('realized_revenue_paisa', sa.BigInteger(), nullable=False),
    sa.Column('item_cost_paisa', sa.BigInteger(), nullable=False),
    sa.Column('delivery_charge_paisa', sa.BigInteger(), nullable=False),
    sa.Column('cod_fee_paisa', sa.BigInteger(), nullable=False),
    sa.Column('return_charge_paisa', sa.BigInteger(), nullable=False),
    sa.Column('packaging_paisa', sa.BigInteger(), nullable=False),
    sa.Column('payment_fee_paisa', sa.BigInteger(), nullable=False),
    sa.Column('other_cost_paisa', sa.BigInteger(), nullable=False),
    sa.Column('ad_cost_paisa', sa.BigInteger(), nullable=False),
    sa.Column('allocation_method', sa.String(length=40), nullable=True),
    sa.Column('allocation_version', sa.Integer(), nullable=True),
    sa.Column('discount_paisa', sa.BigInteger(), nullable=False),
    sa.Column('write_off_cost_paisa', sa.BigInteger(), nullable=False),
    sa.Column('contribution_profit_paisa', sa.BigInteger(), nullable=False),
    sa.Column('margin_basis_points', sa.Integer(), nullable=True),
    sa.Column('quality', sa.String(length=16), nullable=False),
    sa.Column('missing_inputs', app.db.types.JSONColumn, nullable=False),
    sa.Column('reason', sa.String(length=400), nullable=True),
    sa.Column('outcome', sa.String(length=24), nullable=False),
    sa.Column('return_reason', sa.String(length=32), nullable=True),
    sa.Column('calculated_at', app.db.types.TZDateTime(), nullable=False),
    sa.Column('metadata_json', app.db.types.JSONColumn, nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.types.TZDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.TZDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consignment_id'], ['consignments.id'], name=op.f('fk_profit_snapshots_consignment_id_consignments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_profit_snapshots_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by'], ['profit_snapshots.id'], name=op.f('fk_profit_snapshots_superseded_by_profit_snapshots'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_profit_snapshots_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profit_snapshots')),
    sa.UniqueConstraint('tenant_id', 'consignment_id', 'revision', name='uq_profit_snapshots_tenant_consignment_revision')
    )
    with op.batch_alter_table('profit_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profit_snapshots_consignment_id'), ['consignment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_profit_snapshots_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_profit_snapshots_order', ['order_id'], unique=False)
        batch_op.create_index('ix_profit_snapshots_tenant_current', ['tenant_id', 'is_current'], unique=False)
        batch_op.create_index('ix_profit_snapshots_tenant_date', ['tenant_id', 'business_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_profit_snapshots_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profit_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profit_snapshots_tenant_id'))
        batch_op.drop_index('ix_profit_snapshots_tenant_date')
        batch_op.drop_index('ix_profit_snapshots_tenant_current')
        batch_op.drop_index('ix_profit_snapshots_order')
        batch_op.drop_index(batch_op.f('ix_profit_snapshots_created_at'))
        batch_op.drop_index(batch_op.f('ix_profit_snapshots_consignment_id'))

    op.drop_table('profit_snapshots')
    with op.batch_alter_table('consignment_charges', schema=None) as batch_op:
        batch_op.drop_index('ix_consignment_charges_tenant_kind')
        batch_op.drop_index(batch_op.f('ix_consignment_charges_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_consignment_charges_created_at'))
        batch_op.drop_index(batch_op.f('ix_consignment_charges_consignment_id'))
        batch_op.drop_index('ix_consignment_charges_consignment_current')

    op.drop_table('consignment_charges')
    # ### end Alembic commands ###
