"""alerts: notification centre

Phase E, third slice. One tenant-owned table.

*   notifications — the in-app centre master spec section 94 requires,
    because push is not enough: a seller with notifications switched off still
    has to be able to find out that delivered parcels have not been paid for.

The unique (tenant, kind, dedupe_key) is the whole reason the table is usable.
Without it a daily alert scan writes a fresh "7 parcels unpaid" every morning,
and section 94's "deduplicate repetitive warnings" becomes a list nobody
finishes reading. entity_type/entity_id carry the deep link, so tapping an
alert opens the order or case it is about rather than a dashboard.

Additive only. No earlier table is altered.

Revision ID: d646e9a8c42a
Revises: 0c3aa1907dfc
Create Date: 2026-09-10 06:44:13.467734+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
import app.db.types

revision: str = "d646e9a8c42a"
down_revision: str | None = "0c3aa1907dfc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=12), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("body", sa.String(length=600), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=True),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("dedupe_key", sa.String(length=120), nullable=False),
        sa.Column("amount_paisa", sa.BigInteger(), nullable=False),
        sa.Column("item_count", sa.Integer(), nullable=False),
        sa.Column("business_date", sa.Date(), nullable=False),
        sa.Column("read_at", app.db.types.TZDateTime(), nullable=True),
        sa.Column("payload", app.db.types.JSONColumn, nullable=False),
        sa.Column("created_at", app.db.types.TZDateTime(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_notifications_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
        sa.UniqueConstraint(
            "tenant_id", "kind", "dedupe_key", name="uq_notifications_tenant_kind_dedupe"
        ),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(
            "ix_notifications_tenant_created", ["tenant_id", "created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_notifications_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(
            "ix_notifications_tenant_unread", ["tenant_id", "read_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index("ix_notifications_tenant_unread")
        batch_op.drop_index(batch_op.f("ix_notifications_tenant_id"))
        batch_op.drop_index("ix_notifications_tenant_created")

    op.drop_table("notifications")
    # ### end Alembic commands ###
