"""profit: expenses and ad allocation

Phase E, second slice. Two tenant-owned tables.

*   expenses — money the seller spent, over a period. Recording one
    changes no profit figure; an expense reaches orders only when it is
    allocated, which is a separate named step. allocated_paisa is kept next to
    amount_paisa so spend that reached no parcel stays visible rather than
    being smeared onto unrelated orders.
*   expense_allocations — one expense's share of one parcel, with the
    method and version that produced it. Master spec section 86 requires
    allocation to be explicit; this row is the answer to "why does this order
    carry 120 taka of ad cost?".

The unique (tenant, expense, consignment) is what makes re-allocating replace a
run rather than add a second share.

Additive only. No earlier table is altered.

Revision ID: 0c3aa1907dfc
Revises: ef349f877a82
Create Date: 2026-09-10 04:16:25.692233+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
import app.db.types

revision: str = '0c3aa1907dfc'
down_revision: str | None = 'ef349f877a82'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount_paisa', sa.BigInteger(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('preferred_method', sa.String(length=40), nullable=False),
    sa.Column('allocated_at', app.db.types.TZDateTime(), nullable=True),
    sa.Column('allocated_paisa', sa.BigInteger(), nullable=False),
    sa.Column('metadata_json', app.db.types.JSONColumn, nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.types.TZDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.TZDateTime(), nullable=False),
    sa.CheckConstraint('amount_paisa > 0', name=op.f('ck_expenses_ck_expenses_amount_positive')),
    sa.CheckConstraint('period_end >= period_start', name=op.f('ck_expenses_ck_expenses_period_ordered')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_expenses_product_id_products'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_expenses_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenses'))
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_expenses_tenant_kind', ['tenant_id', 'kind'], unique=False)
        batch_op.create_index('ix_expenses_tenant_period', ['tenant_id', 'period_start'], unique=False)

    op.create_table('expense_allocations',
    sa.Column('expense_id', sa.Uuid(), nullable=False),
    sa.Column('consignment_id', sa.Uuid(), nullable=False),
    sa.Column('amount_paisa', sa.BigInteger(), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('allocated_at', app.db.types.TZDateTime(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.types.TZDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.TZDateTime(), nullable=False),
    sa.CheckConstraint('amount_paisa >= 0', name=op.f('ck_expense_allocations_ck_expense_allocations_amount_non_negative')),
    sa.ForeignKeyConstraint(['consignment_id'], ['consignments.id'], name=op.f('fk_expense_allocations_consignment_id_consignments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], name=op.f('fk_expense_allocations_expense_id_expenses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_expense_allocations_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expense_allocations')),
    sa.UniqueConstraint('tenant_id', 'expense_id', 'consignment_id', name='uq_expense_allocations_expense_consignment')
    )
    with op.batch_alter_table('expense_allocations', schema=None) as batch_op:
        batch_op.create_index('ix_expense_allocations_consignment', ['consignment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_allocations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_allocations_expense_id'), ['expense_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_allocations_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_allocations_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_expense_allocations_expense_id'))
        batch_op.drop_index(batch_op.f('ix_expense_allocations_created_at'))
        batch_op.drop_index('ix_expense_allocations_consignment')

    op.drop_table('expense_allocations')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index('ix_expenses_tenant_period')
        batch_op.drop_index('ix_expenses_tenant_kind')
        batch_op.drop_index(batch_op.f('ix_expenses_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_product_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_created_at'))

    op.drop_table('expenses')
    # ### end Alembic commands ###
